### ISSUE TITLE
Search within VectorDataSource

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#100]
Separate service, uses full scan approach, usable for <100.000 objects. Two search methods with different as search conditions:

- [x] search within geometry (Point, Polygon, Line) + radius
- [x] add attribute (metadata) conditions with simple SQL-like syntax. Maybe later

Initially support search of Points only, ignore polygons and lines. Maybe later search for lines and polygons also.

**Comment by mtehver** [comment]
The new 'search' module implements this. It also supports searching from VectorTileDataSource and FeatureCollection
