### ISSUE TITLE
GeoJSON to/from LocalDataSource

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#101]
Adding x0.000 points to LocalDataSource may take many seconds, so bulk adding (and loading) makes sense in such cases. Two methods to LocalVectorDataSource:

- [x]  addGeoJson(String, style) to load GeoJSON data (in WGS84), all objects with given single style. If several styles needed, separate GeoJSON files have to be used
- [x]  getGeoJson() to export GeoJSON data from DataSource, ignore styling.

**Comment by mtehver** [comment]
This is now implemented in develop branch, though with little bit different API. As the SDK already has serialization to/from geojson using 'FeatureCollection' class, this was reused and the implemented methods are renamed to addFeatureCollection and getFeatureCollection.

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1
