### ISSUE TITLE
Adding metadata in the default VectorElement metadata collection does not work

### ISSUE THREAD

**Issue by Shtong** [CartoDB/mobile-sdk#107]
Hello,

I've seen this bug with the latest NuGet build of CartoMobileSDK.Android in a Xamarin app, as well as in the latest WinPhone10 build retreived from the GitHub releases page (sdk4-winphone-4.0.1-f956a659c22020f333398acd6f7e508b6d77ce48), still in Xamarin.

Basically the problem is that if I try to add a metadata entry to a `VectorElement` instance, it won't work. A workaround is to manually create and fill an instance of `StringVariantMap`, and then override the default collection with the new one.

To reproduce, create a new blank Xamarin Android app in Visual Studio, reference the CartoMobileSDK.Android NuGet package, and write this code in the activity:

```C#
protected override void OnCreate(Bundle bundle)
{
    base.OnCreate(bundle);

    // Set our view from the "main" layout resource
    // SetContentView (Resource.Layout.Main);

    LineStyleBuilder styleBuilder = new LineStyleBuilder
    {
        Color = new Color(255, 0, 0, 255),
    };

    MapPosVector positions = new MapPosVector();
    positions.Add(new MapPos(0, 0));
    positions.Add(new MapPos(10, 10));
    Line line = new Line(positions, styleBuilder.BuildStyle());

    // Method 1 - does not work
    line.MetaData.Add("key", new Variant("value"));
    Log.Debug("Metadata_repro", $"Method 1: {line.MetaData.Count}");
    // Output: D/Metadata_repro(31959): Method 1: 0

    // Method 2 - works
    StringVariantMap map = new StringVariantMap
    {
        { "key", new Variant("value") }
    };
    line.MetaData = map;
    Log.Debug("Metadata_repro", $"Method 2: {line.MetaData.Count}");
    // Output: D/Metadata_repro(31959): Method 2: 1
}
```

The documentation explicitly specifies that the Metadata getter "_Returns a modifiable meta data map_", which is clearly not the case.

**Comment by mtehver** [comment]
This is actually expected behaviour. When you access line.MetaData, then a copy of the actual metadata is created. The documentation is wrong and I have pushed a fix to the develop branch. Thanks for point this out.
