### ISSUE TITLE
Text readability issue in high zoom situations.

### ISSUE THREAD

**Issue by Shtong** [CartoDB/mobile-sdk#113]
Hello,

We are developing an application that contains a relatively high object density on city maps, and we need to draw texts that describe some of the objects. Because of the high density, we need the text objects to be small enough to some room left for the other elements. After some experimentation we think that ideally we need Text vector elements with a text size of 2 or 3pts for them to use an acceptable amount of space. We also want to scale them relatively to the ground.

The problem is, Text vector elements are rendered in a resolution that makes them unreadable in practice. It looks like the end result is a text that has been rendered in a tiny bounding box (something like 4 pixels height), and then upscaled.

For example (here with a zoom level of 21.6):

![image](https://cloud.githubusercontent.com/assets/1116681/26683399/eee4ce0e-46e3-11e7-8443-1feca7832576.png)

This example's text elements (the red blobs) were generated using the following style:

```c#
TextStyleBuilder defaultStyleBuilder = new TextStyleBuilder
{
    OrientationMode = BillboardOrientation.BillboardOrientationGround,
    FontSize = 2,
    CausesOverlap = false,
    Color = new Color(255, 0, 0, 255),
    ScalingMode = BillboardScaling.BillboardScalingWorldSize,
    Flippable = false,
    HideIfOverlapped = false,
};
```

Is there a setting I can play with that would allow me to improve this situation ?

Thanks

**Comment by mtehver** [comment]
Hi. You can try 'ScaleWithDPI' property. By default it is 'true', so try setting this to 'false'.

**Comment by Shtong** [comment]
Thanks for your answer

I have already tried this setting, but only in UWP, and I didn't notice the difference. On Android, it is better, but not enough for the text to be readable.

`ScaleWithDPI = false`on UWP:

![poc5_2_uwp](https://cloud.githubusercontent.com/assets/1116681/26820417/08e1e4e6-4aa3-11e7-8a66-11f080d72cc5.png)

`ScaleWithDPI = false`on Android:

![poc5_2](https://cloud.githubusercontent.com/assets/1116681/26820434/1503af8e-4aa3-11e7-911a-bd5dce8a224d.png)

**Comment by mtehver** [comment]
Thanks for the details. At first I missed the BillboardScaling.BillboardScalingWorldSize part which causes the issue here. Unfortunately there is no good workaround at the moment as the text is always rendered to a bitmap as a first step and the specified font size is used. A fix would be to add an additional attribute to API for specifying 'oversampling' of font size. I will keep the issue open, perhaps we will do this in SDK 4.1 version. 

Currently the only fix is to use a different BillboardScaling mode for texts.

**Comment by jaakla** [comment]
One thing you could try is to increase general DPI setting, for example double with:
```java
mapView.getOptions().setDPI(mapView.getOptions().getDPI()*2);
```

**Comment by jaakla** [comment]
SDK latest RC https://github.com/CartoDB/mobile-sdk/releases/tag/release%2Fv4.1.0-rc.3 has updated method to set text size: it is now in float instead of int. So you can set higher DPI (as given above), which increases everything, and then make texts smaller with high accuracy (use e.g. 1.5f pixels). Also you can try with higer values of setRenderScale() method, this also came with this latest build.

**Comment by mtehver** [comment]
Windows build for SDK 4.1RC3 is now available under 'Releases' section. As Jaak already mentioned, you can use TextStyleBuilder.RenderScale property to make the text sharper. The default value is 1.0, but you should probably use 4.0 (or even larger number). Closing this for now.

**Comment by jaakla** [comment]
Fix summary  : 
1. Use the latest SDK RC.3 build, nuget: `Install-Package CartoMobileSDK.UWP -Version 4.1.0-rc3`
2. Always set higher DPI for mapview if built for UWP (desktop) platform, this fixes base map rendering:
```c#
 MapView.Options.DPI = 240; 
```
3. Use new parameter _RenderScale_ in TextStyleBuilder:
```c#
   TextStyleBuilder MyStyleBuilder = new TextStyleBuilder
                {
                    OrientationMode = BillboardOrientation.BillboardOrientationGround,
                    FontSize = 2.0f,
                    CausesOverlap = false,
                    Color = new Carto.Graphics.Color(255, 0, 0, 255),
                    ScalingMode = BillboardScaling.BillboardScalingWorldSize,
                    Flippable = false,
                    HideIfOverlapped = false,
                    RenderScale = 8.0f // high value is needed if text is very small, just 2 pixels here
                };
```

@Shtong - does it work for you?

**Comment by Shtong** [comment]
Thanks for publishing the windows preversion on Nuget. I'm a little busy but I'll try to have a look this week and will get back to you with my findings.

**Comment by Shtong** [comment]
The fix does work, tested on both Android and UWP platforms.
