### ISSUE TITLE
Loading MBTiles (MVT files) in CartoDB Mobile SDK

### ISSUE THREAD

**Issue by carlos-mg89** [CartoDB/mobile-sdk#120]
Hi!

I have been considering quite seriously the CartoDB Mobile SDK to be used as a framework in my project. So far it looks really good to me and I think I just need a few more answers to finally go for it.

Is it possible to use in the free plan the loading of MBTiles (MVT Tiles)? Is there any limitation with it?

Does the "75,000 map views/month with standard basemaps" limitation apply to the MVT tiles too? Or only to the online service?

I ask here, because it seems the guys that are in charge of the contact email don't know these details. And I really need to know about it.

Cheers and thanks in advance

**Comment by jaakla** [comment]
Yes, you can use own mbtiles with free sdk. Map views are not counted then.

**Comment by carlos-mg89** [comment]
Thanks for answering @jaakla 

What about the limitation of 10.000 public users for the mobile SDK? Will that be a restriction too or would it be unlimited because I am using my own mbtiles and I'm not using at all the CartoDB servers?

**Comment by jaakla** [comment]
10,000 user limitation still holds, also the app needs to be public

**Comment by carlos-mg89** [comment]
@jaakla public means free to download in the App Store/Google Play, at no cost, right?

**Comment by jaakla** [comment]
Yes, exactly

**Comment by carlos-mg89** [comment]
@jaakla Thanks for all the information :+1:
