### ISSUE TITLE
Replace map samples in doc

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#122]
Remove Bing and ESRI, add HERE maps and satellite here:
https://carto.com/docs/carto-engine/mobile-sdk/loading-map-data#microsoft-bing-maps

**Comment by Nikituh** [comment]
As this is a minor fix with no real need for a review, merged straight to master. @csobier Let's go live!

**Comment by csobier** [comment]
Ok @Nikituh , just refreshed the docs!
