### ISSUE TITLE
Server URL unification

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#123]
Adjust backend URL prefixes, so there is unique service prefix for all different things. Two issues with current URLs:

* for adding new data sources need of reconfiguring request "proxies" (cdn, nginx,varnish).
* CDN/nginx config becomes messy and issues can happen in management

[Internal doc](https://docs.google.com/document/d/11-DeWHFEsDHZR8MXcYpebhiva6sp9qqfcBvlRNON78E/edit) with URLs in different SDK versions.

- [x] tiles.json for maps - add /maps/ prefix
- [x] /maparea/ prefix for custom maps packages, remove /custom/
- [x] /routearea/ prefix for route packages, remove /custom/
- [x] /geocodearea/ prefix instead of /geocoding/ - just to fit the pattern of other custom packages
- [x] Fix same URLs in SDK 4.1.0 side @mtehver 
 
@cellum

**Comment by jaakla** [comment]
@mtehver updated URLs should work now in server side, doc and tests in runscope are updated.

**Comment by mtehver** [comment]
@jaakla SDK develop branch is now updated according to the new spec. There is a small discrepancy regarding 'maparea' service vs 'routearea' or 'geocodearea': maparea requests do not include additional version number (after the source id) while other requests do. For example:

http://api.nutiteq.com/maparea/v2/carto.streets/wzAzAzAzDMwUTEfwXBV8FwVVPMTUA9dQ1DXUNQAAAPDw8PD8FwVfBcFVQ_XUNQ11DUAAAAAAAAAA.mbtiles?appToken=...

vs

http://api.nutiteq.com/routearea/v2/carto.streets/1/wzwwMMDAwxHRAPPM89Q1AA_UNQAAAAAAAAAA.vtiles?appToken=...

Should we leave this as it is or include version for 'maparea' service also?

**Comment by jaakla** [comment]
Good point, lets have this /1/ - data structure version there. If there are newer incompatible data versions, then the number increases.

**Comment by mtehver** [comment]
The /1/ schema is now used for mappackages also (commit 05c2e20)

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1
