### ISSUE TITLE
Bundle CartoCSS (Builder) fonts with SDK

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#126]
Currently SDK bundles fonts used in basemaps, but not the ones what can be used in CARTO Builder visualizations. Therefore for CARTO visualizations app has to bundle own additional fonts.

* Currently only bundled styles use bundled fonts. Change SDK so custom cartocss decoder would try to find fonts also from SDK bundle; 
* Review selection of fonts - maybe basemaps and CARTO fontset can be unified more
* add common CARTO cartocss selectable fonts to SDK package. Adding all would be probably way too big in terms of bytes. E.g. first default "Dejavu Sans Book"

**Comment by mtehver** [comment]
Bundling all the fonts used by Builder would make the SDK binary probably too large. Besides, only limited users of the SDK would benefit from this. A better idea is to make it easy to add custom fallback fonts to VectorTileDecoder, for example.

**Comment by mtehver** [comment]
Closing this, as SDK 4.2 has option to specify fallback fonts.
