### ISSUE TITLE
Add SVG parser/renderer for CartoCSS icons

### ISSUE THREAD

**Issue by mtehver** [CartoDB/mobile-sdk#127]
Icon set are usually distributed as SVG files. Currently SDK requires all SVG images to be converted into raster images. For better compatibility, try to integrate NanoSVG parser/renderer into the SDK.

**Comment by jaakla** [comment]
Btw Mapbox converts SVG in style projects to sprite png (texture atlas)+json in servers-side, using https://github.com/mapbox/spritezero

**Comment by Shtong** [comment]
I haven't looked at 4.1 yet, but would this allow us to use SVG image sources with a Mark geometry in a LocalVectorDataSource for example ?

**Comment by mtehver** [comment]
@Shtong Not at the momement, but we may add this in the near future.

**Comment by mtehver** [comment]
Implemented, closing.

**Comment by jaakla** [comment]
this was fast 👍
