### ISSUE TITLE
Release the three Xamarin versions as a single multi-platform Net Standard package

### ISSUE THREAD

**Issue by Shtong** [CartoDB/mobile-sdk#128]
It would be very nice if we wouldn't have to handle different packages for different platforms with Carto Xamarin. It would also allow us to develop multi-platform libraries using PCL projects instead of Shared Projects, and make our code easier to test and reuse / distribute. Since all Xamarin platforms are now compatible with NetStandard 1.3, it wouldn't probably be too hard to create a single Net Standard package containing all three versions of the library.

**Comment by Nikituh** [comment]
Hey

Great proposal! Unfortunately, the implementation is not as simple as one would think, as our MapView is a native Android/iOS/UWP view. PCL projects are for pure C# libraries, our library is not a native C# library. It would be like wrapping Android's RelativeLayout and iOS's UIView together – something the Xamarin.Forms team hasn't yet perfected.

However, Microsoft is constantly building upon PCL and updating .NET standard. Perhaps some time in the future it'll allow to wrap native code!

Best wishes
Aare
CARTO Mobile
