### ISSUE TITLE
[doc] update routing and add geocoding for 4.1 API

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#129]
Add geocoding page, and update routing to valhalla.

**Comment by Nikituh** [comment]
* Created packagemanager.md: https://github.com/CartoDB/mobile-sdk/blob/documentation/doc/packagemanger.md
* Created geocoding.md: https://github.com/CartoDB/mobile-sdk/blob/documentation/doc/geocoding.md
