### ISSUE TITLE
Add basic info about how to publish mobile apps

### ISSUE THREAD

**Issue by csobier** [CartoDB/mobile-sdk#133]
@csobier commented on [Wed Aug 10 2016](https://github.com/CartoDB/docs/issues/981)

Add general info about how to publish your apps on the app store and/or manage any changes to your apps.

@jaakla for awareness, will assign to a future Sprint, when time allows.

---

@csobier commented on [Tue May 02 2017](https://github.com/CartoDB/docs/issues/981#issuecomment-298687035)

@jaakla , still interested in adding this to the docs? Perhaps as an FAQ?  Let me know, otherwise, we can close this issue.

---

@jaakla commented on [Tue May 02 2017](https://github.com/CartoDB/docs/issues/981#issuecomment-298766437)

We have a bit longer list of TODOs pending with ideas how to make the section more usable, see https://github.com/CartoDB/mobile-sdk/issues/86 . FAQ would be one part there.

---

@csobier commented on [Wed May 03 2017](https://github.com/CartoDB/docs/issues/981#issuecomment-298890178)

Okay, keep me posted. I'll keep this open for now...

**Comment by jaakla** [comment]
I'd leave this out, this is not specific to our SDK.
