### ISSUE TITLE
SDK 4.1 offline package upgrade guide

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#135]
SDK 4.1 has different offline packages, so users who have already downloaded offline maps need to re-download it again. However, it would be nicer from end-user point if app is able to continue to work after app/SDK update, with old maps.

Prepare guide to SDK wiki with code sample (in Android/Java?) how to nicely update map data: 

a) keep user state - use old or new map version. No need to support mixed case (some packages old, some new)

b) provide package download suggestion. 
* For most packages it is 1:1
* Some packages are deprecated (big FR, DE), so user has to download smaller packages
* Some packages have smaller subpackages (RU, IT, JP etc), so users can optionally select smaller regions

c) configure mapview layers/style based on user state. App needs old style as custom style package to be able to render old maps.

**Comment by mtehver** [comment]
A basic upgrade guide with high-level suggestion is now under Wiki

**Comment by jaakla** [comment]
https://github.com/CartoDB/mobile-sdk/wiki/Upgrading-from-3.x-and-4.0.x-to-4.1
