### ISSUE TITLE
get showing map bound

### ISSUE THREAD

**Issue by AliKhoshraftar** [CartoDB/mobile-sdk#137]
how to get showing map bound from mapview or projection or everthing else ?
projection.getBounds() return all over world's bounds . but i want to get current view map bounds that showing in screen only.

**Comment by Nikituh** [comment]
Hey!

Unfortunately, this is not a trivial task and there's no direct function in our API. 

However, you should check out our Swift and Kotlin examples that feature a **ScaleBar view** where this is calculated.

cf:
* Kotlin: https://github.com/CartoDB/mobile-android-samples/blob/master/AdvancedMapKotlin/app/src/main/java/com/carto/advanced/kotlin/components/ScaleBar.kt#L85
* Swift: https://github.com/CartoDB/mobile-ios-samples/blob/master/AdvancedMap.Swift/Feature%20Demo/ScaleBar.swift#L80

**Comment by jaakla** [comment]
Please post SDK usage questions to stackoverflow (with carto-mobile tag) and these will be answered. This project's GH issues are meant for bugs, ideas or specific feature request which are related to SDK itself.
