### ISSUE TITLE
Error configuring the dependencies?

### ISSUE THREAD

**Issue by jmlipman** [CartoDB/mobile-sdk#138]
When I tried to build it for Android I get the following error: OSError: [Errno 2] No such file or directory

It seems that I didn't configure the paths properly (maybe the "boost"...). I think I'm confused about the third command written in the building process: "ln -s ../../sdk_3d/all/libs/boost # change to folder where you have boost libs!". I can't simply find those files? Where is that sdk_3d folder? I cannot find it in my Android/Sdk folder nor in the extracted boost files.

I tried to download the boost_1_65_1.tar.gz file, extract it and add ln -s boost.

Thanks.

**Comment by jaakla** [comment]
There are quite a few dependencies, and boost requires specific folder levels. You may find this build script (used by travis) useful: https://github.com/CartoDB/mobile-sdk/blob/master/scripts/travis/prerequisites.sh

**Comment by jaakla** [comment]
Closing the issue, as it is not about specific SDK bug or feature, what we can directly fix. Feel free to add comments here anyway.
