### ISSUE TITLE
Error when passing very long string to BalloonPopup

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/mobile-sdk#140]
## Context

while playing a bit with the SDK I found that passing a long string to the balloon popup method breaks the application. 

## STR

1 . Execute the code on `MainActivity.java`. 
2 . I was running a Nexus 5 Android 7.1 API 25 emulator
3 . Click on any feature, it will run a query using the CartoSQLService class and try to call the balloon popup constructor with the result, which is a very long string
4 . See error log

## files

[Archive.zip](https://github.com/CartoDB/mobile-sdk/files/1368517/Archive.zip)

content: 

* error_log.txt
* MainActivity.java

**Comment by mtehver** [comment]
Thanks for reporting! The string requires very large bitmap canvas (approximately 1000x140000 pixels) to render, thus causing the fail. A fix (that simply discards the popup) is now commited in master. Closing.
