### ISSUE TITLE
Performance issues with the UWP build when MapView is initialized while being hidden

### ISSUE THREAD

**Issue by Shtong** [CartoDB/mobile-sdk#142]
Hello,

We have an application screen where the user can switch between a form and a Carto map control. The screen initially opens showing the form, but the UI actually contains both form and map, hiding /showing each control when the user presses a button.

While this setup works fine on Android, it is causing serious performance issues on UWP (untested on iOS). When the MapView is created, hidden from the interface, it seems to keep creating and killing threads in a loop, permanently using 8~10% CPU, until the map is actually visible on the screen. When the map shows on the screen for the first time, the performance problems stops. If the user changes screen without showing the map on screen (ie. if the MapView is destroyed without being shown at all), the entire app UI becomes unstable.

**Reproduction steps:**

- Create a new blank UWP app, with the defaults settings using Visual Studio 2017, and name it `ReproCartoThreadSpam`
- Add the `CartoMobileSDK.UWP` NuGet package to the project. The tested version is 4.1.0.
- In MainPage.xaml, put the following markup:
```xaml
<Page
    x:Class="ReproCartoThreadSpam.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:carto="using:Carto.Ui"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Button HorizontalAlignment="Right"
                VerticalAlignment="Top"
                Content="Switch map visibility"
                FontSize="20"
                FontWeight="Bold"
                Margin="20" Click="Button_Click"/>
        <Border x:Name="mapContainer" Visibility="Collapsed">
            <carto:MapView x:Name="mapView" />
        </Border>
    </Grid>
</Page>

```
- In MainPage.xaml.cs, add the following method to the existing class:
```cs
private void Button_Click(object sender, RoutedEventArgs e)
{
    if (mapContainer.Visibility == Visibility.Collapsed)
        mapContainer.Visibility = Visibility.Visible;
    else
        mapContainer.Visibility = Visibility.Collapsed;
}
```
- Make sure the app compiles, and run it

**Expected results:**
Once the application has finished initializing, its use of system resources is stable, and it does not use much CPU. Clicking the *Switch map visibility* button has no noticable effect on resource usage.

**Actual results:**
Once the application has finished initializing, it is rapidly creating and destroying threads, and consistently uses more that 5% of the CPU cycles. When the *Switch map visibility* is clicked, effectively showing the map, the performances problems disappear.

**Comment by mtehver** [comment]
@Shtong Thanks for reporting this. Should be fixed now, a test build with the fix is available from here: https://drive.google.com/open?id=0B1TVGN1snTrnNVRCYUVVU19hdlU
