### ISSUE TITLE
HTTPTileDataSource headers not used

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#143]
Apparently the headers are not used even if set:
https://github.com/CartoDB/mobile-sdk/blob/9f69d558b1b1f7c29b932cb3beb47880d160720f/all/native/datasources/HTTPTileDataSource.cpp#L102

That's an issue with some we tile providers like IGN (France) which require the "User-Agent" header

**Comment by mtehver** [comment]
Thanks for reporting this. We will have the fix in 4.1.1 release.
