### ISSUE TITLE
setFocusPos not centered when rotating the map

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#144]
at first if i use  ```setFocusPos``` without rotating the map, the center point is correctly set at the center of the map view.
But when i rotate the map using two fingers, then call ```setFocusPos``` i can see that the focusPoint is decaled a bit from the center of the map view. I see in my app because i draw a crosshair at the exact middle of the map view.
And when i want to focus on a marker i use ```setFocusPos``` and expect the marker to be right under the crosshair

**Comment by mtehver** [comment]
Can you elaborate a bit - are you calling setFocusPos while still rotating the map using fingers? Or after that? Any chance of screenshots or more detailed description?

**Comment by farfromrefug** [comment]
The thing i cant really give an easy example because i am implementing Carto as a module through Titanium mobile. So my actual code is in javascript and pretty complex.

However here are 2 screenshots.
- First one just after running the app and "centering" on the marker using ```setFocusPos```
- i then rotate the map (which obviously pans it a bit as i do it using fingers)
- i can ```setFocusPos``` again on the same exact ```MapPos``` (Marker pos) =>2nd screenshot
![screenshot_20171101-164739](https://user-images.githubusercontent.com/655344/32283409-8bda2af2-bf24-11e7-9917-b86e4074d877.png)
![screenshot_20171101-164748](https://user-images.githubusercontent.com/655344/32283422-903a9e9c-bf24-11e7-8a53-bdeaa156dbfe.png)

**Comment by mtehver** [comment]
Is there any chance that the map view is larger than the visible area shown on the screenshots? That could cause the effect.

**Comment by farfromrefug** [comment]
@mtehver the view goes "under" the top toolbar and the bottom toolbar (which is why we dont see the carto logo there).
But why would it change it "horizontally" as we rotate? 
How can i fix this?

THanks

**Comment by mtehver** [comment]
I am not entirely sure what is going on. Perhaps for debugging, can you log and check the 'screen position' of the mapView in both cases (unrotated and rotated)? The following Java snippet demonstrates this:

```
ScreenPos pos = mapView.mapToScreen(mapView.getFocusPos());
Log.d(TAG, pos.toString());
```

I assume that you use default anchor point for your markers (bottom/horizontally centered)?

**Comment by farfromrefug** [comment]
@mtehver thanks for helping me. After a lot of testing and actually creating a sample app, i figured out that the issue was on my side. Before, while using google maps, i was adjusting the "setFocusPoint" depending on the padding of the view. I totally forgot about that :s 
Sorry and thanks again for your help!
