### ISSUE TITLE
[FR] customize online vector source CSS

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#145]
I don't think there is arleady a way to do this.
My app is made for hiking purpose, i am looking at switching from google maps to carto. However carto default styles like voyager do not show peaks. 
It would really be nice to be able to update the css to change things like this.

I am even willing to create a PR if you are ok with this (and if it is actually possible...)

**Comment by jaakla** [comment]
The Voyager style is designed to be a background map, and we want to keep it clean, this is why it does not show some layers.

However, you can use your customized style without changing SDK:

1) take latest built-in style package: https://github.com/CartoDB/mobile-sdk/blob/master/assets/cartostyles-v1.zip
2) Unzip and edit css in it, e.g. _voyager_. I know it is not very simple or graphical, but right now we don't have better tool for it. Our used [data schema](https://openmaptiles.org/schema/#mountain_peak) seems to have special layer **mountain_peak** for what you ask 
3) zip it again in same way, add to project assets
4) use it as custom style:
```java
 // load style from zip file in assets
MBVectorTileDecoder baseStyleDecoder = new MBVectorTileDecoder(new CompiledStyleSet(new ZippedAssetPackage(AssetUtils.loadAsset("cartostyles-v1.zip")), "voyager"));
// create layer
VectorTileLayer urlLayer = new VectorTileLayer(new CartoOnlineTileDataSource("carto.streets"), baseStyleDecoder);
// add it to the map
mapView.getLayers().add(urlLayer);
```

**Comment by farfromrefug** [comment]
@jaakla that s amazing 👍  Will try that right away.

carto web does not have a way to create such a thing and then use it witch ```CartoMapsService```?

**Comment by jaakla** [comment]
no, unfortunately carto web allows to style only overlays :(

**Comment by farfromrefug** [comment]
@jaakla no problem. Thank you! (i clsoe that issue as it is solved for me even if not tested)

**Comment by farfromrefug** [comment]
@jaakla i tried and managed to load my style just fine.
Now i am looking at a to test my modifications fairly quickly without having to rebuild my app everytime.
Could i load my zip asset in cartodb.js? 
Do you have a web renderer for your vector maps?

Thanks

**Comment by jaakla** [comment]
We don't have web renderer and there is no plan to have it with this styling language. We're providing basemaps in vector for other web renderers like openlayers or mapbox-gl-js libraries

**Comment by farfromrefug** [comment]
@jaakla no problem. I just saw this:
https://github.com/mapbox/mapbox-studio-outdoors.tm2
It seems to use the same style as you do in the sdk. Does it mean i can use those mss files?
Thanks (already have mountain peaks on my map!!!!)

**Comment by jaakla** [comment]
Probably not, mapbox has different data structure. We use currently OpenMapTiles structure, and here you can find some compatible styles: https://openmaptiles.org/styles/ . None of the vector rendering libraries can use cartocss, they all have different styling languages.

**Comment by farfromrefug** [comment]
@jaakla really cool !
https://github.com/openmaptiles/klokantech-terrain-gl-style is just what i want. Now how do i integrate this? Do i just zip and use the json file name as a key to ```CompiledStyleSet``` ? 
Maybe there is a doc somewhere that i did not see?

I am sorry to bother you, once i got i wont anymore ;)

**Comment by farfromrefug** [comment]
@jaakla sorry to bother you again. After a lot of searching it seems the link you pointed me too refers Mapbox compatible styles:
https://www.mapbox.com/mapbox-gl-js/style-spec/
Though i dont see how to use them in cartoDB. Can you help?
THanks

**Comment by jaakla** [comment]
It depends what do you mean by "mapbox compatible" here. CARTO vector tiles (both basemap tiles and tiles from CARTO Maps API) are in mapbox-compatible PBF format, so you can use them with mapbox-gl-js library. You just need compatible styling (style.json file) and openmaptiles styles page provides some, including tool to edit them (Maputnik). You cannot use mapbox own Studio for editing map, as this supports only their own tiles, which are in different data structure (i.e. different layers and attributes). Style language is still the same. In other words, we are compatible with mapbox open source software, but not to their basemap service data structure (which is not open source).

We have a sample of carto vector basemap with mapbox-gl-js library here: http://tiles.basemaps.cartocdn.com/gl/voyager-gl-style/index.html. Note that this is work in progress, not published yet.

**Comment by farfromrefug** [comment]
@jaakla I dont want to use your tiles with mapbox! I want to stick with cartoDB. 
What i just want is to be able the style/theme my map view on android with CartoDB
You pointed be to https://openmaptiles.org/styles/ for style.
The thing is that those styles are in a JSON format and i dont see how to use them in CartoDB mobile SDK. This is where i am asking for your help

I would really like to try the "Klokantech Terrain" style as it has everything i want. It even has contour lines, but i think for that i need mapbox vector tiles.

I hope i am clearer
Thanks

**Comment by jaakla** [comment]
Ok, I thought you want web rendering? CARTO does not have own web renderer, and we use other opensources there ourselves, for example Mapbox-gl-js.

CARTO Mobile SDK takes only CartoCSS styles. The same https://openmaptiles.org/styles/ page has in the end some CartoCSS styles also, but yes, the others there, including terrain is in mapbox-gl style format which is not usable with our mobile SDK without manual converting to cartocss. And in the other hand, there is are web map renderers for cartocss styles, so if you need to have map for both mobile/native and web, then you would need to use two parallel styles.

**Comment by farfromrefug** [comment]
@jaakla thanks that s clearer. Just so you know i dont need  web rendering, i only wanted it for fast style editing.
I am really good with your mobile SDK! I will look at converting the GL style to cartoCSS. Maybe there is a converter somewhere. Thanks ! :)
Do you plan on adding the GL style support?

THanks

**Comment by jaakla** [comment]
We don't have plan to add gl style to mobile SDK. With quick search I found https://github.com/FoxGIS/mapbox-gl-json-to-mapnik-xml which creates Mapnik XML style (not cartocss), but same XML style is supported by mobile SDK also ([see sample package](https://github.com/CartoDB/mobile-android-samples/blob/master/AdvancedMapAndroid/app/src/main/assets/styles_mapzen.zip)).

**Comment by farfromrefug** [comment]
@jaakla awesome i was looking for a conversion to CartoCSS and could not find anything!
Thanks!
