### ISSUE TITLE
Mixin of 2 layers and Zindex

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#149]
Sorry about the title, was hard to find the right one!

I have 2 layers in my app:
- Carto vector layer
- Mapbox vector terrain for contour lines

The thing is i am facing issue make the both work correctly together.
If you had contour lines, you expect them to be over the landuse but under road and other data.

Now this is how it looks on my app.
![screenshot_20171109-153623](https://user-images.githubusercontent.com/655344/32610787-13442336-c564-11e7-8093-772df7c0a0b6.png)

Is there a way to acheive this?
Thanks

**Comment by mtehver** [comment]
There is no easy way to do this. In theory you could take the basemap style of Carto SDK, split it into 2 sections. Then you have to use 3 layers, the first and the last should be from the split style. The middle layer can use MapBox data source. But this would be most likely slow due to 2 data sources.

**Comment by farfromrefug** [comment]
@mtehver how is z order define within a vector source? How is it decided if a road is drawn on top of landuse? is it just the style definition order?
Could be we thing of a merge source? I mean a source that would combine 2 vector sources, store them together and them draw at the same time elements from both sources using the same style. That would sove that case i think.

**Comment by mtehver** [comment]
z-order is not defined within vector sources, but rather in style description. You can check the voyager.json file from the assets/cartostyles-v1.zip file. 

But technically you could achieve the effect also by creating custom datasource and creating a custom style. Then you do not have to create 3 separate layers. Your custom datasource must:

* download basemap tile from CARTO
* download contours tile from MapBox
* extract the layers from both data sources, and create a new tile containing the concatenated layers

I am not 100% sure but I think the third step can be actually implemented very easily due to protobuf encoding - you can simply treat the tiles as BLOBs and concatenate the BLOBs

There are downsides with custom sources/styles, though. CARTO may decide to upgrade/update the style and/or the tile structure. We will not give any guarantees that your solution will work after that.

**Comment by farfromrefug** [comment]
@mtehver first thanks for the idea i was not sure i could simply concat the blobs.
Now about upgrade/update issue. I have no problem with that!

THanks will try and report here. That could help someone else.

**Comment by farfromrefug** [comment]
@mtehver It works perfectly:
![screenshot_20171113-114322](https://user-images.githubusercontent.com/655344/32721927-7ee0d5b0-c868-11e7-85af-e403ec9fd7e7.png)
Now i do have hickups just like in my other issue https://github.com/CartoDB/mobile-sdk/issues/153
For reference here is the class:
```java
package akylas.carto;

import java.nio.ByteBuffer;

import com.carto.core.BinaryData;
import com.carto.core.MapBounds;
import com.carto.core.MapPos;
import com.carto.core.MapTile;
import com.carto.datasources.TileDataSource;
import com.carto.datasources.components.TileData;
import com.carto.projections.Projection;

public class MergeTileDataSource extends TileDataSource {
    TileDataSource[] sources;
    TileDataSource firstSource;
    int sourcesCount;
    int minZoom = -1000;
    int maxZoom = 1000;
    public MergeTileDataSource(TileDataSource... sources) {
        this.sources = sources;
        firstSource = sources[0];
        sourcesCount = sources.length;
        MapBounds bounds = firstSource.getDataExtent();
        double minX = bounds.getMin().getX();
        double minY = bounds.getMin().getY();
        double minZ = bounds.getMin().getZ();
        double maxX = bounds.getMax().getX();
        double maxY = bounds.getMax().getY();
        double maxZ = bounds.getMax().getZ();
        
        minZoom = firstSource.getMinZoom();
        maxZoom = firstSource.getMaxZoom();
        for(int i = 1; i< sourcesCount; i++) {
            TileDataSource source = sources[i];
            minZoom = Math.max(minZoom, source.getMinZoom());
            maxZoom = Math.min(maxZoom, source.getMaxZoom());
            
            bounds = sources[i].getDataExtent();
            if (bounds.getMin().getX() < minX) {
                minX = bounds.getMin().getX();
            }
            if (bounds.getMax().getX() > maxX) {
                maxX = bounds.getMax().getX();
            }
        
            if (bounds.getMin().getY() < minY) {
                minY = bounds.getMin().getY();
            }
            if (bounds.getMax().getY() > maxY) {
                maxY = bounds.getMax().getY();
            }
        
            if (bounds.getMin().getZ() < minZ) {
                minZ = bounds.getMin().getZ();
            }
            if (bounds.getMax().getZ() > maxZ) {
                maxZ = bounds.getMax().getZ();
            }
        }

        
        this.bounds = new MapBounds(new MapPos(minX, minY, minZ), new MapPos(maxX, maxY, maxZ));
    }
    
    @Override
    public TileData loadTile(MapTile tile) {
        TileData result = null;
        int zoom = tile.getZoom();
        for(int i = 0; i< sourcesCount; i++) {
            TileDataSource source = sources[i];
           if (zoom <= source.getMaxZoom() && zoom >= source.getMinZoom()) {
               TileData sourceResult = source.loadTile(tile);
               if (result == null) {
                   result = sourceResult;
               } else if (!result.isReplaceWithParent()){
                   byte[] data1 = result.getData().getData();
                   byte[] data2 = sourceResult.getData().getData();
                   ByteBuffer bb = ByteBuffer.allocate(data1.length + data2.length);
                   bb.put(data1);
                   bb.put(data2);
                   result = new TileData(new BinaryData(bb.array()));

               }
           }
            
        }
        return result;
    }

    @Override
    public Projection getProjection() {
        return firstSource.getProjection();
    }
    @Override
    public int getMinZoom() {
        return minZoom;
    }

    @Override
    public int getMaxZoom() {
        return maxZoom;
    }
    
    MapBounds bounds = null;
    MapBounds getBounds() {
        return bounds;
    }


    @Override
    public MapBounds getDataExtent() {
        return getBounds();
    }
    
    @Override
    public void notifyTilesChanged(boolean removeTiles) {
        for(int i = 0; i< sourcesCount; i++) {
            sources[i].notifyTilesChanged(removeTiles);
        }
    }
}

```

**Comment by farfromrefug** [comment]
Also now in the logcat i see ```MBVectorTileDecoder: Duplicate layer name: landcover``` for every ```loadTile```
This is actually normal because the 2 sources bring ```landcover``` . Could that be the source of hick ups?

**Comment by mtehver** [comment]
That should be 'ok' in the sense that the 2nd layer definition is simply ignored. TBH, I am not sure what causes the hiccups as tile loading is done asynchronously (in a different thread) from the renderer.

**Comment by farfromrefug** [comment]
@mtehver thanks for answering. I will try to investigate it!

**Comment by farfromrefug** [comment]
@mtehver I would like to create a PR to add my MergeTileDataSource to the native framework. But i need your help. On the C side i don't see how to do the BinaryData concat. Can you guide me?

Thanks

**Comment by mtehver** [comment]
@farfromrefug You can try the following snippet

```
std::shared_ptr<std::vector<unsigned char> > data1 = binaryData1->getDataPtr();
std::shared_ptr<std::vector<unsigned char> > data2 = binaryData2->getDataPtr();

std::vector<unsigned char> mergedData(*data1);
mergedData.insert(mergedData.end(), data2->begin(), data2->end());
auto mergedBinaryData = std::make_shared<BinaryData>(std::move(mergedData));
```

I think the best name for the class would be `MergedMBVTTileDataSource`, as it assumes MBVT/protobuf encoding. I will likely have to make some changes to the code once you have submitted this as in some cases the tiles can be gzipped and thus need to be unzipped before concatenating.

**Comment by farfromrefug** [comment]
I ll close this for now as the work is happening in the PR
