### ISSUE TITLE
[Android] mapView onResume

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#150]
In the Android doc i see that ```MapView``` has ```onPause``` and ```onResume``` activities.
So i thought i needed to use them in my app.
When do i see refreshing whenever i come back to my activity:
![a3y17ltexxnrd90mmguillon11092017154129](https://user-images.githubusercontent.com/655344/32611041-ccd7af8e-c564-11e7-9ed9-3730c2ffedb0.gif)
Looking at the sample app this does not seem to be called (which might be why we dont see the issue):
https://github.com/CartoDB/mobile-android-samples/blob/master/AdvancedMapAndroid/app/src/main/java/com/carto/advancedmap/baseclasses/activities/MapBaseActivity.java

Should i NOT call those methods? What the consequence of using/not using them?

Thanks

**Comment by mtehver** [comment]
Yes, simply do not call these methods. Note that onPause releases map-related resources to make more space for other activities. This is so by design.

**Comment by farfromrefug** [comment]
@mtehver thanks i wont!
