### ISSUE TITLE
drawing issue with line and rgba colors

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#151]
If i assign a rgba color to a line with ```setColor``` i can see some drawing issues in curves.
![screenshot_20171109-154519](https://user-images.githubusercontent.com/655344/32611220-53fe5ed6-c565-11e7-9a34-4d06f53f7493.png)

is that solvable?

Could we may be get an ```opacity``` property for ````VectorElement``` that would solve that issue?

Thanks

**Comment by mtehver** [comment]
This is a known issue and happens with half-transparent overlapping lines. We do not plan to fix this due to major performance impact and some none-trivial techical complexity. The workaround is to carefully choose another color for the line that has alpha=1.0.

**Comment by farfromrefug** [comment]
@mtehver what about an opacity property for all VectorElement? That would solve the issue

**Comment by mtehver** [comment]
@farfromrefug Actually that was the option I described (basically adding an 'opacity' property of Layer objects), it is expensive performance-wise (separate drawing surface, full screen blending of the surface) and proper implementation would require lots of change. I am keeping this open now, but as I said earlier, we do not have this on the roadmap.

**Comment by farfromrefug** [comment]
@mtehver sorry i thought you were talking about the drawing of every single ```VectorElement```. Is that difficult too?

I understand your point about layer and surfaces. It would be a great addition, especially for people trying to migrate from google maps, but i understand it might be technically chalenging.
And i can live without it!

Thanks

**Comment by jaakla** [comment]
Another report of same: https://gis.stackexchange.com/questions/269219/avoid-alpha-summation-in-line-that-overlap-itself-in-carto-mobile-sdk/269413#269413

**Comment by jaakla** [comment]
There is now remedy for this: you should draw lines without any transparency, but then set Opacity for whole Layer as per #184 , now available since SDK 4.1.3
