### ISSUE TITLE
Valhalla offline routing does not work with 'multimodal' profile

### ISSUE THREAD

**Issue by mtehver** [CartoDB/mobile-sdk#159]

**Comment by mtehver** [comment]
This is somewhat improved now, but there are still issues, including missing timezone info from graph nodes in actual packages.

**Comment by bachph** [comment]
When I try the app, I also get everytime a toast that the routing failed. Does it work all well if the license is switched?

**Comment by mtehver** [comment]
Marking this as 'wont fix'. We will not be shipping Valhalla routing with SDK 4.2. The support is still present in the project source code but we will exclude it from official builds.
