### ISSUE TITLE
Customize offline MBTiles vector tiles [iOS]

### ISSUE THREAD

**Issue by RandyHBH** [CartoDB/mobile-sdk#163]
I create an MBTiles vector tiles using OpenMapTiles and now I want to styling it, what i want is that in the points of interest I see a representative icon of the same not only the title, try to find some info about this, but nothing is clear. Also try whit the [example in AdvancedSwift ios example](https://github.com/CartoDB/mobile-ios-samples/blob/master/AdvancedMap.Swift/Feature%20Demo/StyleChoiceView.swift) whitout luck. If you could help me with an example or explaining how to do it, I would greatly appreciate it.

Regards

**Comment by jaakla** [comment]
Unfortunately we do not have easy-to-use styling tool, it has to be done by manually editing text files in the zip which defines the style. Some hints:
 - check out built-in style package, you can see .mss files (cartocss files) which define styling based on OpenMapTiles schema: https://github.com/CartoDB/mobile-sdk/blob/master/assets/cartostyles-v1.zip
 - https://github.com/CartoDB/mobile-sdk/wiki/CartoCSS-notes - technical details how we implement CartoCSS

If you want to practise CartoCSS, you can try [Mapbox Studio Classic](https://www.mapbox.com/mapbox-studio-classic/), but this does not work with our styles directly, as we have done a few extensions to CSS itself. You can load vector tile URL as data source there through to build new styles.

**Comment by RandyHBH** [comment]
hi, i add a new poi.mss file to keep the things in place, maybe is a silly question but how i can genereta de md5 and size values that i need to include in the voyager.json file

**Comment by mtehver** [comment]
hi. you do not need to set these values, they are only needed for built-in styles, so that the sdk can download style updates automatically.

**Comment by mtehver** [comment]
Closing this. I think the questions were answered. Just a small note: we have included a Python script for generating MD5 hashes in the zipped style asset: https://github.com/CartoDB/mobile-sdk/blob/master/assets/cartostyles-v2.zip
