### ISSUE TITLE
Support reduced style packages

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#164]
Currently most of SDK binary footprint is style asset, and specifically one font (NotoSansPlus) and most of it is one specific language - Korean Hangun script, which is about 4MB extra. When we remove the font, then all CJK languages will disappear on the map, which makes big part of the world essentially nameless.

Possible quite optimal solution would be a processing script which parses planet file and gets list of used glyphs, and then creates clean font set with only really used glyphs outside of standard Latin typography.

Another solution would be to include minimal style (without CJK or just without K of it), and allow users to use custom style package. The problem here is that with this one the app footprint would be even larger. Also this custom app-provided style would not support style updates. So for this solution we'd need to add to API user control which style package they want to use: "lite" or with all languages. Also server should include both variations as different styles.

Until we dont have either solution I'm bundling full big style to SDK, so users upgrading SDK will not get sudden loss of all texts on map in big regions. Known issue is that the SDK and eventually mobile app footprint is increased by several MB.

**Comment by mtehver** [comment]
The develop branch now includes a stripped font. The stripped font was created using chars_from_packages.py script (basemap-styles repo).

**Comment by jaakla** [comment]
Style is already reduced / optimized, not so needed.
