### ISSUE TITLE
Remove Mapzen online services from SDK

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#165]
Remove online routing and geocoding accessing mapzen as backend.

**Comment by jaakla** [comment]
> CartoOnlineTileDataSource (MapZen-specific zoom level configuration)

Where is this exactly?

**Comment by mtehver** [comment]
About CartoOnlineTileDataSource: initial 'maxzoom' value is set to 17 for MapZen sources (https://github.com/CartoDB/mobile-sdk/blob/master/all/native/datasources/CartoOnlineTileDataSource.cpp). This will be overridden with the value from tiles.json (if present). I think the MapZen case can be simply removed from the code, 'tilezen' schema never worked too well for us, anyway.
