### ISSUE TITLE
Doc: Add CARTO integration guide

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#17]
- [x] General intro (like in blog?)
- [x] Loading viz.json
- [x] Using Maps API
- [x] Using SQL API

**Comment by Nikituh** [comment]
@jaakla Kuidas tundub?

**Comment by Nikituh** [comment]
@jaakla 

Updates:

- links to real api
- vector sample for map api
- vis section
    - “experimental” warning
- sql, maps first, vis later
