### ISSUE TITLE
Generate html doc for Swift iOS API

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#171]
Doxygen does not support Swift AFAIK, see https://medium.com/google-developers/how-to-generate-fabulous-api-reference-docs-for-ios-5bd297b9697d . @Nikituh can you take a look?

**Comment by Nikituh** [comment]
It does look like it still isn't possible, and I can't say I don't understand the reasoning. Doxygen is rather outdated, today there are better tools for generating documentation.

cf. moving from Doxygen to Jazzy: https://medium.com/google-developers/how-to-migrate-ios-api-reference-from-doxygen-to-jazzy-35bd89c6a92b

I'm not entirely sure how it interacts with Javadoc, though.

**Comment by mtehver** [comment]
SDK now has a new 'generate-jazzy.sh' script under 'scripts' folder. The script needs an updated SWIG to work (cartodb/mobile-swig repo).
