### ISSUE TITLE
[PROJECT] Mobile SDK 4.1.2 release

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#172]
- [x] rm mapzen (online geocode - replace with mapbox, online routing - replace with own service), 
- [x] update styles #166 
- [x] Swift html doc #171

**Comment by jaakla** [comment]
All different release packages are released now, just some tests and updates of samples: remove mapzen, increase version numbers.

**Comment by danicarrion** [comment]
@jaakla what's the status? is 4.1.2 live? can we close this?

**Comment by jaakla** [comment]
Done and live. Docs to be updated, but that’s different project
