### ISSUE TITLE
slow rendering on zoomed "big" polygons

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#178]
It seems that there is a slow rendering issue when you are zoomed on polygon.
It happens when you start to have offscreen parts of the polygons.

One way to see the issue is to render mapbox terrain source with hillshading.
I can post a style for mapbox terrain source if necessary.

**Comment by mtehver** [comment]
The 4.1.2RC2 release has additional optimizations that may help here. This version includes more fine-grained rejection of the geometry.

**Comment by farfromrefug** [comment]
@mtehver will need to run more tests but it s already a lot better. I am not even sure i see hick-ups anymore. THanks
