### ISSUE TITLE
iOS SDK as Dynamic Library

### ISSUE THREAD

**Issue by Nikituh** [CartoDB/mobile-sdk#180]
## Proposal

iOS SDK should be built as a dynamic shared library.

Overview of dynamic libraries: https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/OverviewOfDynamicLibraries.html

Other than the benefits stated in the article above, we can then offer NativeScript plugin support. The binary might get slightly larger, but shouldn't be a major issue. Shared libraries are are supported as of iOS 8, but I don't think that will be much of a problem either

**Comment by jaakla** [comment]
@mtehver is it something what requires our swig to support? If so, don't see it very realistic :(

**Comment by mtehver** [comment]
@jaakla No, I do not think that it requires any major changes. Hopefully this involves only a few xcode building parameters. But things rarely are as simple, unfortunately.

**Comment by Nikituh** [comment]
Reference to original issue: https://github.com/CartoDB/mobile-sdk/issues/175

**Comment by mtehver** [comment]
This is now implemented in the master branch: in order to build SDK as shared framework, **--shared-framework** command-line option should be used with **build-ios.py** script

**Comment by jaakla** [comment]
Separate job to be added to Jenkins - creates zip file with -dynamic.zip extension, uploads to S3.

**Comment by jaakla** [comment]
to be tested for #210 , but scheduled as primary build for 4.2.0

**Comment by mtehver** [comment]
@jaakla Are you sure the framework folder structure remained the same? I can not access the dev build currently but I double checked my local dynamic shared library build and it works as expected.

**Comment by farfromrefug** [comment]
@jaakla @mtehver what's the status on that?
I just used the Pod to install 4.1.3 and it seems it is not yet in?
