### ISSUE TITLE
[FR] insert layer below carto style layer

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#185]
I don't know if this could be possible, but it would be immensly useful!
That way you could choose to have a raster overlay layer to show below labels.

Mapbox can do this 
https://www.mapbox.com/ios-sdk/examples/runtime-toggle-layer/

Maybe it can help...
Thanks

**Comment by jaakla** [comment]
With our SDK you have full control over layer order, the layers are added in the order you define, and you can also insert layers in-between others by specifying order. In fact, we don't add any layers automatically, so you need to add also "carto style layer" explicitly in app code. Or do you need something different here ?

**Comment by farfromrefug** [comment]
@jaakla yes i get that. Actually i was more thinking about the way a "carto style layer" is created.
If you look at the mapbox examples, it's like adding contour in between "layers" in the "carto style layer"

**Comment by jaakla** [comment]
Ok, that's clear now. Right now you can set label rendering order, so it is always on top, even of other layers with: `vectorTileLayer.setLabelRenderOrder(VectorTileRenderOrder.VECTOR_TILE_RENDER_ORDER_LAST);` This may resolve issue of having raster overlay layer below labels, which is probably the most common case.

**Comment by farfromrefug** [comment]
@jaakla that's awesome!
That enough for now.
There might be other case where you would want for example to put contour lines under water layer or such.
Do you want to keep this issue open?

**Comment by farfromrefug** [comment]
Actually thinking about it. Crazy idea: could we have a method for vectorLayer to set zordering of a layer like label, water, ....

This would mean having zordering of layers. But seeing ```setLabelRenderOrder``` you might already have it?

**Comment by mtehver** [comment]
I think the use cases for custom z-ordering are limited, though certainly exist. The option to render labels on top of everything handles the most important case.

**Comment by farfromrefug** [comment]
@mtehver Well actually when you use raster overlay (which is something quite common now), this becomes quite important.
Maybe it s only me but for example i would love to be able to put "raster slopes" or "raster hillshades" beneath contour lines. This is where it supposed to be.
And as i also want to put contour lines beneath roads, and as coutour lines come as a separated source, there is no way to do that right now.

**Comment by farfromrefug** [comment]
@mtehver Just stumble upon another issue that makes this request quite important.
I need a source with carto.streets and mapbox contour lines. The thing is for it to render correctly i need contour lines beneath carto.streets roads.
Until now i was doing it with a ```MergeTileDataSource``` and ```loadTile``` like this
```java
@Override
    public TileData loadTile(MapTile tile) {
//        return firstSource.loadTile(tile);
        TileData result = null;
//        int zoom = tile.getZoom();
        for(int i = 0; i< sourcesCount; i++) {
            TileDataSource source = sources[i];
//           if (zoom <= source.getMaxZoom() && zoom >= source.getMinZoom()) {
               TileData sourceResult = source.loadTile(tile);
               if (result == null) {
                   result = sourceResult;
               } else if (sourceResult != null && !result.isReplaceWithParent()){
                   byte[] data1 = result.getData().getData();
                   byte[] data2 = sourceResult.getData().getData();
                   ByteBuffer bb = ByteBuffer.allocate(data1.length + data2.length);
                   bb.put(data1);
                   bb.put(data2);
                   result = new TileData(new BinaryData(bb.array()));
               }
//           }
            
        }
        return result;
    }
```
I just realized that i have a big issue at zoom > 14.
carto.streets max zoom is 14 but TileLayer still render at zooms >14 using the same data.
The issue is that mapbox terrain data exists past 14. So using my MergeTileDataSource i loose carto.streets data on zoom > 14. And i dont see any easy solution for this except having 2 separate layers.
Any idea?

**Comment by farfromrefug** [comment]
Found out that this must be where ```isReplaceWithParent``` is important!
Think i can close that issue. Need to fix MergeTileDataSource
