### ISSUE TITLE
Need a sample for EPSG:900913 in Swift 4

### ISSUE THREAD

**Issue by LakshmanaSwamy** [CartoDB/mobile-sdk#187]
Please provide the sample for  draw a line or a Point on CartoMap, based on the response we need to show on a map . If it is a point we need to show a point on Map. if it is a LineString draw line between points. 
Response getting from server :
{
    geometry =     {
        digiLength = "27.3021";
        featureGeom =         {
            crs =             {
                properties =                 {
                    name = "EPSG:900913";
                };
                type = name;
            };
            geometry =             {
                coordinates =                 (
                                        (
                        "10030.5",
                        6754567
                    ),
                                        (
                        "10069.8",
                        "6754586.9"
                    )
                );
                type = LineString;
            };
            id = 735940;
            properties =             {
            };
            type = Feature;
        };
        lod16BboxIntMaxX = 32784;
        lod16BboxIntMaxY = 21722;
        lod16BboxIntMinX = 32784;
        lod16BboxIntMinY = 21722;
    };
}

**Comment by mtehver** [comment]
Sorry, but Carto Mobile SDK 4.x does not support any other projections besides EPSG3857.

We have left our API open for other projections but currently do not plan to do this due to very limited commercial interest.

**Comment by jaakla** [comment]
Note that you can convert the point coordinates to WGS84 in your app (see many algorithms for that here: https://wiki.openstreetmap.org/wiki/Mercator) and add then them to the map using standard methods:
```
        let longitude = -77.0369
        let latitude = 38.9072
        let markerBuilder = NTMarkerStyleBuilder()
        markerBuilder?.setColor(Colors.appleBlue.toNTColor())
        markerBuilder?.setSize(15)
        position = projection?.fromWgs84(NTMapPos(x: longitude, y: latitude))
        let marker = NTMarker(pos: position, style: markerBuilder?.buildStyle())
        source?.add(marker)

```
