### ISSUE TITLE
On Android, Text vectors containing line breaks are not properly rendered

### ISSUE THREAD

**Issue by Shtong** [CartoDB/mobile-sdk#197]
When a `Text` vector element displays a string that contains line breaks, the android bitmap renderer seems to incorrectly compute its size and truncates the text with an ellipsis (...).

The problem can easily be reproduced. For example (in a Xamarin/C# android application):

```cs
protected override void OnCreate(Bundle savedInstanceState)
{
    base.OnCreate(savedInstanceState);

    // Register license
    MapView.RegisterLicense(LICENSE, ApplicationContext);

    // Set our view from the "main" layout resource
    SetContentView(Resource.Layout.Main);
    MapView map = FindViewById<MapView>(Resource.Id.mapView);

    MapPos textPos = new MapPos(0, 0);

    // Vector layer with text
    LocalVectorDataSource vectorSource = new LocalVectorDataSource(map.Options.BaseProjection);
    TextStyleBuilder textStyleBuilder = new TextStyleBuilder
    {
        // Default settings
    };
    vectorSource.Add(new Text(textPos,
                                textStyleBuilder.BuildStyle(),
                                "This is a large text with a number\nof line breaks that has to be\ndisplayed properly on the map!"));
    VectorLayer textLayer = new VectorLayer(vectorSource);
    map.Layers.Add(textLayer);

    map.FocusPos = textPos;
}
```

**Comment by mtehver** [comment]
Thanks for reporting this. For some reason (do not remember why) Texts in the SDK are not split at linefeeds. To keep the backward compatibility, I left the default behaviour as it is, but added  'BreakLines' property to TextStyleBuilder. So you should set BreakLines to true and the sample will work. We will ship this in the next release (4.1.3 or 4.2).

**Comment by Shtong** [comment]
Cool, thanks. Do you have an approximate release period for the next version by any chance ?

**Comment by mtehver** [comment]
A very rough estimate would be 1 month from now (end of April or beginning of May). We have couple of features we want to finish first and making releases is quite time consuming, so it will take some time.

**Comment by jaakla** [comment]
@Nikituh - sample/demo to be added to Overlay sample

**Comment by mtehver** [comment]
@Shtong We have now a 4.1.3RC1 release that includes the change.

**Comment by Shtong** [comment]
I just made a test, which worked as expected.

I'll just drop a small suggestion : have a text align setting. It was not needed with only one line, but with several lines maybe users will want to have shorter lines aligned on the center or right of the text area. Other than that, it looks good.
