### ISSUE TITLE
[FR] hd enabled raster layers

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#198]
Right now if raster layer user 256px tiles, it gets very blurry and not really nice on hdpi devices (most devices).

There is a way to actually draw 512px tiles with 256px sources.
If a tile is requested, you can request the 4 tiles at the upper zoom and create a "merged" bitmap.

It would be amazing to have that in Carto. Like a boolean for the layer which actually draws it in HD if tiles are not HD.
I already have that implemented with googlemap on iOS and Android. I can send the code here. But i guess in Carto it would have to be written in C++
I would like to make a PR, but i cant get my carto mobile env to work :s (will work on that).

**Comment by jaakla** [comment]
You can write custom data sources in app level, AdvancedMap has sample "Custom Raster Data Source" which does raster manipulation (loads 2 tiles from different URLs/sources and overlaps them), and with same principle you can do same with 4 tile tile loading and merging. I'm not sure if that's the best option here really, our basemaps have also 512pix tiles which can be used on normal rasterlayer and this should resolve high dpi issue.

**Comment by mtehver** [comment]
As Jaak already answered, most modern tile providers also support 'retina tiles' with 512x512 resolution. So this is definitely the preferred option and this will work out of box. For other use cases a custom app-specific data source is the way-to-go. Anyway, downloading 4x the number of tiles will likely give pretty bad UX due to the latency/amount of HTTP requests. Thus I am closing this.

**Comment by farfromrefug** [comment]
@mtehver @jaakla i understand your point. But today still some very important raster tile providers (like IGN in France) still provide tiles in 256px. That's why i need to do this. I could also mention most osm free raster sources like openstreetmap still give 256x256 tiles. Some are upgrading like thunderforest which provides @2x tiles.

Now i agree i can do that with custom data source and i will. Making it inside the sdk would have made it work also with mbtiles i think. But i will try to do it there too.
Thanks

**Comment by mtehver** [comment]
If you build it as a virtual datasource (that queries another datasource 4x for each tile), then I think you can reuse your class both for online and offline cases.

**Comment by farfromrefug** [comment]
@mtehver will look into this. Thanks!
