### ISSUE TITLE
Invalid NuGet link in the docs

### ISSUE THREAD

**Issue by Shtong** [CartoDB/mobile-sdk#201]
In the Xamarin Android *Getting Started* section (https://carto.com/docs/carto-engine/mobile-sdk/getting-started/#xamarin-android-app), the link to the NuGet package that should be installed goes to a deprecated package (CartoMobileSDK instead of CartoMobileSDK.Android)

**Comment by mtehver** [comment]
Thanks for reporting this. We are in process of updating the documentation, so the guides will change quite a bit. Meanwhile, I have fixed the link in the old documentation, though not sure when/if this will be public.
