### ISSUE TITLE
Use GET instead of POST to init maps

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#203]
Needed to allow server-side caching. 

@danicarrion @jsanz

**Comment by mtehver** [comment]
Master branch includes the performance fix and this will be in 4.1.3 release. 

Just a small whining: though the change may improve performance, using JSONP for any other platform besides Web is an ugly hack: we need to extract the JSON from the JSONP by assuming a certain output format, as we can not simply execute Javascript.

**Comment by jsanz** [comment]
just to confirm, sorry to bother

@dgaubert the only way to make a `GET` request to the Maps API to instantiate a named map is using the JSONP endpoint?

**Comment by dgaubert** [comment]
No, it isn't. We also support the GET method for anonymous maps but the body content should be sent as `config` query-param. For instance: `curl -X GET "dgaubert.carto.com/api/v1/map?config='{layers: [...]}'"`

In case of instantiating a named map you have to use either `jsonp` or `POST` method.

**Comment by mtehver** [comment]
As the SDK needs to support both named and anonymous maps, this means that JSONP parsing hack is still needed (for named maps).

**Comment by jaakla** [comment]
@dgaubert and @jsanz : Just to confirm another detail here: specific customer's "named map" is actually a builder-generated map, where the map name is 'hacked' from the URL (added tpl_ etc there). This works fine, and I don't know better solution, but is it also in longer term safe and supported solution, suitable for production use?

**Comment by jsanz** [comment]
not sure to understand your question @jaakla, you mean you are instantiating the map on the SDK from a BUILDER embed url?

When I need to get the named map template that backs a map, yeah, the only method I know about is looking at the url for the `tpl_{namedmap_id}`, even I guess CARTO ENGINE internal API for visualizations should also give a path to get the template for example from a visualization name.

**Comment by jaakla** [comment]
Yes, the map is done with Builder. I'm a bit worried just because this is not a public official API.

**Comment by jsanz** [comment]
I'm afraid that's the best we have at this moment :sweat:

**Comment by jaakla** [comment]
tested with next release: #210

**Comment by jaakla** [comment]
Updated Android SDK (build 470) traffic seems nice: to create named map GET is used, and the subsequent tiles are cache HIT as expected:
![screenshot 2018-04-16 14 28 10](https://user-images.githubusercontent.com/5609650/38806602-6cc04562-4182-11e8-889f-3cef79f19747.png)
