### ISSUE TITLE
3x VectorLayer deadlock

### ISSUE THREAD

**Issue by Nikituh** [CartoDB/mobile-sdk#208]
#### How it happened:

Our current routing sample uses two different layers:

1. `routeLayer` for lines and intructions
2. `startStopLayer` for start and stop markers.

When implementing transparent route, I had to create to create a `routeInstructionLayer` in order to keep the instructions full opacity. 

#### How do I know it's to do with VectorLayers?

Unable to reproduce if I comment out one of layer _addings_:
* `//        mapView.layers.add(routeInstructionLayer)`

#### Steps to reproduce:

1. Run dev branch of mobile-android-samples: https://github.com/CartoDB/mobile-android-samples/tree/dev
2. Open offline routing sample and set markers to calculate a route
3. On that route, zoom in and out
4. Should freeze after a few seconds

#### How do I know it's a new issue?

Easily reproducible with local library:
* `implementation(name:'carto-mobile-sdk-4.1.2.466', ext:'aar')`

Cannot reproduce with release version:
* `implementation 'com.carto:carto-mobile-sdk:4.1.2@aar'`

**Comment by mtehver** [comment]
Good spotting! This is regression in post 4.1.2 code related to layer opacity feature. Fixed now in master branch.
