### ISSUE TITLE
package encryption keys do not match, failed to create/open package manager database

### ISSUE THREAD

**Issue by nuynait** [CartoDB/mobile-sdk#211]
I am using Carto package manager on iOS for offline street map cache. It works perfectly until I upgrade app's core data database. 

I don't think upgrade my app's core data database should affect anything with `NTCartoPackageManager` because it is not using my app's core data model.

Here is the error log:
```
PackageManager: Error while constructing PackageManager: Package encryption keys do not match, trying to remove

<Error>: PackageManager: Error while constructing PackageManager: Package encryption keys do not match, trying to remove

*** Terminating app due to uncaught exception 'IOException', reason: 'Failed to create/open package manager database'
*** First throw call stack:
(0x186476364 0x1856bc528 0x18647602c 0x105d66b10 0x105d66818 0x105d66ec4 0x105ca0af0 0x105c9f860 0x105c9f3e4 0x105cab18c 0x105cb15e8 0x105c9c5b0 0x105c96338 0x105c95ae0 0x105c95b20 0x18fa2cae8 0x18fa2c6c0 0x10475a134 0x1047581ec 0x104751918 0x104751950 0x18fa2cae8 0x18fa2c6c0 0x1048741fc 0x104870bc0 0x10486cacc 0x10486cd64 0x18fa2cae8 0x18fad3f70 0x18fad3410 0x18fad2e14 0x18fad2890 0x18fad2790 0x18fa29f00 0x18a4b9998 0x18a4bdb20 0x18a42a36c 0x18a451b90 0x18fca5c00 0x18641e790 0x18641e060 0x18641bd70 0x18633be58 0x1881e8f84 0x18fa9067c 0x10499d274 0x185e5856c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Here is how I init the `NTCartoPackageManager`

``` swift
packageManager = NTCartoPackageManager(source: "carto.streets", dataFolder: dirURL.path)
```

dirURL.path is already created at this point.

If I delete the app and install the new version, it is good. **BUT if I upgrade from the old version then this problem exists.**

Any help appreciates.

**Comment by nuynait** [comment]
I didn't upgrade temporary solved the problem by using a new dataFolder.

**Comment by nuynait** [comment]
I have a map sdk, which include the carto, and that's where `NTCartoPackageManager` locates. Seems like when I change something and recompiles map sdk, that problem might occur and I have to change to a new dataFolder

**Comment by mtehver** [comment]
@nuynait When you used SDK 4.0.1, which package source did you use? nutiteq.osm perhaps? Note that you can not simply change the source and keep your old packages. This is the likely reason for the error.

If you want to keep using nutiteq.osm as your source and upgrade to 4.1.x SDK, there is a caveat: SDK 4.1.x does not include built-in style (like nutibright) compatible with nutiteq.osm source. The built-in styles are only available for carto.streets source. So you have to extract old styles from the SDK repo and embed them into your project.

Thus if possible, I would suggest simply dropping old packages and redownloading the packages from carto.streets source.

**Comment by nuynait** [comment]
@mtehver Thanks for letting me know. When having that problem, I actually didn't change any source, it was always using `nutiteq.osm`, it is when I had that  `Package encryption keys do not match` issue, I changed to `carto.osm` to see if that is the issue. 

Yes the package issue exists even if I do not change source. I think what I will do right now is to test upgrade app every time when I release a new version. If any package encryption key issue happens I will change to a new folder name for now.

Thanks so much for all the information. Really appreciate. I will close this issue for now since it is not obvious why having this issue and I am not using the latest carto library. I will reopen if updated in future and found issue still exists.
