### ISSUE TITLE
WktGeometryWriter incorrectly encodes numbers

### ISSUE THREAD

**Issue by Shtong** [CartoDB/mobile-sdk#216]
We are having a problem, reproduced in a Xamarin app on the UWP and Android platforms. When we want to generate a WKT text from a geometry using the `WKTGeometryWriter` class, the resulting WKT contains coordinates that are written using exponential notation (`6.142e05`) insteand of standard floating point (`614235.422476`).

The bug was encountered on version 4.1.2 of the API.

Sample code to reproduce the problem:
```cs
PointGeometry point = new PointGeometry(new MapPos(614235.422476, 5356009.567610));

WKTGeometryWriter writer = new WKTGeometryWriter();
string result = writer.WriteGeometry(point);

Log.Info(result);
// Expected: POINT(614235.422476 5356009.567610)
// Actual: POINT(6.142e05 5.356e06)
```

**Comment by jaakla** [comment]
for #218

**Comment by mtehver** [comment]
Thanks for reporting this, SDK 4.1.3 release will include the fix.
