### ISSUE TITLE
Use URLconnection for iOS

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#217]
Advantages:
* automatic proxy usage
* HTTPS2 support

Requires HTTPS for all backends.
* internal endpoints
* review tilejson-s - indirect endpoints: https://github.com/CartoDB/lbs-services/issues/29

Review performance. Does it use HTTP/2 ?

**Comment by mtehver** [comment]
Implemented, SDK 4.2 uses `URLSession` API on iOS.
