### ISSUE TITLE
Support custom URLs for backend

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#221]
Useful for on-premises, custom and staging backends.
* Packagemanager
* Map/tilejson
* online routing
* online geocoding

**Comment by mtehver** [comment]
This is now implemented. Some notes:

* For `CartoOnlineTileDataSource`, the source can be URL to custom tiles.json
* For `CartoPackageManager` the source can be URL to custom packages.json for country packages. For bbox based packages, the source should be an URL template with '{tilemask}' tag
* For `CartoOnlineRoutingService` the source can be an URL to OSRM-compatible 'viaroute' service
* There is no `CartoOnlineGeocodingService` with source id right now

**Comment by jaakla** [comment]
@Nikituh please test with staging backend server URL and share in advancedmap develop branch

**Comment by Nikituh** [comment]
Newest builds instantly crash:

```
Jun  4 11:54:55  AdvancedMap.Swift[840] <Info>: BaseMapView::onSurfaceCreated()
AdvancedMap.Swift(840,0x16c5e7000) malloc: *** mach_vm_map(size=1610612736) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc
```

The app crashes on startup, in the gallery view, without even rendering a map.

Build #498 is fine, 499# is broken. The only commit between them is: https://github.com/CartoDB/mobile-sdk/commit/ec418c05d64cc5b43e86d49484642d60e7382ad8

**Comment by mtehver** [comment]
Closing this, this was implemented in 4.1.4.

**Comment by farfromrefug** [comment]
@mtehver i want to implement my custom PackageManager to download offline map packages.
Can you guide me on how to make it work. 
I have the example JSON from your server [here](https://api.nutiteq.com/mappackages/v2/carto.streets/2/packages.json) but i am not sure how to build it for me. I dont need encryption key. 
Thanks

**Comment by mtehver** [comment]
@farfromrefug You should be able to use `PackageManager` class directly, by using empty strings as encryption keys. 

I have just published a repository containing scripts required for building offline packages:
https://github.com/nutiteq/mobile-sdk-scripts

**Comment by farfromrefug** [comment]
@mtehver that s pretty awesome. So this supposes you have a mbtiles for the whole planet?
Like one generated by OpenMapTiles. Cause now i generate my own OpenMapTiles mbtiles (for france only right now).

So let me guess if i am correct:
* i could modifiy the repo structure to only use "france" as a country
* i could then pass to the build_map_packages my own build mbtiles? It will be splitted right by regions right?
* for the route/geocoding i could then pass the pbf file of France only

Thank a lot for that sharing, it is pretty awesome!

**Comment by mtehver** [comment]
@farfromrefug Yes, that's correct.

For map packages the input is a 'master' mbtiles file that has to contain all the tiles needed by the packages. If you just want to make packages for France, then only a small subset of the planet.mbtiles is actually required. 

For routing and geocoding packages a corresponding .osm.pbf file is required (you can get one for France from Geofabrik, for example). 

And to make packages for just France, use the 'packages-carto.json.template' file from the repo and simply keep the France packages, delete everything else.

**Comment by farfromrefug** [comment]
OK though as I generate my own mbtiles it can only be France for now. Really to long to do the world on my machine ;). Will try your script with my mbtiles. Maybe tweak your script to work with it. 
BTw the script for offline is there to split the mbtiles right ? I wonder if there already existing tools somewhere which would do this faster using SQL requests. 
Thanks again!

**Comment by farfromrefug** [comment]
Found this https://github.com/mapbox/mbtiles-extracts

**Comment by mtehver** [comment]
@farfromrefug The splitting script does a bit more than just copying tiles. It cleans up 'empty' tiles and tiles filled with a single polygon. And it prunes unnecessary subtiles. But for dense areas none of these steps are essential and simply copying tiles should work fine.

**Comment by farfromrefug** [comment]
@mtehver thanks for the explanation. Will look a little bit deeper at the script.
