### ISSUE TITLE
Make build scripts more dev-friendly

### ISSUE THREAD

**Issue by mtehver** [CartoDB/mobile-sdk#222]
Issues with the current scripts:

- [x] Build scripts do not check that the required tools/utilities exists, resulting in cryptic failure messages
- [x] Some utilitities (corflags) are not even exposed via command-line options
- [x] The default paths should be more flexible and more up-to-date with current tools versions

**Comment by farfromrefug** [comment]
Can't wait for that to start creating PRs. Can't get it to compile on mac right now.

**Comment by mtehver** [comment]
Closing this. Build scripts could be more user-friendly, but the current state should work with latest tools.
