### ISSUE TITLE
[ANDROID] cant open mbtiles 

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#223]
On android i try to open a mbtiles i created like that:
```
new MBTilesTileDataSource(sPath);
```
But i always get : 
```
05-19 16:35:04.606: E/TileSourceProxy(28756): (AsyncTask #3) [174,320] Could not load file file:///android_asset/Resources/storage/emulated/0/Android/data/akylas.alpi.maps/files/mbtiles/73947ed3-c698-5988-d081-7f61767021df.mbtiles
```
whatever location i try to open the file from (tried app data and external sd card)

- the file exists
- i know i can open it with ```SQLiteDatabase.openDatabase()```
- my app have storage permissions 

Any idea on how to solve this?

Thanks

**Comment by Nikituh** [comment]
There can be several reasons for this. Any chance you could provide sample code of your application? 

Either way:

* You should provide the minimum and maximum zoom range with in your MBTilesTileDataSource constructor
* You should copy the asset to your SD-card

Have you checked out our sample code?
* https://github.com/CartoDB/mobile-android-samples/blob/9ab5980b8f407dcd86c108b0c0df9e68151aba9b/AdvancedMapAndroid/app/src/main/java/com/carto/advancedmap/sections/offlinemap/BundledMapActivity.java

**Comment by farfromrefug** [comment]
@Nikituh i found the reason, sqlite does not like the file://. I removed it before giving it to MBTilesTileDataSource and now it works!

Thanks for you support
