### ISSUE TITLE
Create a BalloonPopup with buttons

### ISSUE THREAD

**Issue by carlos-mg89** [CartoDB/mobile-sdk#224]
A few days ago I posted a question in gis.stackexchange.com and I thought you might be able to provide some assistance with this issue I have: https://gis.stackexchange.com/questions/283234/create-a-balloonpopup-with-two-buttons

Basically, I would like to add a button (ideally two buttons) in a BalloonPopup, so I can perform two actions related to the clicked place.

I can obviously find a different way of doing this, like showing a fragment (I'm developing in Android) with a Layout and the two buttons over there. However, this won't look as great as it would with a BalloonPopup that has two buttons inside.

I've tried to understand how the class BalloonPopup works, but haven't found a way of doing this. Can you think of any possible way to achieve this through modifying this class or creating a new one¿?

Perhaps there is some other class that serves to this purpose or a very similar approach. However, I haven't been able to read about it, either in gis.stackexchange.com , in the docs of carto.com or in this repository.

Thank you in advance

**Comment by carlos-mg89** [comment]
Any possibility this could go any further? It doesn't have to be anything fancy, I only need a way of making a couple of buttons with text to work inside of the BalloonPopup or a similar entity that could be put in place over the map.

**Comment by mtehver** [comment]
The request makes a lot of sense, though it is not a trivial change. I will schedule this for 4.2 release. Which will not be out any time soon, though.

**Comment by carlos-mg89** [comment]
Thanks a lot for including that requirement! It'll improve the UX of my app (I ended up opting for a BottomSheetDialog fragment, which does the work nicely, but not as fancy as I would have loved).

Would keep an eye on this then :)

**Comment by carlos-mg89** [comment]
This has been included in the latest RC, right? Do you have any documentation about it?

**Comment by mtehver** [comment]
@carlos-mg89 Only API docs, which are currently not displayed in Android Studio. But the API is really straightforward, the relevant classes are: `BalloonPopupButtonStyleBuilder`, `BalloonPopupButtonStyle`, `BalloonPopupButton` and `BalloonPopupEventListener`. You can add/replace/remove the buttons from `BalloonPopup` using `addButton`, `replaceButton`, `removeButton` methods.

**Comment by mtehver** [comment]
Closing this, as SDK 4.2 is released.
