### ISSUE TITLE
MBTiles and CartoCSS style

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#225]
Hello,

I have a issue on mobile sdk when using mbtiles with CartoCSS style, but it can not render property as "text-name, text-face-name, ...". I just want to show label of polygon, line or point. So, how to resolve this issue, please help me.

Many thanks,

**Comment by jaakla** [comment]
For developer questions it is better to post to StackOverflow with tag carto-mobile. Please add also your code sample, how exactly do you try to create the layer and what exactly is in your style.
