### ISSUE TITLE
Issue in NTMapPos for iPhone X

### ISSUE THREAD

**Issue by k-varma** [CartoDB/mobile-sdk#228]
CartoMobileSDK (4.1.2)
Swift 4 

In Our project we are taking the NTMapPos at the Zoom Level of 25meters, When using iPhone X we are sending the mapview and by using the below code we are getting the values, But When converting the NTMapPos to coordinates and tried to plot on Google maps, the topRight, bottomRight, bottomLeft points do not match what we see in Carto map in Phone and Google maps. 

Do we need to send any Zoom value or others?
 

>    func getBoundingBoxInMapPos(mapView:NTMapView)->[NTMapPos]{
> 
>         let width: Float = Float(mapView.frame.width)
>         let height: Float = Float(mapView.frame.height)
> 
>         
>         let topLeft :NTMapPos = mapView.screen(toMap: NTScreenPos.init(x: 0, y: 0))
>         let topRight :NTMapPos = mapView.screen(toMap: NTScreenPos.init(x: width, y: 0))
>         let bottomRight :NTMapPos = mapView.screen(toMap: NTScreenPos.init(x: width, y: height))
>         let bottomLeft :NTMapPos = mapView.screen(toMap: NTScreenPos.init(x: 0, y: height))
>         return [topLeft,topRight,bottomRight,bottomLeft,topLeft]
>     }

**Comment by jaakla** [comment]
What numbers do you exactly get? you should get internal coordinates, which needs to be converted to Wgs84 to get latitude and longitude what Google Maps expects. Something like:
```
let projection = mapView.getOptions().getBaseProjection()
let topLeftWgs = projection.toWgs84(topLeft)!
let topRight Wgs = projection.toWgs84(topRight)!
...
```

**Comment by k-varma** [comment]
@jaakla 

The coordinates i am getting is 
topLeft   [52333.5533661467,6752706.87406307]
topRight [52539.1839352835,6752706.87406307]
bottomRight  [52539.1839352835,6752364.46108686]
bottomleft [52333.5533661467,6752364.46108686]

Later we are converting these points using a website and tried to Plot on the Google maps, 
Below is the URL where we transform the topRight points 

https://epsg.io/transform#s_srs=3857&t_srs=4326&x=52539.1839353&y=6752706.8740631

I am attaching the screen shot of in which location we get the points and On the map where it is Plotted. 

If you see it The black lines on the image The topLeft spotted the Black line but it is plotted much before the Black line. 

If you have doubt in location you can see a street name "Legg Street" in phone and google maps. 


Can you please help me of it. 
![question](https://user-images.githubusercontent.com/29655870/41752382-cdddcd06-75e4-11e8-9eec-164af50275a4.png)

**Comment by jaakla** [comment]
From where do you get that 52333.5533661467,6752706.87406307 is in EPSG3857, is it in documentation somewhere? If it is, then this is not correct, these are internal coordinates which are not defined in any specific projection, actually in different SDK versions they may be different. 

You should always use SDK's EPSG3857 class (you can get it from mapView as `options.baseProjection` class, or just create new class) and method `projection.toWgs84(MapPos)` of this to convert the coordinates to the 4326 coordinates which are good for Google maps and any other tools. Same way, if you have your data in lat/long then you shoudl use fromWgs84() method of the projection to convert them.

**Comment by k-varma** [comment]
I got the Points from below code.

In the docs we have option for getting the screen positions, So the ScreenPostion cant give the exact postions?
   
```
    let width: Float = Float(mapView.frame.width)
    let height: Float = Float(mapView.frame.height)

    let topRight :NTMapPos = mapView.screen(toMap: NTScreenPos.init(x: width, y: 0))
    
```

**Comment by jaakla** [comment]
The problem is that you do some conversions from internal coordinates to WGS84 (lat/long) outside SDK, assuming they are in some projection, you should never do this. You should convert coordinates inside SDK to Wgs84, and then use these values.
