### ISSUE TITLE
more debug in css parsing

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#229]
Hi,

I am facing those errors in my logcat:
```
06-16 18:49:54.841: E/carto-mobile-sdk(6001): MBVectorTileDecoder: Could not parse to the end of string expression, error at position 15
06-16 18:49:54.842: E/carto-mobile-sdk(6001): MBVectorTileDecoder: Unsupported text expression type
```
But i have no idea where the error is in my mss file.
Could you add better logs to pinpoint the error?

Thanks

**Comment by mtehver** [comment]
Thanks for reporting this. The error message is really cryptic and I will improve this. The reason was mostly likely related to the contents of your 'text-name' or 'shield-name' parameters, perhaps you had mismatching [] or {} tags.

**Comment by farfromrefug** [comment]
@mtehver will look at it thanks.

**Comment by farfromrefug** [comment]
i can confirm it works perfectly now
