### ISSUE TITLE
[FR] export TileUtils

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#231]
Would be really useful to have access to TileUtils methods in the Android and iOS sdks.
I am needing it to interact with a source without a layer

Thanks

**Comment by mtehver** [comment]
Thanks for the feedback. The class is relatively high level and I think exposing it can be quite useful. We will try to add this to the next release.

**Comment by farfromrefug** [comment]
@mtehver great ! will be awesome to have
 Thanks
