### ISSUE TITLE
Building for PRs

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#246]
I am about to start making PRs. Especially i want to add more native Sources.
I am currently using them in Java but i think the JNI bridge is the reason why i am seeing hickups.

I am building  correctly on android. I just have a question. Is there a way to have carto packager and sources working? Right now i end up with the no appToken [here](https://github.com/CartoDB/mobile-sdk/blob/0a9c83513b265a7c6950377b28f2c6f5f07afb47/all/native/components/LicenseManager.cpp#L19)

Thanks

**Comment by jaakla** [comment]
I'm afraid you can't. PackageManager and CARTO tile services are commercial backend services, and the license key system with encrypted tokens is meant to keep secured control for the access. So the idea is that if you use SDK as open source, then you are expected to connect to own backend services, not CARTO ones.

**Comment by farfromrefug** [comment]
@jaakla i understand.  Will try to test my PRs without carto (i think i might be able to use mapbox)

How do you test while developing. Do you have a setup for an android app to rely on the realtime built sdk? Even maybe a gradle that rely on the build?
Any guide?

**Comment by mtehver** [comment]
During development we do most testing on iOS/ObjC as both app and SDK code are native and debugging is more seamless. We usually test Android as a secondary platform once the implementation is mostly finished. We have some automatic tests and stuff but these are private ATM.

**Comment by farfromrefug** [comment]
@mtehver thanks for the info. Will try to have it run on iOS
