### ISSUE TITLE
Marker on Tap

### ISSUE THREAD

**Issue by KrishNaveen** [CartoDB/mobile-sdk#250]
Wants to give user an option to choose location. So that whenever user taps on map wants to show marker over there. Any inbuilt functionalities?

Otherwise how can I convert point into coordinate(Like mkMapView.convert(point, toCoordinateFrom: mkMapView)

**Comment by jaakla** [comment]
Sample code for this: https://carto.com/developers/mobile-sdk/guides/map-view/#listening-to-events
