### ISSUE TITLE
Nearest geometry to a point

### ISSUE THREAD

**Issue by josemazo** [CartoDB/mobile-sdk#258]
Hi!

We were thinking if there is a way within the SDK to calculate the nearest geometry to a point that fits some properties. Our data sources are offline MVTs in MBTiles files.

**Comment by mtehver** [comment]
It really depends on requirements but we may have what you need: take a look at `VectorTileSearchService` class. You can specify a `SearchRequest` with geometry and filter criteria. It is not commonly used and I think we have only one sample in our AdvancedMap project demonstrating this.

**Comment by josemazo** [comment]
Thanks @mtehver we'll try that and let you know the outcome.

**Comment by josemazo** [comment]
Hi @mtehver. It works like a charm! Thank you :D
