### ISSUE TITLE
HTTPTileDataSource: Unable to connect

### ISSUE THREAD

**Issue by 96NekoRS** [CartoDB/mobile-sdk#262]
Can't load tiles with HTTPTileDataSource in Android 9, this works in Android 8.1 and below.
I'm getting the following exception:
`HTTPTileDataSource::loadTile: Exception while loading tile 14/8607/5662: Unable to connect: http://example.com:8080/data/v3/14/8607/5662.pbf`

Also I tried loading the url with a browser on the same phone and network and that works aswell.

**Comment by LordArianz** [comment]
can you share your solution?

**Comment by farfromrefug** [comment]
@LordArianz you need to setup a [security config] [https://developer.android.com/training/articles/security-config]

**Comment by LordArianz** [comment]
I put this, but not working:
`    <base-config cleartextTrafficPermitted="true" />
`

**Comment by farfromrefug** [comment]
use this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
```

**Comment by LordArianz** [comment]
still unable to connect!

**Comment by LordArianz** [comment]
this is my code:
`        String url = "http://mts1.google.com/vt/lyrs=y&x={x}&y={y}&z={zoom}";
        TileDataSource tileDataSource = new HTTPTileDataSource(1, 19, url);
        TileLayer baseLayer = new RasterTileLayer(tileDataSource);
        mapView.getLayers().add(baseLayer);
`

**Comment by farfromrefug** [comment]
You did not forget to add it to you manifest, right? Cause it works for use. Using it in multiple apps.

**Comment by LordArianz** [comment]
no, i did not forget, this is my code in manifest:
`android:networkSecurityConfig="@xml/network_security_config"`

**Comment by Jaymo** [comment]
Tested it on an app that was encountering the same issue and can confirm it works
