### ISSUE TITLE
Offline Custom Data + Offline Geocoding

### ISSUE THREAD

**Issue by lhorus** [CartoDB/mobile-sdk#264]
The [documentation](https://github.com/CartoDB/mobile-sdk/blob/master/doc/custom_offline_data.md), explains how to load offline data, however, the offline geocoder and reverse geocoder's [documentation](https://github.com/CartoDB/mobile-sdk/blob/master/doc/geocoding.md) states that the data is preprocessed, by CartoDB - via Pelias from what I understood. However, and since .mbtiles do - can - contain all the PoI and street information, which they often do, is CartoDB's offline geocoder not able to process said format by default? Is the Pelias format required? This would result in duplicate data, as the map render cannot simply not contain street names and so forth, vectors without street names and so on, aren't of much use to the user.

Sorry if this seems rather rude, just trying to figure this whole thing out!

**Comment by jaakla** [comment]
Pelias as such is based on Elasticsearch database engine, we don't have it on the mobile, so we use own created data structure for geocoding, based on sqlite. Geocoding, routing and map rendering are different tasks and all of them require a lot of specific simplifications, optimizations and indexing, especially if you have global map coverage and mobile devices with limited memory. So even if mapbox vector tiles seem to include similar data as geocoding, then if you go to details, then it is quite useless for fast geocoding. For example it misses relations betweem objects (you have streets, but dont know city where it belongs), objects are cut across tiles, are geometrically simplifed for lower zoom tiles , there is no name-based index at all etc.
I can imagine geocoder on top of vector tiles package, but any geocoding type search would require scanning through all tiles (bigger package can have tens of thousands of them) and a lot of memory to keep the state, so it would be very-very slow. Even reverse-geocoding would be very limited. Actually, if you just need street name as "reverse geocode" then this is possible now with vector tile query, we have API for this also.

**Comment by lhorus** [comment]
Don't take me wrong, the question isn't exactly on a commercial perspective, I am merely curious as I've been wondering how exactly does CartoDB do offline geocoding and reverse geocoding in such a relatively fast and accurate way.

I take it the tools and structure of the generated sqllite database is private?

**Comment by jaakla** [comment]
The format itself: https://github.com/CartoDB/mobile-sdk/wiki/Nutigeodb-format . You can find other format descriptions from wiki also. We don't have public opensource tools to create it to be shared, at least not yet :)

**Comment by lhorus** [comment]
Ah couldn't find that anywhere! Thank you!

Let me know if those tools someday become public ;) cheers mate!

**Comment by mtehver** [comment]
@lhorus We have now published the scripted needed for creating offline map, routing and geocode packages: https://github.com/nutiteq/mobile-sdk-scripts.

Closing this.
