### ISSUE TITLE
`marker-clip:false` not working

### ISSUE THREAD

**Issue by alizeyn** [CartoDB/mobile-sdk#265]
Referencing to the [docs](https://carto.com/developers/styling/cartocss/#marker-clip-boolean) :

> By default, geometries are clipped to map bounds. You can disable line clips to avoid rendering artifacts on a map if are having performance issues.

as you can see on the screen shot, `marker-clip:false` not working.
![device-2019-02-27-181836](https://user-images.githubusercontent.com/19981414/53499157-09411180-3abd-11e9-8ad2-66e0a0fcf44b.png)

**Comment by mtehver** [comment]
`marker-clip` property is currently not implemented. You are using `marker-allow-overlap: false` in your CSS, correct? This implicitly sets clipping to true.

I agree that the current handling is bad and I will add `marker-clip` support to SDK 4.2. The preview version should be out by early next month.

**Comment by mtehver** [comment]
@alizeyn This is now available in SDK 4.2.0-rc.1

**Comment by mtehver** [comment]
Closing this, SDK 4.2.0 is now out.
