### ISSUE TITLE
emuglGLESv2_enc errors after displaying long Line

### ISSUE THREAD

**Issue by carlos-mg89** [CartoDB/mobile-sdk#267]
First of all, thanks for the great work you do with this project. I already see there's a new version being tested.

I am trying to figure out why am I getting tones of GL errors. It doesn't seem to happen always, only when the Line is pretty long. For example, with a length of 200 (5km long) or even 3.000 points (50km long in this case) it works like a charm. No single issue.

However, with a route 200km long (12.000 points), I start to see these errors.

This is an extract of the error log:
```
E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0xd3db9c80
    Out of bounds vertex attribute info: clientArray? 0 attribute 0 vbo 187 allocedBufferSize 0 bufferDataSpecified? 1 wantedStart 0 wantedEnd 4
    a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0xd3db9c80
    Out of bounds vertex attribute info: clientArray? 0 attribute 3 vbo 187 allocedBufferSize 0 bufferDataSpecified? 1 wantedStart 0 wantedEnd 4
E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0xd3db9c80
    Out of bounds vertex attribute info: clientArray? 0 attribute 0 vbo 187 allocedBufferSize 0 bufferDataSpecified? 1 wantedStart 0 wantedEnd 4
    a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute. buf=0xd3db9c80
    Out of bounds vertex attribute info: clientArray? 0 attribute 3 vbo 187 allocedBufferSize 0 bufferDataSpecified? 1 wantedStart 0 wantedEnd 4
```

And this is the code I'm using to add the Line (it's the same for all these 3 cases):

```
private LocalVectorDataSource tracksDataSource;

private void addBundledTracksLayer()
    {
        if (tracksDataSource == null) {
            tracksDataSource = new LocalVectorDataSource(baseProjection);
            tracksDataSource.setGeometrySimplifier(new DouglasPeuckerGeometrySimplifier(1.0f / 320.0f));
            VectorLayer tracksLayer = new VectorLayer(tracksDataSource);
            tracksLayer.setOpacity((float) 0.7);
            tracksLayer.setUpdatePriority(1); // Right now I don't remember why I added this line, but removing it doesn't make any difference
            mapView.getLayers().add(tracksLayer);
        }
    }
private void displayTrackSegments(Document doc)
    {
        NodeList trackSegments = doc.getElementsByTagName("trkseg");
        for (int i = 0; i < trackSegments.getLength(); i++) {
            MapPosVector gpxTrack = new MapPosVector();
            NodeList trackSegmentPoints = trackSegments.item(i).getChildNodes();

            for (int j = 0; j < trackSegmentPoints.getLength(); j++) {
                Node node = trackSegmentPoints.item(j);
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    Element element2 = (Element) node;
                    gpxTrack.add(baseProjection.fromLatLong(
                            Double.parseDouble(element2.getAttribute("lat")),
                            Double.parseDouble(element2.getAttribute("lon"))
                    ));
                }
            }

            displayTrackSegment(gpxTrack);
        }
    }

    private void displayTrackSegment(MapPosVector gpxTrack)
    {
        LineStyleBuilder lineStyleBuilder = TrackLineStyleBuilder.Companion.get(this, R.color.TrackColor);

        tracksDataSource.add(new Line(gpxTrack, lineStyleBuilder.buildStyle()));
    }
```

The app works fine, but it obviously adds noise to the log and there might be a good reason why it does work fine, apparently, for a shorter Line, and in longer ones it throws tones of these errors. Perhaps I'm adding a very detailed Line (it's extracted from a GPX file). But actually, it's necessary for me to display it as it is.

Cheers!

**Comment by mtehver** [comment]
Thanks for reporting this.  I will try to reproduce it locally. What device/Android version are you using? A quick workaround is to split long lines (over 5,000 vertices) into multiple separate Line objects.

**Comment by carlos-mg89** [comment]
Hi @mtehver I've tried what you proposed and even though I was enthusiast with this idea to solve it temporarily, it hasn't resolved the massive error log. I have even tried to draw Lines with a maximum length of 2000 vertices. And 3.000 and 5.000 too. But the errors keep being thrown. So this makes me guess that is either not a matter of a Line being too long.

Perhaps it is a memory issue, or something related with the DataSource.

I'm using an Android emulator and it has the following config:
- RAM: 1.536MB
- VM heap: 256MB
- Internal storage: 2.000MB
- Multi-Core CPU: 2

**Comment by mtehver** [comment]
@carlos-mg89  I did some testing and believe this to be a bug with Android 4.x emulator. Do you have any rendering artifacts with long lines or just these messages in log? Similar messages have been reported in other Android projects and they are usually ignored.

**Comment by carlos-mg89** [comment]
Not sure @mtehver about that, since I use API 27-28.

**Comment by mtehver** [comment]
Interesting. If you could create a small app demonstrating this, I could investigate this further. Otherwise I will treat this as 'wont fix' as emulator issues are low priority.

**Comment by carlos-mg89** [comment]
Most of the code is already published on my first comment. The only missing bit would be the initialization of the Document object (this is a GPX file being open as an XML document). Here you have a method that obtains a Document object:

```
fun readGpxFileStream(gpxFileStream: InputStream): Document?
        {
            var doc: Document? = null
            try {
                val dbFactory = DocumentBuilderFactory.newInstance()
                val dBuilder = dbFactory.newDocumentBuilder()
                doc = dBuilder.parse(gpxFileStream)

                val element = doc!!.documentElement
                element.normalize()
            } catch (ex: ParserConfigurationException) {
            } catch (ex: SAXException) {
            } catch (ex: IOException) {
                Log.d(MapApplication.LOG_TAG, ex.localizedMessage)
            }
            return doc
        }
```

And here the code that uses the above method and the methods on my first comment:

```
public void displayGpxRoute(String gpxFilePath) {
        try {
            File gpxFile = new File(gpxFilePath);
            Document doc = GpxUtils.Companion.readGpxFileStream(new FileInputStream(gpxFile));
            if (doc != null) {
                addBundledTracksLayer();
                displayTrackSegments(doc);
            }
        } catch (IOException exception) { }
    }

```
So this code works well, it does display the route over the map. But as I explained before, when the route is too large the `E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected.` error appears. Lots of them.

**Comment by carlos-mg89** [comment]
I won't create a small app for this, sorry. I'm already posting all the involved code in this matter. There could be, of course, other code that might potentially have something to do. Although I find it weird that I reading a very long GPX file, without showing it, doesn't generate any error or doesn't show any log. It happens when I display it over a Carto MapView.

**Comment by mtehver** [comment]
I am still not able to recreate the issue. I took HelloMapAndroid sample for our GitHub repo, and added the following snippet to create 12000 vertex line:

```
    private void addLongLine() {
        // Create a new layer and add it to the map
        Projection projection = new EPSG3857();// mapView.getOptions().getBaseProjection();
        LocalVectorDataSource datasource = new LocalVectorDataSource(projection);
        VectorLayer layer = new VectorLayer(datasource);
        mapView.getLayers().add(layer);

        MapPosVector poses = new MapPosVector();
        for (int i = 0; i < 12000; i++) {
            poses.add(new MapPos(i * 300, Math.cos(i * 0.01) * 10000));
        }

        LineStyleBuilder styleBuilder = new LineStyleBuilder();
        styleBuilder.setWidth(5);

        Line line = new Line(poses, styleBuilder.buildStyle());
        datasource.add(line);
    }
```

I used API 27 emulator to test but this worked without any warnings in the log. Can you modify the snippet or add further instructions so I could recreate the issue? Otherwise I will close the issue and mark it as a configuration/emulator problem.

**Comment by carlos-mg89** [comment]
That's correct, with your code I don't get any error in the log.

You could perhaps use my code, with the attached GPX file. It's not that big GPX file.
[554530.zip](https://github.com/CartoDB/mobile-sdk/files/3137921/554530.zip)

**Comment by carlos-mg89** [comment]
We can close this issue, since it's happening anymore in the new release, 4.2RC2. Thanks again for the fix!
