### ISSUE TITLE
Full https support

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#268]
All internally used URL-s should use HTTPS instead of http. May require also some server-side changes.
Use this as base url: https://api.nutiteq.com

**Comment by mtehver** [comment]
@jaakla I created a small script. HTTPS seems to work using api.nutiteq.com, but tiles.json and packages.json contain references to other plain HTTP services. These also need to be changed. The test script is here: https://gist.github.com/mtehver/a3366d14316aed59d78ab78190a4d274

**Comment by mtehver** [comment]
Implemented in SDK 4.2.0-rc.1. Closing.
