### ISSUE TITLE
Java extensions of TileDataSource create hickups

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#269]
Implementing ```MergedMBVTTileDataSource``` in this [PR](https://github.com/CartoDB/mobile-sdk/pull/257) i found ou that the Java implemention of it [here](https://github.com/farfromrefug/nativescript-carto/blob/master/src-native/android/cartoadditions/src/main/java/com/akylas/carto/additions/AKMergeTileDataSource.java) creates hickups while the C implemention does not.
It's very noticeable.
I am wondering if it comes from a conversion of the BinaryData when going from Java to C?

**Comment by mtehver** [comment]
Any chance the hiccups are created by garbage collection cycles? This should be visible in logical. Other than that, no idea really. The implementation looks exactly how I would write this.

**Comment by farfromrefug** [comment]
@mtehver  no idea yet. would need to take a deeper look at this.Does jni convert the tiledata or is it passed as it is?

**Comment by mtehver** [comment]
@farfromrefug All processing is done on the native side. Not sure what you mean by JNI here. JNI layer processing should be quite thin, perhaps it is doing some memory pinning but it should not be that expensive. 

Anyway, I think I will review and merge the native MergedMBVTTileDataSource to the SDK now.

**Comment by farfromrefug** [comment]
@mtehver if you have a Java TileSource, when the java loadTile version returns, it must be returning its result to the method it was run from.
In this case if i am correct my java ```loadTile``` is called from C++ using JNI. So the result TileData result also transits from Java to C++ through JNI.

**Comment by mtehver** [comment]
@farfromrefug This could be related to #278, `BinaryData` constructor had a JNI reference leak. Could you confirm that 4.2.0 RC works without hiccups?

**Comment by farfromrefug** [comment]
Yes i read about that other issue. Will test on 4.2.0 and report here

**Comment by mtehver** [comment]
@farfromrefug I think this was fixed in SDK 4.2.0. Can I close the issue or is there anything else that needs investigation?

**Comment by farfromrefug** [comment]
@mtehver TBH i did not have time to test that again. Plus most of the classes i was using in JAva were merged in C++ so lets close this for now
