### ISSUE TITLE
projection with wgs84

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#274]
In my apps (like in most apps) i always work with wgs84 data.
Consequently working with Carto i constantly have to use ```fromWgs84``` and ```toWgs84``` when working with projection.

Is there a way to make the projection and the map use Wgs84 as its default format?
That would make the code so much cleaner.

Thanks

**Comment by mtehver** [comment]
In SDK 4.2, yes. We have EPSG4326 projection so that you can directly use longitude/latitude.

**Comment by phammanhdam** [comment]
@mtehver When the version 4.2 is released, thank your information :)

**Comment by mtehver** [comment]
@phammanhdam We hope to release RC by the end of April and do final release in May, but both dates may slip a bit.

**Comment by farfromrefug** [comment]
It s out!
