### ISSUE TITLE
Marker's setRotation() works the opposite way than ImageView setRotation()

### ISSUE THREAD

**Issue by carlos-mg89** [CartoDB/mobile-sdk#275]
Hi,

I write this up since I'm not sure you intended this on purpose or maybe this is a mistake / confusion. The thing is that the `setRotation()` method from the `Marker` class (I believe is actually an inherited method from the `BillBoard` class) works very differently than the one from the Android's official `ImageView`.

I believe it'd be more consistent to use the same way than the `ImageView`, but that's only because I got crazy while testing this method.

I had to apply a complementary degree operation (`360 - desired_rotation`) in order to get the results I wanted. I have a location marker, and I wanted the marker to point to the bearing between my previous location and the current location. This worked perfectly fine with an `ImageView`, but with the Carto mobile SDK I had to perform the above operation.

As I said at the beginning, perhaps this was your intention, maybe because yo thought that the `ImageView`s implementation doesn't work as you think is natural. And maybe you are right :)

**Comment by mtehver** [comment]
Well, this is a question of conventions. I agree that perhaps the sensible convention would be to use Android's scheme as Android is the most common platform. Nevertheless, changing this would cause major backward-compatibility issue. So I am marking this as 'wontfix'

**Comment by carlos-mg89** [comment]
Alright! As I previously said, if you are aware of this and is not a big deal, that's OK. Just wanted to be sure it wasn't a bug. I've made it work so is not a big deal.

Perhaps it's a nice thing to document this in the examples of the Carto website, or in the code's documentation.

Talking about documentation, I'm not able access to the comments of the Carto mobile SDK while on Android Studio. I realized about this issue after checking it manually on the Github repo. Concretely here https://github.com/CartoDB/mobile-sdk/blob/0a9c83513b265a7c6950377b28f2c6f5f07afb47/all/native/vectorelements/Billboard.h

Do you know how to access it while seeing the classes on Android Studio? It's an inconvenience I'm actually facing in other dependencies too. So I don't believe is a concrete issue with you guys.

Thanks for the reply by the way :)

**Comment by mtehver** [comment]
Thanks for reporting the issue about documentation. We had this working a while a go with Eclipse, but I guess Android Studio needs different approach. I created a new issue for this: #277.

**Comment by carlos-mg89** [comment]
Thanks for creating that issue, I'll follow it then.

I'll close this issue then.
