### ISSUE TITLE
Fatal signal 6 (SIGABRT) - ReferenceTable overflow (max=1024)

### ISSUE THREAD

**Issue by soheil-sf** [CartoDB/mobile-sdk#278]
Hello , I'm using `VectorTileSearchService(dataSource, tileDecoder).findFeatures(searchRequest)` to scan near tiles and using their features in a real time procedure, but is some cases after a while VM aborting and getting **Fatal signal 6 (SIGABRT) at 0x00006825 (code=-6), thread 26661**  and **Failed adding to JNI pinned array ref table (1024 entries)**. 
I'm also getting this error while loading tiles but not as quickly as the above case.

**Comment by mtehver** [comment]
Thanks for reporting this. Any chance you are constructing lots of (>1024) BinaryData objects with java byte arrays as an input? I have identified a leak in this particular case. This will be fixed in 4.2.0.

**Comment by soheil-sf** [comment]
I think the leak is inside DataSource loadTile method. All I'm doing is searching for cached tiles inside a local sqlite DB and if it didn't find any sending request to a tile server to download and storing tiles. BTW this **ReferenceTable overflow ** only occurs in android 4.x ,  mostly 10 mins after start navigating the map.

**Comment by mtehver** [comment]
@soheil-sf Can you test again with SDK 4.2.0-rc.1? This version includes the `BinaryData` fix. If the issue still persists, please provide us a project or snippet that helps us recreate the issue. 

It occurs only in Android 4.x as later Android versions have much bigger ReferenceTables.

**Comment by mtehver** [comment]
SDK 4.2.0 should fix this. Closing. If the issue still persist, this can be re-opened but we would need more details.
