### ISSUE TITLE
Adding Point to a LocalVectorDataSource 4.2.0 RC1 with LOCAL_SPATIAL_INDEX_TYPE_KDTREE is now much slower

### ISSUE THREAD

**Issue by carlos-mg89** [CartoDB/mobile-sdk#282]
I've realized that while adding about 300 `Point` to a `LocalVectorDataSource` with a `LOCAL_SPATIAL_INDEX_TYPE_KDTREE`, the process is way slower than before. Actually, before it was almost instant.

This is the code I'm using:

```
val routesVectorDataSource = LocalVectorDataSource(
                baseProjection,
                LocalSpatialIndexType.LOCAL_SPATIAL_INDEX_TYPE_KDTREE
        )
val routesVectorLayer = VectorLayer(routesVectorDataSource)
routesVectorLayer?.visibleZoomRange = MapRange(MIN_VISIBLE_ZOOM, 24f)
mapView.layers.add(routesVectorLayer)
addRoutes(routesVectorDataSource)

private fun addRoutes(routesVectorDataSource: LocalVectorDataSource) {
        routes.forEach { route ->
            val routeDocument = GpxUtils.readGpxFileAndGetDocument(route)

            if (routeDocument != null) {
                val pointPos = baseProjection.fromLatLong(
                        route.lat, route.lon
                )
                val point = Point(pointPos, getRoutePointStyle())
                val routeId = route.getId()
                point.setMetaDataElement("id", Variant(routeId!!.toLong()))

                routesVectorDataSource.add(point)
            }
        }
    }
```

In the latest RC for 4.2.0 version takes about 10 seconds to appear, and then 5 more seconds to be clickable (there's a vectorElementEventListener which I guess doesn't work untill all Points are added to the LocalVectorDataSource).

The whole process in 4.1.6, initializing the LocalVectorDataSource, adding it to the MapView, loading the 300 Point and enabling them to be clicked, takes about a 2 seconds. Nothing else is changed, only the Carto version.

**Comment by mtehver** [comment]
Something seems way off here. Test with the following snippet:

```
    private void addPoints() {
        long t0 = System.currentTimeMillis();

        Projection projection = new EPSG3857();
        LocalVectorDataSource datasource = new LocalVectorDataSource(projection, LocalSpatialIndexType.LOCAL_SPATIAL_INDEX_TYPE_KDTREE);
        VectorLayer layer = new VectorLayer(datasource);
        mapView.getLayers().add(layer);

        PointStyleBuilder styleBuilder = new PointStyleBuilder();
        styleBuilder.setSize(5);
        PointStyle style = styleBuilder.buildStyle();

        for (int i = 0; i < 30000; i++) {
            MapPos pos = projection.fromLatLong(i * 0.001, 0);
            com.carto.vectorelements.Point point = new com.carto.vectorelements.Point(pos, style);
            point.setMetaDataElement("id", new Variant(i));
            datasource.add(point);
        }

        long t1 = System.currentTimeMillis();

        Log.e("!!!", "t1 - t0 = " + (t1 - t0));
    }
```

Adding 30000 points takes 0.5sec on my old MacBook Pro and they appear on the map instantly.

**Comment by mtehver** [comment]
One more hint to increase the performance of adding elements: do not call hundreds of times `LocalVectorDataSource.add` method, instead construct element vector (`VectorElementVector`) first and then use `LocalVectorDataSource.addAll`.

**Comment by carlos-mg89** [comment]
Your hint was very helpful. It reduced the time and now it's much faster.

I believe I was doing something else that delayed the loading of those Points. I was reading the latitude and longitude from a file, and not from the route objects, even though I wrote it down as I was doing that in the code snippet. Thanks! You helped me a lot with this matter.
