### ISSUE TITLE
[iOS] NTMBVectorTileDecoder crashes with NTCompiledStyleSet

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#283]
I am trying to to use ``` NTMBVectorTileDecoder.alloc().initWithCompiledStyleSet(styleSet)``` but it crashes whatever the style i am using.
Can't really find why exactly. Can't also find any example of this in the CartoDB repos.
Could you confirm that it works on your side?

Also could you write a very short summary on how to setup a live dev env for iOS? I think that's what you are using, right?

Thanks

**Comment by mtehver** [comment]
Did a quick test, seems to work for me, when the style asset we have internally built-in.

Regarding the dev env, iOS is the easiest. Just the latest XCode, CMake and the custom Swig wrapper generator should do it.

**Comment by farfromrefug** [comment]
@mtehver ok need to try here. 
About your dev env. Could you explain how you run it? I dont see any demo app in the ```mobile-sdk``` repo. Do you use https://github.com/CartoDB/mobile-ios-samples ? How do you make it use the sources directly? How are the swig wrapper updated upon change?

This could get very useful to anyone wanting to create PRs.

Thanks

**Comment by mtehver** [comment]
For final iOS tests, we use mostly mobile-ios-samples and few non-public projects. The simplest way to test is to compile SDK first, then checkout mobile-ios-samples project, run 'pod update' on its subprojects and then replace the official SDK build under Pods/CartoMobileSDK with your compiled version (under dist/ios after you have successfully compiled the SDK).

**Comment by farfromrefug** [comment]
@mtehver ok though you had a project with live compile, something like:
- modify src
- click run in xcode

Will try to see if i can do this.

Thanks

**Comment by mtehver** [comment]
@farfromrefug We do not have/use that for full SDK. We use it for submodules, like those in libs-carto. One important bit I forgot: use --configuration=Debug flag when running build-ios.py script. Otherwise you really can not step into SDK when debugging.

**Comment by mtehver** [comment]
@farfromrefug Any update on the crash? Could you test/report with 4.2.0RC2?

**Comment by farfromrefug** [comment]
@mtehver sure will try today or tomorrow. Was trying to create a fulll iOS realtime dev env but did not manage yet.

**Comment by farfromrefug** [comment]
@mtehver i tested this this morning. still crashing with 4.2.0.rc2.
I compiled my own version of the framework in debug.
This is where it crashes
<img width="1623" alt="Screen Shot 2019-05-17 at 11 12 55" src="https://user-images.githubusercontent.com/655344/57917529-28b63200-7895-11e9-9073-1529cfc78e3d.png">
Any idea?

**Comment by mtehver** [comment]
@farfromrefug Pretty sure that your `MBVectorTileDecoder` instance is a null pointer. If you debug you code, perhaps you can check if `swigCPtr` member of the managed proxy object is 0 or not.

**Comment by farfromrefug** [comment]
@mtehver thanks a lot! ACtually created that issue by modifying my code.
Also now thanks to the debug version i saw the real error. Carto was throwing because my zip was not correctly structured.
So it is fixed (need to be able to catch that error from my framework side).

Thanks a lot (again!)
