### ISSUE TITLE
MapEnvelope.getConvexHull simply returns the list of MapPos

### ISSUE THREAD

**Issue by hamadycisse** [CartoDB/mobile-sdk#284]
While it could offer a method which uses https://github.com/CartoDB/mobile-sdk/blob/master/all/native/utils/GeomUtils.h::CalculateConvexHull in order to return a real convex hull

**Comment by mtehver** [comment]
Correct. But `MapEnvelope` constructor that accepts `MapPos` list assumes that it is already convex hull of some point set. Thus recalculating the convex hull is pointless.

**Comment by mtehver** [comment]
Closing this, as the question is answered and there are no plans to expose convex hull calculation code in the SDK.
