### ISSUE TITLE
How to set my font name for BalloonPopup

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#285]
Hello,
In my Android project. I have  a font (*.ttf) in assets folder and my code for BalloonPopupStyleBuilder as bellow, but it's not working for me. Please help me, thank you so much,

BalloonPopupStyleBuilder balloonPopupStyleBuilder = new BalloonPopupStyleBuilder();
balloonPopupStyleBuilder.setTitleFontName("fonts/Roboto-Condensed-Italic.ttf");

**Comment by mtehver** [comment]
SDK currently supports only Android/iOS built-in fonts. You could perhaps try this workaround:

https://stackoverflow.com/questions/2711858/is-it-possible-to-set-a-custom-font-for-entire-of-application/16883281#16883281

Not sure if it works, though.

**Comment by phammanhdam** [comment]
@mtehver thank you very much

**Comment by phammanhdam** [comment]
@mtehver, I did your way but it didn't work :(
