### ISSUE TITLE
Valhalla state in SDK

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#291]
Now in 4.2.0 Valhalla is not present anymore. Does that mean you are dropping it completely?

When creating a ```CartoPackageManager``` you can use for routing ```routing:nutiteq.osm.car``` or ```routing:carto.streets```.
The first one will work ```PackageManagerRoutingService``` while the second one requires ```ValhallaOfflineRoutingService```. So are you dropping  ```routing:carto.streets``` packages too? I ask the question because ```routing:nutiteq.osm.car``` is not really useful when you want pedestrian or bicycle routing.

**Comment by mtehver** [comment]
We plan to keep the custom fork of Valhalla in the project but will not actively maintain it nor include it in the public release. We may revise this once we have a commercial customer who needs it. Updating Valhalla 2.x (the current version) to 3.x requires significant amount.

I am keeping this issue open as this may be of interest to others.

**Comment by farfromrefug** [comment]
@mtehver thanks for answering. Indeed i have seen that 3.x was a big breaking change.
Good to know you are going to keep packages.
Just so you know i am going to publish to bintray an version with Valhalla. Will try to maintain it well. Hope you are ok with this?

**Comment by mtehver** [comment]
@farfromrefug Sure, no problem with that.
