### ISSUE TITLE
How to delete vertex of vector element in EditableVectorLayer

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#293]
I have used EditableVectorLayer to edit the object. But I couldn't find a way to delete a vertex. Can you give me an idea for this? Please help me. Thank you so much

![Screenshot_2019-05-28-10-24-01-662](https://user-images.githubusercontent.com/6292758/58448755-fb8a3f00-8132-11e9-9270-f76aca1f61b6.png)

**Comment by mtehver** [comment]
I do not think we have a demo for this in our samples projects. We had a more complete editing demo for Nutiteq SDK 3 that included this feature. The demo app worked this way: once dragging started, we displayed a 'garbage bin' icon on the corner of the screen. If user dragged a point to the garbage pin, the point was removed.

You can find the relevant source code here:

https://github.com/nutiteq/gismap3-android/blob/master/com.nutiteq.gismap3/src/com/nutiteq/gismap3/EditableOverlayActivityBase.java

I believe the editing API has changed very little, so the code can be perhaps simply copied. The relevant methods are `onDragStart`, `onDragMove` and `onDragEnd`.

**Comment by phammanhdam** [comment]
Thanks @mtehver , 
I have looked at your sample code, but it seems to only deleting the selected element but not the vertex

**Comment by mtehver** [comment]
@phammanhdam No, this is not correct. The code I referenced deletes the vertex being dragged.  Please take a closer look at the following method:

```
public VectorElementDragResult onDragEnd(VectorElementDragInfo dragInfo) {
    		Log.debug("dragEnd");
    		dragging = false;
            Rect rect = new Rect();
            deletePointBtn.getHitRect(rect);
            deletePointBtn.setColorFilter(null);
            deletePointBtn.setVisibility(View.GONE);
            addPointBtn.setVisibility(dragInfo.getVectorElement() instanceof Line ? View.VISIBLE : View.GONE);
            boolean onDeleteBtn = rect.contains((int) dragInfo.getScreenPos().getX(), (int) dragInfo.getScreenPos().getY());
            return onDeleteBtn ? VectorElementDragResult.VECTOR_ELEMENT_DRAG_RESULT_DELETE : VectorElementDragResult.VECTOR_ELEMENT_DRAG_RESULT_MODIFY;
    	}
```

If the vertex is dragged to the garbage bin icon, the method returns `VectorElementDragResult.VECTOR_ELEMENT_DRAG_RESULT_DELETE`, which signals the SDK to remove the vertex.

**Comment by phammanhdam** [comment]
Many thank @mtehver ,

I saw it, I'm so stupid. 

I tried deleting the vertex of the polygon, it's works well until there are 3 vertices left will crash app. 
I don't know the reason

**Comment by mtehver** [comment]
@phammanhdam No problem. Regarding the crash, not sure why this happens. If you delete a vertex of a triangle, SDK should automatically remove the element by calling `onElementDelete`.

**Comment by phammanhdam** [comment]
@mtehver Thank you very much and a map sdk awesome
