### ISSUE TITLE
VectorTileEventListener / VectorElementEventListener priority

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#294]
I have a map which looks like this
![Screenshot_1559569829](https://user-images.githubusercontent.com/655344/58807008-93969580-8617-11e9-80f9-2c4b27e1e9eb.png)
I have setup a ```VectorTileEventListener``` and a ```VectorElementEventListener``` on the layer containing the routes.
The issue that i have is when i click on the "Mont Jalla", the ```VectorTileEventListener``` is called before the ```VectorElementEventListener```.
I would like the the vector element always to be selected first. As a user that seems like what you want.

I dont see a way to achieve that right now, Any idea?

**Comment by mtehver** [comment]
You can not change the order of listeners, but you can implement a workaround: when receiving a click event in your `VectorTileEventListener`/`VectorElementEventListener` do not take action immediately, simply store the relevant click information. If you return false in your listeners, eventually `MapEventListener` will be called and you can reorder you events there.

**Comment by farfromrefug** [comment]
@mtehver thanks for the idea. But i wont go that road. I will end up with a bad user experience. The issue is the delay in user interaction. Can't add any delay. 
Think it is time to dive in the framework ;)

**Comment by mtehver** [comment]
@farfromrefug There should be no noticable delay - the click handling works essentially like this pseudocode:

```
void handleClick(ClickInfo clickInfo) {
  for (layer in layers_reversed) {
    if (layer.listener.onClick(clickInfo))
     return;
  }
  map.listener.onMapClicked(clickInfo);
}
```

**Comment by farfromrefug** [comment]
@mtehver ok but if i read what you are writting the "route" layer should be called first, thus the VectorElementEventListener? Is that becuase i use ```setLabelRenderOrder```? with that option the the label layer is put last?

**Comment by mtehver** [comment]
@farfromrefug The pseudocode is simplified. `VectorTileLayer` actually consists of 2 sublayers, with labels on top of normal layers if you use `setLabelRenderOrder`

**Comment by proXenet** [comment]
unlesh my advence commonsural ending lose account this throw legacy built whit Atome on troned by faith seeding on account dimitryll666.69@gmail.com

**Comment by mtehver** [comment]
I think the questions were ansered, thus closing this.
