### ISSUE TITLE
hide "Evaluation" when no license

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#295]
@mtehver could you remove the "evaluation" from the watermark?

I mean now that everything is open sourced (even the license manager), i feel like it does not make sense to put the evaluation.
Right now i am using the SDK for a client with OSM raster tiles. I don't set a license key as i don't use any carto licensed feature.
So the evaluation text does not really make sense.
If you don't want to do it, can i do it in my custom build? Is that ok with you?
I am also think of allowing the scaling of the watermark to a certain extent (too big when the map is not full screen).

**Comment by mtehver** [comment]
@farfromrefug I think this makes sense. We will discuss it internally first.

If you compile your own build, then sure, feel free to remove the watermark. We would be grateful if you kept some kind of reference/attribution to the SDK, though.

**Comment by farfromrefug** [comment]
@mtehver i dont want to remove the watermark! What i want is:
- remove the evaluation
- allow the watermark to be moved
- allow the watermark to be scaled in something like 0.5/1 scale or maybe a bit more

**Comment by mtehver** [comment]
@farfromrefug Ok, thanks for clarifying. We may add an option to use 'null' license or something like that if you do not need CARTO online services. We would still display the watermark by default, but could allow resizing/moving it.

In case you need CARTO online services, this gets a bit more complicated and I am not currently able to answer if removing the watermark altogether is consistent with usage terms.

**Comment by farfromrefug** [comment]
@mtehver i agree and i again i don't want to remove the watermark altogether. It needs to be shown.
But maybe less intrusive. Especially on small mobile screens or view taking one third of the screen.

**Comment by jaakla** [comment]
General practise for map tools is that no provider allows to remove watermark. Even if you use it as open source, then attribution is required to be kept as courtesy. Unless if you buy really expensive special license for this. 
p.s. under MapView Options there is WatermarkScale, you can set it to 0.5 for example, it it is too big for current screen.

**Comment by farfromrefug** [comment]
@jaakla totally agree. Again the issue is not with the watermark but with the evaluation tag in the watermark.
Also setting the watermark scale is not possible when no carto license has been set

**Comment by mtehver** [comment]
This is now implemented in 4.2.1RC1. Closing.
