### ISSUE TITLE
using style for vector elements

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#296]
I see there is another [issue](https://github.com/CartoDB/mobile-sdk/issues/121) about this. But i am not sure this is the same FR.
Would it be possible to use cartocss style for Vector Layers?
It would make theming and applying style much much more easier:
- you could add ```class``` and ```layer``` as new properties for vector layers
- metada could be used to read nuti props like we do with tile features
- would be much faster as you don't need to go to the native (java, objc...) side and back 
- would be much stronger as you could use text, svg, images, font icons, shields. ....

I am not sure how the code is structured and that would be doable. But yesterday i started working with big clusters, and using cartocss would make things a 1000 times easier.

**Comment by mtehver** [comment]
For `VectorLayer` elements, no, we do not support CartoCSS nor plan to do this. The rendering code for `VectorLayer` elements is not shared with vector tile rendering code. We had a 'lightweight' CartoCSS support, but this is deprecated.

But starting from SDK 4.2.0, SDK include `GeoJSONVectorTileDataSource`. It is most convenient to use if you have GeoJSON inputs, but can be used visualize `FeatureCollection` instances.

**Comment by farfromrefug** [comment]
```GeoJSONVectorTileDataSource``` is not enough in the sense that i can't manipulate the elements.
Can you point me to where the carto css style is applied to the ```VectorTileLayer``` elements? 
Would like to take a look at how feasible this would be (can't find it)

Thanks

**Comment by mtehver** [comment]
@farfromrefug Correct, this is not useful when you have data that needs to changed frequently.

About the code, a starting point would be `MBVectorTileDecoder` class/`decodeTile` method. But most of the relevant code in in mobile-libs-carto repository, in cartocss and mapnikvt subprojects. I would say it is a huge amount of work.

**Comment by farfromrefug** [comment]
will close this for now. No solution right now
