### ISSUE TITLE
Is it posible to create foot routing?

### ISSUE THREAD

**Issue by Jorgee97** [CartoDB/mobile-sdk#298]
Hello, My question comes because I'm building a navigation system inside my university, so I wonder if it is possible to have foot navigation, because the documentation only states nutiteq.osm.car as a possibility, can you guys provide some insight if this feature exist or if it's not yet implemented. Thanks in advance.

**Comment by mtehver** [comment]
Hi. I am assuming you want to use offline routing, right? We have only OSRM car routing available for SDK 4.2.0 at the moment. At some point we will likely add foot/bicycle routing packages also, but I can not give ETA for this.

But there is another option. SDK 4.1.x versions included Valhalla routing engine and the packages for Valhalla support all routing modes. So you could use SDK 4.1.6, for example. It is possible to use Valhalla routing with SDK 4.2.0 also, but in that case you would need to compile the SDK yourself.

**Comment by Jorgee97** [comment]
Thanks for the quick response @mtehver, I'm actuallly trying to use Online routing, I don't know if that makes any difference at all.

**Comment by mtehver** [comment]
@Jorgee97 In that case the same suggestion applies, SDK 4.1.6 contains `ValhallaOnlineRoutingService` that connects to MapBox routing service. You need MapBox API key to use it, though.

**Comment by Jorgee97** [comment]
@mtehver Many thanks for your help.
