### ISSUE TITLE
Offline packages encryption key

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#300]
I am facing issues with offline packages and their encryption key.
The issue is this. In my app i choose a directory on the SD Card to save offline packages.
The idea is first to get more space and not clutter the internal memory. But also to prevent constant download of packages when app is removed / installed.
To be cleared right now the issue is mostly with my env dev where i constantly remove/install my app. Right now everytime i get that offline packages do not have the same encryption key.

It wont happen everyday for normal users but i am still wondering what is the issue with allowing the user to remove/install the app and still use the same offline packages. 
Maybe an encryption key based on the device serial number or such could be enough? That would allow what i am trying to achieve

And also that s eco friendly ;)

**Comment by farfromrefug** [comment]
I have been looking at the code here to get the encryption key and it seems to be exactly what it should be. It's based on the device id + packageid. Dont know why it does not work upon re install then...

**Comment by mtehver** [comment]
@farfromrefug You are right, this is supposed to work as you described. I will do some tests and try to reproduce the issue.

**Comment by farfromrefug** [comment]
@mtehver no test needed on your side. Found the reason!
```android.provider.Settings.Secure.ANDROID_ID``` is based on the sign key.
And in my env it is not the same on in dev and release. I was facing that issue when the carto data was created in one and used in the other.
I guess this would be acceptable and would never happen to a user except me ;)

Thanks for answering !
