### ISSUE TITLE
what kind of License do I need to use the NML 3D data converter?

### ISSUE THREAD

**Issue by Jorgee97** [CartoDB/mobile-sdk#301]
Hello everyone, In regards to the nutiteq/nlm 3D data converter tool at https://bitbucket.org/nutiteq/nlm/src/master/, the examples doesn't make use of the --license-file flag, also don't mention anything about it. It just complain when I run the command to transform a .KMZ to NML, saying that I need a license file.
Which file should I put in, and what kind of license do I need? the one that I use for my current application or is it something different?

Also regarding the note "you need special arrangement with CARTO to have support for this tools" at the link above what does it actually mean?

Thanks in advance for the help.

**Comment by jaakla** [comment]
I added a general license file `nml.license` to https://bitbucket.org/nutiteq/nlm/downloads/ . You can try with this and let me know if it works. If you need special support or project maintenance services and have a commercial project then you can email me (jaak|at|nutiteq.com) and describe your  needs.

**Comment by Jorgee97** [comment]
Thanks for your help @jaakla, it works properly now.
