### ISSUE TITLE
nor aar file after successful build.

### ISSUE THREAD

**Issue by gabrielzencha** [CartoDB/mobile-sdk#302]
Hi,
After a successful build of Mobile-SDK 4.2 for android, I get three different folders but none has the .aar file require for my android studio project. I am completely new to this project and wish to understand it so I don't want to used precompiled .aar and .jar files from other projects. Please how to I incorporate the files I just build to any project on android studio to start using Carto Mobile-SDK

**Comment by mtehver** [comment]
Hi, you need to add '--build-aar' flag to 'build-android.py' script. To build AAR, you may need to specify gradle binary location via '--gradle' parameter (if it is not accessible via PATH). The final .aar file can be found in 'dist' folder, not 'build'.

**Comment by gabrielzencha** [comment]
@mtehver Thank you for the help. I added the --build-aar and --build-jar flags to the script yes it changed the output but still did not get any .aar in dist folder. Inside the dist folder I have an 'android' folder which has x86 , armabi-v7a, x86_64 all having the libcarto_mobile_sdk.so. Also i have another folder called generated which has the java classes and some other wrappers.
this was my command line app: python android-buld.py --profile standard --build-aar --buil-jar

**Comment by mtehver** [comment]
@gabrielzencha Very difficult to suggest anything. Does gradle command line executable work as expected? If I remember correctly, we need relatively new version, like 4.x or 5.x. Do you get any error messages?

**Comment by gabrielzencha** [comment]
@mtehver Thank you very much for your help. I succeeded in building it on mac.  below is the error message in ubuntu 18.04
FAILURE: Build failed with an exception.

* Where:
Build file '/home/gabriel/Downloads/mobile-sdk/scripts/android-aar/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android-aar'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 4.10.1. Current version is 4.4.1. If using the gradle wrapper, try editing the distributionUrl in /home/gabriel/Downloads/mobile-sdk/build/android-aar/gradle/daemon/4.4.1/gradle/wrapper/gradle-wrapper.properties to gradle-4.10.1-all.zip

**Comment by mtehver** [comment]
@gabrielzencha Good to hear you succeeded on Mac. I guess the Android SDK is a bit old on Ubuntu 18.04, as the error message seems pretty clear, you need to update gradle to version 4.10.1 or later.

I am closing the issue now.
