### ISSUE TITLE
[FR] add elevation support to valhalla packages

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#303]
Right now it seems your valhalla offline packages don't take elevation into account.
I can easily be seen by doing bicycle routing with offline and online (mapbox) and compare them.

Would that be possible for you to add elevation support?
Some references:
https://gis-ops.com/valhalla-how-to-build-with-elevation-ubuntu/
https://valhalla.readthedocs.io/en/latest/sif/elevation_costing/

That would be such a great addition!

**Comment by mtehver** [comment]
As we have deprecated Valhalla offline routing in SDK 4.2, we do not plan to do any updates to Valhalla packages ATM. We may bring it back if there is commercial interest, though.

But I agree, this would be nice, especially for bicycle routes.

**Comment by farfromrefug** [comment]
@mtehver thanks for answering so fast again!
I get it, does your valhalla packages still gets semi regular updates? Or are you planning on dropping them?

**Comment by mtehver** [comment]
@farfromrefug Regarding the updates, I can not currently confirm whether we will continue updating the packages, we need to do some usage analysis first. We do not plan dropping the packages in foreseeable future, though.

I think the issue can remain open, it is a reasonable request and perhaps we will get additional comments.

**Comment by farfromrefug** [comment]
@mtehver using this website:
https://gis-ops.com/valhalla-part-3-how-to-build-with-elevation-support-on-ubuntu/
I very easily added elevation data to my valhalla tiles. Which means that the vtiles that i generated with your script contains elevation data!
I will look at making a pr to add getElevationProfile to `ValhallaRoutingProxy`!

**Comment by farfromrefug** [comment]
I dont think we can have this. Valhalla read the ght files directly to get the profile. So it wont work in Carto
