### ISSUE TITLE
some buildings are not rendering "filled"

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#308]
Some building are not rendering correctly. 
<img width="909" alt="Screen Shot 2019-08-13 at 11 38 27" src="https://user-images.githubusercontent.com/655344/62931820-3d846200-bdbf-11e9-94df-5df6e7a45ae4.png">
I think it comes from the fact that those building are not "filled" as you can see on the screenshot taken from https://cloud.maptiler.com/tiles/v3/
Maybe they are seen as line and not polygons?
However openmaptiles manages to render them correctly as seen here
<img width="931" alt="Screen Shot 2019-08-13 at 11 38 32" src="https://user-images.githubusercontent.com/655344/62931933-85a38480-bdbf-11e9-8722-b9f2969d41e5.png">
Me i only manage to render them as "line".
Is there a way to "fill" them?
<img width="480" alt="Screen Shot 2019-08-13 at 11 43 20" src="https://user-images.githubusercontent.com/655344/62931953-92c07380-bdbf-11e9-9ab2-b7f51d9449d7.png">

**Comment by mtehver** [comment]
I will try to take a look at this next week. My first guess is that there is an issue about polygon vertex ordering. If the ordering is flipped for some polygons, then they are treated as 'holes'. In that case that would be issue with tiles not the SDK, but this needs investigating.

**Comment by farfromrefug** [comment]
@mtehver thanks! But if that s the case could we have an option to not care about the order? In a 2D map like that i dont really see the need, at least for me, for "holes"

**Comment by mtehver** [comment]
@farfromrefug That kind of option is not needed as MVT spec defines polygon vertex ordering for both contours and holes. Anyway, this needs some debugging before I can conclude whether this is tile-related issue or a SDK bug.

**Comment by mtehver** [comment]
@farfromrefug I have identified the cause, basically some buildings are not polygons, but linestrings. SDK 4.2.1RC2 will include a fix for this, so SDK will be able to render closed linestrings with polygon and building symbolizers.

**Comment by farfromrefug** [comment]
@mtehver is that this: https://github.com/CartoDB/mobile-carto-libs/commit/2dc92e320a568bb31156d9b96bec9cd379110f1a ?
I tried to build with it and the building still dont render, only the line

**Comment by mtehver** [comment]
@farfromrefug Correct, that is the change. You may need to update your style also, drop `['mapnik::geometry_type'=3]` filter from #building layer.

**Comment by farfromrefug** [comment]
@mtehver indeed it works !!!! awesome! Thank you so much again.
I guess i can close this one as fixed!
