### ISSUE TITLE
zIndex error with polygon and points

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#310]
I am drawing the user location using 2 points and a polygon:
- 1 point for the user position (yellow)
- 1 point to draw a border around the yellow point(white)
- 1 polygon to draw the accuracy

The issue that i have is that whatever i do the accuracy is drawn on top of the points
<img width="113" alt="Screen Shot 2019-08-13 at 12 33 39" src="https://user-images.githubusercontent.com/655344/62935250-e4203100-bdc6-11e9-9b12-2aef3db640d5.png">

I made sure i add the polygon before the points to the dataSource.
Also i make sure the points and polygon positions do not contain any altitude data (even though i dont think it used for points).

Do you have any idea? Is there any hardcoded rule to draw points before polygons?

**Comment by mtehver** [comment]
Correct, if you are using the same layer, then element ordering is not defined (if mixing different element types). A workaround would be to use 2 layers, 1st for polygon and 2nd for points.

**Comment by farfromrefug** [comment]
@mtehver seems a bit heavy to have 2 layers, don't you think?
Would it be "possible" to implement z ordering for this?
I am asking to get your feeling. If so i can look at it

**Comment by mtehver** [comment]
@farfromrefug Agree, this is not an elegant solution. Assuming you are using `VectorLayer` for your elements, this should not be heavy regarding resources or performance, though.

For z ordering, it is possible to use Z coordinate of vector elements to define ordering. That may work (you need to explicitly enable this support by calling `VectorLayer.setZBuffering`) assuming your points/polygons are not partly transparent. For transparent elements you will likely get unwanted rendering artifacts.

**Comment by farfromrefug** [comment]
@mtehver did not know about ZBuffering, but cant use it as it uses transparency.
Will use 2 layers i guess
