### ISSUE TITLE
issue rendering icon fonts

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#311]
There is an issue rendering some icon fonts. I use the same fonts within the mss style and within my app.
AS you can see in the screenshot the bakery icon is rendered correctly in my app but not on the style. Some part seem to be inversed. The issue still appears when not using an halo.
You can actually see the issue on the screenshot in multiple pois like coffee or burger.
![Screenshot_1565693553](https://user-images.githubusercontent.com/655344/62936142-4f6b0280-bdc9-11e9-88ab-e484f204fcce.png)
[maki.ttf.zip](https://github.com/CartoDB/mobile-sdk/files/3496600/maki.ttf.zip)

The font icon has been generated with icomoon and this json file 
[Maki.json.zip](https://github.com/CartoDB/mobile-sdk/files/3496609/Maki.json.zip)

**Comment by mtehver** [comment]
My guess is that the bakery icon contains self-intersecting polygon, which is ill-defined. It causes flipping of inside/outside handling in glyph parsing or signed distance field renderer. Both are external components of the SDK and this seems rather obscure issue, so I am tempted to flag this as 'wont fix'

**Comment by farfromrefug** [comment]
@mtehver No problem with marking this at wont fix. Just needed to know the reason. I guess i can fix the SVGs. Will look at it and report.

**Comment by farfromrefug** [comment]
@mtehver i will close this issue. I still feel something i weird in Carto as this should not happen (and does not in any other platform). But i indeed confirm it is related to flipped "shapes" in SVGs.
