### ISSUE TITLE
Wrong VectorTileClickInfo clickInfo

### ISSUE THREAD

**Issue by soheil-sf** [CartoDB/mobile-sdk#312]
Hello, I have set a `VectorTileEventListener` on a `VectorTileLayer` to get click info using `onVectorTileClicked` but after upgrading my SDK to V4.2.0 it mostly returns wrong clickInfo depending on touch location and sometimes map zoom. for example if I touch the element when it located on the left side of the screen , the click info is right but when the element is at the center of the screen the clickInfo features value belongs to another element in the layer. This method works perfectly in older versions of Carto.

**Comment by soheil-sf** [comment]
I'm not sure but I think it happens because of [this ](https://github.com/CartoDB/mobile-sdk/commit/e2b9c20c589fb2b72d50fe6fcc8f86549e156049?diff=split) change.

**Comment by mtehver** [comment]
Could you make a small test app with detailed instructions how to reproduce it? Our AdvancedMap sample contains basic `VectorTileEventListener` demo if you select 'Online Base Maps' sample and click on any basemap feature. It works as expected using both SDK 4.1.6 and 4.2.0.

**Comment by soheil-sf** [comment]
I have tested 3 versions:

1.  'com.carto:carto-mobile-sdk:4.2.0@aar' : Works perfectly!
2.  release/v4.2.0 cloned and compiled : The problem exist...
3.  'com.carto:carto-mobile-sdk:4.2.1-rc.1 @aar' : The problem exists...

I'm not sure but it seems there is a bit difference between your 4.2.0 version .aar file and release/v4.2.0

**Comment by mtehver** [comment]
I do not think this is related to SDK versions as the relevant code is unchanged. Perhaps it is dependent on tile loading order or something else. I have looked through the code twice and still can not understand what can cause it. I would like to fix this in 4.2.1, but to do that I need to reproduce it myself. Any help is really welcome.

**Comment by mtehver** [comment]
@soheil-sf SDK 4.2.1RC2 is out and should fix this. Feedback is very welcome.

**Comment by mtehver** [comment]
Closing this as 4.2.1 is now released.
