### ISSUE TITLE
some random rules for element rendering?

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#313]
I have always seen some weird behaviors in the choosing of which tile elements to render.
Now here is an example.
In this video i am only panning the map. As you can see the "Gibert Joseph" poi and house number next to it randomly appear / disappear when i hide / show them. 
I say randomly but i think it related to the order the tiles are rendered.
I think it should always be rendered (which is what i want).
![sdk_gphone_x86PSR1 180720 061mguillon08172019140716](https://user-images.githubusercontent.com/655344/63211534-d0433a80-c0f8-11e9-961b-50ff4dd771d4.gif)

**Comment by mtehver** [comment]
In general panning the map may change the visible texts as texts have different weights and texts from new tiles may hide some existing texts which in turn may allow displaying texts with lower priorities. I have some changes to text clipping method that will be in SDK 4.2.1RC2.

**Comment by farfromrefug** [comment]
It seems much better now. Dont know if it is theme related of sdk related...
Will close this for now
