### ISSUE TITLE
[CartoCSS] features drawing order

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#315]
I can't seem to be able to define drawing order.
I thought order of defined rules was used but it does not seem to work.

For example i cant get "university" to be drawn under the landuse features (which should be the case).
Is that doable? If not that's kind of a big issue
<img width="931" alt="Screen Shot 2019-08-19 at 13 56 10" src="https://user-images.githubusercontent.com/655344/63264419-542d2c00-c28b-11e9-9991-67a24dafa2d3.png">
<img width="894" alt="Screen Shot 2019-08-19 at 13 56 19" src="https://user-images.githubusercontent.com/655344/63264420-542d2c00-c28b-11e9-9c4b-6d233e9152f4.png">

**Comment by mtehver** [comment]
Within a layer the rendering order is defined by the ordering of features within vector tile layer. You can force ordering by using 'virtual layers', for example:

```
#layer {
  polygon-fill: #fff;
  ::outline {
    line-color: #000;
  }
}
```

Here 'outline' is a virtual layer that uses features from the original layer.

A small comment about the performance of the sample: it is generally a bad idea to use multiple symbolizers within a rule. For example:

```
#layer {
  line-color: #000;
  polygon-fill: #000;
}
```

In general it forces GLES shader switching for each rendered feature, which requires lots of draw calls and becomes very slow even for a few hundred features. For this particular example (line and polygon symbolizers) SDK can use line shader for both polygons and lines, but as line shader is much more expensive compared to polygon shader, devices with slower GPUs with suffer.

**Comment by farfromrefug** [comment]
@mtehver Awesome! thanks!
