### ISSUE TITLE
wrong drawing of dash array

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#316]
depending on the angle of the line the dash array is weirdly drawn
<img width="433" alt="Screen Shot 2019-08-19 at 17 20 03" src="https://user-images.githubusercontent.com/655344/63277460-abd89100-c2a5-11e9-8f07-233dcb390fca.png">

**Comment by mtehver** [comment]
This is a known issue. The patterned line symbolizer assumes small line widths with long dash strokes, otherwise there can be artifacts. I will revisit this after SDK 4.2.1 release.

**Comment by mtehver** [comment]
@farfromrefug The fix is now in mobile-carto-libs master branch. It did not make into SDK 4.3.0RC1 but will be in final 4.3.0.

**Comment by farfromrefug** [comment]
@mtehver you are awesome. Will build myself , test and report

**Comment by farfromrefug** [comment]
it is confirmed fixed
