### ISSUE TITLE
Question about theme optimisation

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#317]
I think i already asked you in another issue but i can't find it anymore.
```less
[class=city][capital!=2][rank<=2][zoom>=4],
[class=city][capital!=2][rank<=4][zoom>=5],
[class=city][capital!=2][rank<=6][zoom>=6],
[class=city][capital!=2][rank<=7][zoom>=7],
[class=city][capital!=2][rank<=14][zoom>=9],
[class=city][capital=2][zoom>=4] {
}
```

```less
[class=city] {
   [capital!=2][rank<=2][zoom>=4],
   [capital!=2][rank<=4][zoom>=5],
   [capital!=2][rank<=6][zoom>=6],
   [capital!=2][rank<=7][zoom>=7],
   [capital!=2][rank<=14][zoom>=9],
   [capital=2][zoom>=4] {
   }
}
```

Is there a difference performance wise?
I think i can see [here](https://github.com/CartoDB/mobile-carto-libs/blob/cd940ce37b416eb81ecb7a66424d40f38114b417/cartocss/src/cartocss/CartoCSSMapLoader.cpp#L50) that there is a difference when using layers but i wonder about other rules.

**Comment by mtehver** [comment]
I do not think there is any noticeable performance difference. The compiled style should perform the same and parsing/compilation time should be also similar.

**Comment by farfromrefug** [comment]
@mtehver ok thanks actually that question is related to https://github.com/CartoDB/mobile-sdk/issues/226 which is actually where we already talked about this :D 
I am seeing the slow loading again. I know it is related to the way i write my style.
Will try to pinpoint it.
THanks
