### ISSUE TITLE
[Android] map redrawing on app pause/resume

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#318]
On android if you pause and resume the app, the map gets redrawn. I think actually all map data are destroyed and created again.

Mapbox faced that issue too:
https://github.com/mapbox/mapbox-gl-native/pull/9412

If you run the Mapbox Android demo app you won't see that behavior.

**Comment by mtehver** [comment]
I briefly looked at the MapBox GL issue, but did not really understand the discussion nor code there. Also, I am not seeing the same behavior as in the video when using our AdvancedMap samples.

SDK itself tries to preserve EGL context, but it is really a hint and Android can destroy the context when app has been on background a while. But I am not sure that is really relevant here.

I am currently closing this, could look at this again with actual code sample.

**Comment by farfromrefug** [comment]
@mtehver it might be because the sample app does not use fragments.
Trying to create one riht now

**Comment by farfromrefug** [comment]
@mtehver got a fragment sample running and the issue is not happening. Though it has to be on my side!

Sorry
