### ISSUE TITLE
drawing one way symbol

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#320]
Right there does not seem to be a way to draw oneway symbol. The issue is that we need a way to tell if we want to draw text left to right or right to left. This is true for text and marker with ```marker-placement: line``` or ```text-placement: line;```

**Comment by mtehver** [comment]
There is no option to 'flip' markers or texts, you need 2 images of the arrow. If I remember correctly you could create street signs with something like this:

```
#road::arrow {
   [oneway=-1], [oneway=1] {
        marker-placement: line;
        marker-file: [oneway]=1 ? url('icon/arrow-right.png') : url('icon/arrow-left.png');
        marker-spacing: 180;
        marker-width: 11;
        marker-height: 5;
   }
}
```

**Comment by farfromrefug** [comment]
@mtehver tried to use your code. Seems to work in a way. 
But the marker does not always follow the line
![Screenshot_1567501690](https://user-images.githubusercontent.com/655344/64159878-2fb08280-ce3b-11e9-89f4-9db067aa9b33.png)

Also there seems to be an issue with ```marker-spacing: 180;``` (same for text and others)
With it i almost see none

**Comment by mtehver** [comment]
Thanks for reporting this. Should be fixed in develop branch (mobile-libs) now.

**Comment by farfromrefug** [comment]
I can confirm (late though) that this is fixed
