### ISSUE TITLE
Display Carto Vector Layers on Android app

### ISSUE THREAD

**Issue by Jaymo** [CartoDB/mobile-sdk#321]
We are working on an android client that consumes two types of layers:

- Rater layers that can be displayed using `HTTPTileDataSource` and cached using `PersistentCacheTileDataSource`
- Vector layers

The raster layers can be displayed accurately and persisted successfully. The issue is displaying vector layers. The vector layers are served via an API as shown below
<img width="882" alt="Screenshot 2019-09-02 at 11 22 45 AM" src="https://user-images.githubusercontent.com/1636125/64100648-ad5d8b00-cd74-11e9-845c-8b37e8ca1378.png">
How would I go about displaying them successfully as the Raster layers effectively and is there support to cache them

**Comment by mtehver** [comment]
To be clear: I understand that you are using `CartoMapsService` class to access your named maps; is there an issue displaying the named map as a vector tile layer? Or is it simply a question of caching?

In general to switch to vector tile mode, you need to call `cartoMapsService.setDefaultVectorLayerMode(true)` before `cartoMapsService.buildNamedMap`.

If you want to cache the accessed vector tile using `PersistentCacheTileDataSource`, then you need to do following steps:

1. Iterate over the layers returned from `buildNamedMap`
2. Assuming the layer is an instance of `VectorTileLayer`, simply create a new `VectorTileLayer`, but using `PersistentCacheTileDataSource` that caches the original data source of the layer. 
3. Add this new layer to the map.

**Comment by Jaymo** [comment]
Thanks @mtehver The explanation on the `PersistentCacheTileDataSource` for caching. I can try this in and see if it works. Based on the web service API that I have shared on the initial question, the assumption was that the layer name e.g `aire_prote_ge_e` is a Named map built using CARTO Maps API, in so doing to display the same I would `LayerVector layers = service.buildNamedMap(name, new StringVariantMap())` name being the value for the layer in the JSON sent over. However this simply does not work and  and it constantly crashes with `artoMapsService::buildNamedMap: Template 'vente_de_coupe' of user 'xxx' not found` (where xxx) is the right username

**Comment by mtehver** [comment]
@Jaymo The crash is probably an uncaught exception. Nevetheless, I think the error message describes the problem precisely: there is no named map under your usename with id 'vente_de_coupe', 'vente_de_coupe' is simply a name of a specific layer in your named map. Named map ids usually start with 'tpl_', for example 'tpl_69f3eebe_33b6_11e6_8634_0e5db1731f59'.

**Comment by Jaymo** [comment]
going by your response then it would mean  the data source am working with is not a named map and its not an SQL API as well. Then how would I go about showing the layers on the app.
<img width="882" alt="Screenshot 2019-09-02 at 11 22 45 AM" src="https://user-images.githubusercontent.com/1636125/64123511-3d1f2b80-cdad-11e9-8d22-986a9ae9173c.png">

The exact data source looks like this on web
<img width="664" alt="Screenshot 2019-09-02 at 6 10 03 PM" src="https://user-images.githubusercontent.com/1636125/64123578-748dd800-cdad-11e9-9f41-acd827e7fda0.png">

**Comment by Jaymo** [comment]
@mtehver so with further probing I believe they are Carto PostGIS Raster data, redoing my code now results in an error `permission denied for table vente_de_coupe` since my query now looks something like `String sql = "select * from vente_de_coupe".....` How would I go about sorting the permissions issue?

**Comment by mtehver** [comment]
@Jaymo I am missing much of the context here, so not sure my answers are helpful. But I will try. 

The snippet you provided seems to be part of Maps API response. In order to use named map via Maps API in the SDK, you need named map id (or sometimes called template name). The easiest way is to get is to login into CARTO builder and copy it from the URL. For example, if your Builder URL is https://xxx.carto.com/u/xxx/builder/d3a9c12c-1bff-11e6-8680-0ecfd53eb7d3, then the named map id is 'tpl_d3a9c12c_1bff_11e6_8680_0ecfd53eb7d3' (so add 'tpl_' prefix and substitute '-' with '_').

Regarding SQL API, the snippet you provided seems to indicate you are using polygon data, not raster. But if you are sure that SQL API is what you need to use, I suggest reading CARTO developer documentation as you usually need authenticate before allowed to access data via SQL API.

**Comment by Jaymo** [comment]
So I updated my code  (see attached) Now when I try display the a layer e.g `ces3june2018update` I get an error `Errors when trying to instantiate anonymous map: Failed to process "polygon-fill" property: unable to compute ramp, permission denied for table ces3june2018update` Any idea what could be the issue or if am on the right track 
<img width="836" alt="Screenshot 2019-09-24 at 8 38 47 PM" src="https://user-images.githubusercontent.com/1636125/65536236-b2dd6980-df0b-11e9-9307-ecc9359a9f9c.png">

**Comment by Jaymo** [comment]
I figured out that I can only display Public and public with Link
