### ISSUE TITLE
tiles up to date?

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#322]
I see a lot of differences between OpenVectorMapTiles and Carto tiles.
Are they really old?
<img width="1203" alt="Screen Shot 2019-09-03 at 10 48 51" src="https://user-images.githubusercontent.com/655344/64160001-743c1e00-ce3b-11e9-9480-eb6f7836d603.png">

**Comment by mtehver** [comment]
Right, I would guess they are not up-to-date vs latest OSM data. If you need newer tiles, I would suggest trying `MapTilerOnlineTileDataSource`. Online tiles are shared with other CARTO basemap services and we can not directly control or update them.

We are still discussing internally how often we should update offline packages, current versions were updated a while ago.

**Comment by farfromrefug** [comment]
@mtehver thanks for the answer. I think your tiles are actually 2 years old... This is quite old.
I think it is the same for offline packages.
