### ISSUE TITLE
How to cache/persist  Carto LayerVector for offline use

### ISSUE THREAD

**Issue by Jaymo** [CartoDB/mobile-sdk#323]
I am creating `LayerVector` from  a JSON payload and displaying it on a map. 

`LayerVector layers = mapsService.buildMap(Variant.fromString(configJson.toString()));`

This works well, however I am looking for a way to cache/persist the `LayerVector`  for  offline use similar to how I would a `HTTPTileDataSource.` 

Any solution for this?

**Comment by mtehver** [comment]
Do you need 'full offline' support or you just want to improve performance/reduce network traffic?

Assuming the second you need to iterate over the layers in your `LayerVector` and recreate all layers using a a `PersistentCacheTileDataSource` connected to the original datasource of the layer. 

I suggest looking closely at the `PersistentCacheTileDataSource` methods. `setCapacity`, `setCacheOnlyMode` and  `startDownloadArea` could be useful for controlling cache behaviour and pre-fetching tiles to the cache. In case you need full offline functionality, then you need to serialize the main attributes of the layers so that you can recreate the layers in offline mode.

**Comment by Jaymo** [comment]
From the docs it seems `PersistentCacheTileDataSource` requires that the dataSource for caching  be a `TileDataSource` while on my end my data is a `LayerVector` as returned by `mapsService.buildMap`

How would I go about sorting this?

**Comment by mtehver** [comment]
`LayerVector` returned from `CartoMapsService` contains instances of `TileLayer`s (`RasterTileLayer` or `VectorTileLayer`, depending on the configuration of your service class). Simply cast your layer classes to `TileLayer`.

**Comment by Jaymo** [comment]
With a `mapsService` configuration where `setDefaultVectorLayerMode(false)`  for it to return  raster layers, I have tried casting the result of the `mapsService.buildMap` into a RasterTileLayer so that I can access  `layer.getDataSource()` however the casting fails with the error `inconvertible types: cannot cast LayerVector to RasterTileLayer`

See snippet below
<img width="836" alt="Screenshot 2019-09-26 at 12 37 29 PM" src="https://user-images.githubusercontent.com/1636125/65677531-7704ea00-e05a-11e9-8906-eede4fd4bbba.png">

**Comment by mtehver** [comment]
`LayerVector` is a container class, thus you need to *iterate* over its elements (which are layers and can be casted to `TileLayer`).

**Comment by Jaymo** [comment]
Ohh, Gotcha!! Makes perfect sense now

**Comment by Jaymo** [comment]
Since am executing this in a loop I refactored the code  to the below:

<img width="826" alt="Screenshot 2019-09-26 at 5 04 14 PM" src="https://user-images.githubusercontent.com/1636125/65695251-d7f2e900-e07f-11e9-8b66-b18ce27b92a2.png">

It displays well as it was expected, however my assumption  was it will display offline after loading it the first time over network as the case is when using `PersistentCacheTileDataSource` with `HTTPTileDataSource`

Is there any way to have it offline after it loads using `PersistentCacheTileDataSource`

**Comment by mtehver** [comment]
The exception seems to come from `buildMap` call, thus this is expected. The code never reaches the line where `PersistentCacheTileDataSource` is created. In case you need full offline support, I suggest re-reading my original comment about serializing/deserializing layer state. Assuming you have only 1 layer, you simply need to remember the URL of `HTTPTileDataSource` of your layer and you can recreate `PersistentCacheTileDataSource` and connect it to `RasterLayer` in full offline mode.

**Comment by Jaymo** [comment]
This is right, you have to serialize the main attributes of the layers and then in an offline scenario deserialize them for display
