### ISSUE TITLE
How to achieve map interactivity on layers 

### ISSUE THREAD

**Issue by Jaymo** [CartoDB/mobile-sdk#325]
I have interactivity as part of my JSON payload for layers. See below
<img width="843" alt="Screenshot 2019-09-30 at 9 32 50 AM" src="https://user-images.githubusercontent.com/1636125/65854435-4f1ccb80-e365-11e9-9fc7-b8e2703262e2.png">

How do I show interactivity once a user clicks a layer, similar to how the same layer can show a pop up on web when the layers are clicked 

<img width="422" alt="Screenshot 2019-09-30 at 9 35 13 AM" src="https://user-images.githubusercontent.com/1636125/65854545-a0c55600-e365-11e9-9320-786b6c541fd1.png">

**Comment by mtehver** [comment]
I am assuming you are using raster tiles (the solution I am sketching also works with vector tiles, though there is additional and technically better solution for vector tiles). These are the steps needed to enable interactivity:

1) Configure your `CartoMapsService` instance as interactive (use `setInteractive(true)`)
2) Create your custom 'event listener' class by subclassing `UTFGridEventListener` and overriding its `onUTFGridClicked` method
3) Create instance of your listener and attach it to the appropriate raster layer returned from maps service using `setUTFGridEventListener`

If you want to use interactivity in offline mode, then you need to attach `PersistentCacheTileDataSource` to 'utf grid datasources'. Tile layers have additional optional tile data source that is automatically configured by `CartoMapsService` in interactive mode. You can use `getUTFGridDataSource` and `setUTFGridDataSource` methods.

**Comment by Jaymo** [comment]
Am using the `PersistentCacheTileDataSource` I have attached the `setUTFGridEventListener` to the `TileLayer` as below

`TileLayer baseLayer = new RasterTileLayer(cachedDataSource);`
` baseLayer.setUTFGridEventListener(new customGridEventListener(cachedDataSource));`

Then subclassed `UTFGridEventListener` and overridden `onUTFGridClicked`  I then proceed to  get `TileDataSource` from the `PersistentCacheTileDataSource` passed in, then styled a `BalloonPopup`. How would I add that in considering that my source has no `add` method.

See below

<img width="798" alt="Screenshot 2019-09-30 at 1 02 51 PM" src="https://user-images.githubusercontent.com/1636125/65869195-a2514700-e382-11e9-8d74-b67a6b5e232b.png">

**Comment by mtehver** [comment]
Two suggestions: if you create a new tile layer based on existing layer, you probably need to copy 'utf grid datasource' from the original layer. Use `getUTFGridDataSource/setUTFGridDataSource` methods. For offline usage you probably need to wrap another `PersistentCacheTileDataSource` around this datasource. Second, I do not understand why you need 'cachedDataSource' member in your listener class. And calling `source.delete()` seems very wrong. I would suggest NOT calling any `delete` methods at all.

**Comment by Jaymo** [comment]
I corrected this and was able to achieve interactivity.  

<img width="805" alt="Screenshot 2019-10-08 at 1 46 43 PM" src="https://user-images.githubusercontent.com/1636125/66389929-2d10f200-e9d2-11e9-8084-4947fae09306.png">
 
Now its just a matter of styling 
![Screenshot_20191008-134742](https://user-images.githubusercontent.com/1636125/66391982-3badd800-e9d7-11e9-83d5-5e606a7515a8.png)
