### ISSUE TITLE
Static vector layer/ marker

### ISSUE THREAD

**Issue by rexfordnyrk** [CartoDB/mobile-sdk#326]
Thank very much for your library, its been awesome using it.
Please I would like to ask. how would I be able to have static marker to pick location cordinates.
So theres the marker for selecting location position in the center of the map but its static and dont move with the map when interacting with the map. just like you can do in apps like uber,bolt 
![location_picker](https://user-images.githubusercontent.com/7267490/66131334-c57a3180-e5e2-11e9-9def-bc956f93b025.gif)

**Comment by mtehver** [comment]
I am pasting a snippet here that should do this:

```
        Projection proj = mapView.getOptions().getBaseProjection();
        LocalVectorDataSource datasource = new LocalVectorDataSource(proj);
        VectorLayer layer = new VectorLayer(datasource);
        mapView.getLayers().add(layer);

        MarkerStyleBuilder builder = new MarkerStyleBuilder();
        builder.setSize(20);
        final Marker marker = new Marker(mapView.getFocusPos(), builder.buildStyle());
        datasource.add(marker);

        mapView.getMapRenderer().setMapRendererListener(new MapRendererListener() {
            @Override
            public void onBeforeDrawFrame() {
                MapPos focusPos = mapView.getFocusPos();
                if (!focusPos.equals(marker.getGeometry().getCenterPos())) {
                    marker.setPos(focusPos);
                }
            }
        });
```


You should also call `mapView.getMapRenderer().setMapRendererListener(null)` when shutting down the map.

**Comment by rexfordnyrk** [comment]
Thank you very much Sir. Will test it and give you feedback. but in the mean time I am going to close this issue. Thank again
