### ISSUE TITLE
Correctly display click Info data on BalloonPopup

### ISSUE THREAD

**Issue by Jaymo** [CartoDB/mobile-sdk#327]
I am getting clicked element variant as JSON  Object  `clickInfo.getElementInfo()` then this data is being displayed on a BalloonPopup `clickPopup = new BalloonPopup(clickInfo.getClickPos(), styleBuilder.buildStyle(), "", variant.toString());`

The JSON  Object  is being displayed as a name value pair on the BalloonPopup

![imageedit_2_5804315865](https://user-images.githubusercontent.com/1636125/66753738-1587ac80-ee9d-11e9-854b-864f75a73b42.png)

How can I get the actual name of the key  instead of the key itself i.e Instead of `agency_name` it should be `Name` as is on carto end

**Comment by mtehver** [comment]
If I understand correctly, in CARTO Builder you see 'agency_name' field as 'Name' field? I am afraid such remapping info is not returned via the Maps API, so you need to remap the keys yourself.
