### ISSUE TITLE
How to Ignore the metadata bound in MBTiles

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#329]
I am using the **MBTilesTileDataSource** class for reading mbtiles data.

However, my mbtiles data has **metadata bounds** smaller than tiles table reality and the SDK doesn't load tile on outside of bounding.

Please help me, how to Ignore the metadata bound in MBTiles.

Thank you very much,

**Comment by mtehver** [comment]
If you can modify your mbtiles files, I would suggest deleting 'bounds' key from 'metadata' table. If that is not an option, you can probably subclass `MBTilesTileDataSource` and override `getDataExtent` method like this (in Java):

```
class MyMBTilesTileDataSource extends MBTilesTileDataSource {
  ...
  @Override
  public MapBounds getDataExtent() {
    return getProjection().getBounds();
  }
}
```

**Comment by phammanhdam** [comment]
@mtehver ,  Thank your reply

I did it your way and unfortunately my application crashes. I think, if setting the extent too large
then the SDK loads the tiles very slowly. 
I set buffer bound up to 5000m, and it's work with my case. It is not the best solution but thank you very much.

`@Override
  public MapBounds getDataExtent() {
    return getProjection().getBounds();
  }`

Change to

`@Override
    public MapBounds getDataExtent() {
       int deltalBuffer = 5000;
       MapBounds orgExtentBounds = super.getDataExtent();
        if (orgExtentBounds != null) {
            MapPos mpMax = orgExtentBounds.getMax();
            MapPos mpMin = orgExtentBounds.getMin();
            
            MapPos mpNewMax = new MapPos(mpMax.getX() + deltalBuffer, mpMax.getY() + deltalBuffer);
            MapPos mpNewMin = new MapPos(mpMin.getX() - deltalBuffer, mpMin.getY() - deltalBuffer);
            return new MapBounds(mpNewMin, mpNewMax);
        } 
    }`
