### ISSUE TITLE
[idea] how to have lighter libs 

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#331]
I am always thinking about how to make the native libs (android especially) smaller. RIght now a big reason for the size of the lib is the number of JNI functions to be wrapped. 
Also in my test decreasing the amount of function would make the lib load much faster.
I always take the example of Mapbox. Looking at it they have i think only one JNI function and the lib loads instantly.

The difference between Mabpox and Carto that i see:
* carto have a lot more classes. Which means constructor and thus JNI definitions. Nothing can really be done there.
* all those class have setter getter => JNI definitions.

We could do something about the second one i think. I wonder if we could define simply 2 methods per class(c++): set(propName, ...args) and get(propName). That would not change the java/obc signatures but would heavily decrease the number of C++ function to be called with JNI. And thus would lower the lib size and loading time.

Do you get what i mean? What do you think about it?

**Comment by mtehver** [comment]
A small comment about iOS first. Currently SDK uses static library for iOS, which means that only relevant code is embedded into the application. Thus no binary size issues on iOS, I believe.

For Android, we have .so files that usually contain a lot more features than really needed by  applications. There are a couple of options. We could build several versions of the SDK with various feature levels. Unfortunately this is a logistic nightmare. The suggestion for wrapping setter/getters using 2 methods per class is doable, but would unlikely improve SDK .so binary sizes more than 5-10% and would have additional performance penalty. This would require modifying 'swig' wrapper generator, which is non-trivial.

**Comment by farfromrefug** [comment]
@mtehver how did you compute the 5-10%? For me looking at the list of JNI functions it would be more.
Also what performance penalty are you talking about?

But i agree about modifying swig generator. It is not "trivial" but doable.

I also see that all JNI classes have JNI function swigGetClassName, swigGetDirectorObject, swigGetRawPtr. I wonder why i dont see those in Mapbox.

**Comment by mtehver** [comment]
@farfromrefug 5-10% was an estimate. Thinking about it, I would expect it to be closer to 5% than to 10%. A simple test to get more precise estimate would mean replacing autogenerated getters/setters of a specific class manually and compare the resulting compiled binary sizes to original binary sizes.

Performance penalty would be small, but present as there is need to have a dispatching code from generic setters/getters to actual methods on C++ side.

regarding swigGetClassName, swigGetDirectorObject - these methods are not added for all classes, only for polymorphic classes (classes that have subclasses) and for 'director' classes (classes that can be subclassed at application level). swigGetRawPtr seems to be added to all classes - it is probably unnecessary in lots of cases but the overhead is really small.
