### ISSUE TITLE
Docs for version 4.2.2

### ISSUE THREAD

**Issue by csubira** [CartoDB/mobile-sdk#333]
According to what was discussed here https://github.com/CartoDB/mobile-sdk/issues/332 there are new features in version 4.2.2 that need to have documentation published in Dev Center.

### To be decided/answered:
1. Do we want to keep 4.1.3 docs published in the web as well?
2. Are the new docs (guides and API Docs) for 4.2.2 already written?
3. Estimate tasks and resources

**Comment by mtehver** [comment]
My suggestions:

1. There is not need to keep docs for older versions, as we guarantee high level of backward compatibility. Also, we do not support older versions in the sense that we do not backport fixes to older versions, thus only support the latest version.

2. API docs are auto-generated and we keep them in our samples repositories. These are already up-to-date (http://cartodb.github.io/mobile-ios-samples/ and http://cartodb.github.io/mobile-android-samples/reference/packages.html). Guides not so much, as they do not include sections for the newer features. But the sample code in guides works as well in newer SDK versions.

**Comment by csubira** [comment]
Great!
Then, regarding to 1) I can easily change the version displayed in the title in Dev Center to the new one so the site is updated. 

And 2) if the docs in master are updated, that's what it's going to be seen in Dev Center. Any new info about new features or etc can be included there and it will be fetched and published in the scheduled deploys. With reference of the `cartodb.github.io` pages I'd refer them from the guides or docs in Dev Center to make sure users find them there (I don't know if they're already)
 
I've opened a PR in Dev Center to change the version. https://github.com/CartoDB/developers/pull/669 (As you see it's only a hardcoded text) In order to have the last version updated my proposal is that every time that there's a new version you can open a PR in Dev Center to change it. It can be reviewed by Response Team to be merged. Does it sound good @mtehver ?

**Comment by mtehver** [comment]
@csubira Thanks, sounds great! Only thing, I do not have access to https://github.com/CartoDB/developers/ page, thus I am not able to create PRs.

**Comment by csubira** [comment]
@mtehver Then, what about opening an issue in Mobile SDK repo and tag us?

**Comment by mtehver** [comment]
@csubira Sure, that would work. Will do that.

**Comment by csubira** [comment]
Thanks a lot @mtehver ! 
(I'm merging the PR with the 4.2.2 version and deploy right now!)
