### ISSUE TITLE
[Bug] Variant getString() -Error: input is not valid Modified UTF-8

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#335]
I use mbtiles vector data and when clicking to get object information, there is an error. Maybe due to Variant's getString () function, you can add the getBytes() method to Variant and I can decode string with my encoding.

Thank you very much,

`A/.geotech.vtool: java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xa7
    java_vm_ext.cc:570]     string: 'C.ty TNHH MTV LN ��k Glei'
    java_vm_ext.cc:570]     input: '0x43 0x2e 0x74 0x79 0x20 0x54 0x4e 0x48 0x48 0x20 0x4d 0x54 0x56 0x20 0x4c 0x4e 0x20 <0xa7> 0xa8 0x6b 0x20 0x47 0x6c 0x65 0x69'
    java_vm_ext.cc:570]     in call to NewStringUTF
    java_vm_ext.cc:570]     from java.lang.String com.carto.core.VariantModuleJNI.Variant_getString(long, com.carto.core.Variant)
A/.geotech.vtool: runtime.cc:630] Runtime aborting...
    runtime.cc:630] Dumping all threads without mutator lock held
    runtime.cc:630] All threads:
    runtime.cc:630] DALVIK THREADS (37):
    runtime.cc:630] "Thread-451" prio=4 tid=37 Runnable
    runtime.cc:630]   | group="" sCount=0 dsCount=0 flags=0 obj=0x12e00000 self=0x7364e10800
    runtime.cc:630]   | sysTid=24619 nice=10 cgrp=default sched=0/0 handle=0x72bed92d50
    runtime.cc:630]   | state=R schedstat=( 479801232 7037869 74 ) utm=8 stm=39 core=7 HZ=100
    runtime.cc:630]   | stack=0x72bec9c000-0x72bec9e000 stackSize=991KB
    runtime.cc:630]   | held mutexes= "abort lock" "mutator lock"(shared held)`

**Comment by mtehver** [comment]
Interesting. Can you share a code snippet to reproduce the issue? Internally, SDK assumes that all strings are UTF-8 encoded and all string inputs coming from Java side should be automatically converted from unicode to UTF-8. So I am not sure how this can happen.

**Comment by phammanhdam** [comment]
@mtehver,  
I'm using MBTiles DataSource for Vector Tile Layer and set VectorTileEventListener for get properties when click to a feature. 

I using GDAL for create mbtiles data from Shapefile with font encoding TCVN3 (Vietnamese) not UTF8

MBTiles data sample: https://www.dropbox.com/s/d8xb8mbz7wy15oo/DakGlei_DinhVanHuu.mbtiles?dl=0

CartoCSS for mbtiles:
`#DakGlei_DinhVanHuu {line-width:2.0;line-color:rgba(46, 213, 115, 1.0);polygon-fill:rgba(112, 161, 255, 0.47843137);text-name:[TK]+ "\n" + [KHOANH]+ "\n" + [LO];text-face-name:'Roboto Regular';text-size:18;text-fill:#036;text-allow-overlap:false;text-halo-fill:fadeout(white, 25%);text-halo-radius:2.5;text-halo-rasterizer:fast;text-wrap-width:125;text-wrap-before:true;text-placement:point; }`

And code snippet
`private class VectorTileListenerCustom extends VectorTileEventListener {

        @Override
        public boolean onVectorTileClicked(VectorTileClickInfo clickInfo) {
            if (clickInfo.getClickType() == ClickType.CLICK_TYPE_SINGLE) {
                Feature feature = clickInfo.getFeature();
                if (feature.getProperties().containsObjectKey("CHURUNG")){
                    Variant val = feature.getProperties().getObjectElement("CHURUNG");
                    String s = val.getString(); //Error if input is not valid UTF-8
                }

            }
            return true;
        }
    }`

Hope you can handle this error, thank you

**Comment by mtehver** [comment]
So the string attributes for vector tiles are encoded as TCVN3, not UTF8? In that case the .mbtiles file has illegal encoding - MapBox vector tiles inside .mbtiles use protobuf format. Protobuf specifies that all strings must be UTF8 or ASCII7 (https://developers.google.com/protocol-buffers/docs/proto#scalar). If possible, I suggest re-encoding the .mbtiles file.

**Comment by phammanhdam** [comment]
Thank @mtehver and your comment. 
And I think i need to convert encoding to UTF-8 to solve this problems.
Best regards,
