### ISSUE TITLE
[4.3.0] issue with labels and variables rules

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#340]
I am testing the develop branch.
Running it on a style of mine i see this

The names are computed using a variable:
```
@name: [nuti::lang] ? ([name:[nuti::lang]] ? [name:[nuti::lang]] : ([name:[nuti::fallback_lang]] ? [name:[nuti::fallback_lang]] : [name])) : [name];
```
Feels like that "expression" is not computed anymore.
![Screenshot_1584439854](https://user-images.githubusercontent.com/655344/76846025-28cde800-6840-11ea-8056-5139a93a165c.png)

Let me know how i can help. Maybe we can chat somewhere, this could make things faster

**Comment by mtehver** [comment]
Thanks for reporting this. Could you share your full style and settings of the nutivariables? We use the same @lang expression in our built-in styles and there are no such issues.

**Comment by farfromrefug** [comment]
Here you go. It happens with all my styles but not carto v1 or v2
[mapsme.zip](https://github.com/CartoDB/mobile-sdk/files/4343254/mapsme.zip)

**Comment by mtehver** [comment]
Thanks. I guess you are actually using precompiled XML style, not CartoCSS style? Can you build a new version of the css2xml utility based on the latest snapshot from 'develop' branch and try again? I believe the latest css2xml utility should fix the issue as the encoding of 'TextSymbolizer' expression changed a bit between the translation phases.

I could not reproduce the issue, but the sample allowed me to discover an unrelated problem that is now fixed.

**Comment by farfromrefug** [comment]
@mtehver indeed will test with a newly built css2xml! Thanks

**Comment by farfromrefug** [comment]
@mtehver any place where we can chat?
I compiled `css2xml` but now it fails while compiling my style:
```
Exception while compiling: Error while building zoom 5 properties: Expression parsing failed: 
 
```
The error is not showing the line where it fails.

**Comment by farfromrefug** [comment]
@mtehver i can confirm that the newly built css2xml fixes the issue.
Thanks!
