### ISSUE TITLE
If can use Google Maps vector tile overlay ?

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#341]
I am looking way to use the Google Maps vector tile map to overlap with the Cartodb SDK.  Can someone help give me the idea.
Thanks a lot,

**Comment by mtehver** [comment]
Sorry, as far as I know Google Maps uses proprietary vector tile format that 3rd party solutions (like Carto Mobile SDK or MapBox SDK) do not support. Thus the only was is to use raster tiles from Google but even that could be illegal due to copyright issues.

**Comment by phammanhdam** [comment]
I found the MapTiler, they extended Mapbox SDK source code to use the Google Map vector tile. I thing it's a good idea with CartoDB mobile,
Many thanks, 

https://www.maptiler.com/mobile/?_ga=2.72962074.865069155.1584623136-1243645568.1584623136

**Comment by jaakla** [comment]
Where did you get info that MapTiler uses Google Map vector tiles, and not raster tiles?

**Comment by phammanhdam** [comment]
> Where did you get info that MapTiler uses Google Map vector tiles, and not raster tiles?

You can install MapTiler app in Google Play and check 
https://play.google.com/store/apps/details?id=com.maptiler.geoeditor

**Comment by farfromrefug** [comment]
This is not google map vectors. Simply openmaptiles with a google look a like style

**Comment by phammanhdam** [comment]
> This is not google map vectors. Simply openmaptiles with a google look a like style

I don't think so, It is exactly Google Map vector tile, it includes Street, Hybrid, Terrain and Satellite

![Screenshot_2020-03-20-14-03-17-931_com maptiler geoeditor](https://user-images.githubusercontent.com/6292758/77142964-486d4680-6ab4-11ea-8674-25a2b3da87c1.jpg)
![Screenshot_2020-03-20-14-04-03-580_com maptiler geoeditor](https://user-images.githubusercontent.com/6292758/77142967-4c00cd80-6ab4-11ea-8758-03ad64eb1414.jpg)
![Uploading Screenshot_2020-03-20-14-04-26-698_com.maptiler.geoeditor.jpg…]()

**Comment by farfromrefug** [comment]
Sorry but you are wrong. It is very easy to see that those are openmaotikes when you know what to look at(missing data in openmaptiles also missing in those maps). Plus shops are actually those from osm and not google. And finally when If you snif the network trams you will see.that it does not come from google ;)

**Comment by phammanhdam** [comment]
@farfromrefug OK thank you so much,
