### ISSUE TITLE
line-pattern wrongly drawn

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#345]
<img width="837" alt="Screen Shot 2020-03-29 at 12 10 19" src="https://user-images.githubusercontent.com/655344/77846491-bbfb0c00-71b6-11ea-8f77-21f37056725b.png">
As you can see a line pattern is really wrongly drawn. 
You can see the svg at the very top left. It is the one from OSM

**Comment by mtehver** [comment]
Thanks. Is the cliff2.svg the same as this one: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/cliff2.svg ?

There seems to be stretching issue. In addition, the artifacts are related to issue #316. I will try to fix this in final 4.3.0, but no promises.

**Comment by farfromrefug** [comment]
@mtehver yes they are coming from that repo. Let me know if you want a full style.
Also cliffs are not part of OpenMapTiles packages ;) 
Let me know if you want a mbtiles with it.
However you should be able to have the same issue with roads for example.
