### ISSUE TITLE
[feature-id] seems to behave weirdly with non existing property

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#346]
Let's say i use this:
```
text-feature-id: [name];
```
It works great when there is a name. But very weirdly when there is none. 
For example if this is used for icon (font icon) i can see the icon changing randomly while zooming in or out.
I think this is due to `text-feature-id` actually being set to "" when there is no name.Or maybe it is `null`?

In case with that i seems that  a large number of "features" share the same which creates the issue i am seing.

Could you change the behavior so that when the feature id is "" or null it is simply not "enabled"?
This would allow us to use it with `[name]` or `[ele]` or anything else without having edge cases.

**Comment by mtehver** [comment]
What are you using for `text-name`? Some fixed symbol? The problem is that 'feature-id' needs to have a unique value. Assuming this is for mountain peaks, could you combine `[name]` with `[ele]`? Something like this:

```
text-feature-id: [name] + '\n' + [ele];
```

**Comment by farfromrefug** [comment]
I use all the time because I use font icons to draw like pois icons and I need to text to be linked to the icon. 
I will use osmid now that I have it In my tiles. However I still think there is a bug there and that if feature-id is null or '' it should be treated as NO feature-id or it will have very bad side effects

**Comment by mtehver** [comment]
I agree about the ugly side effects. This feature is kind of a 'work-around feature' anyway, as ideally features should have ids identifying them. I will think about this a bit more, as there are a few options how this can be implemented with different effects.

**Comment by farfromrefug** [comment]
BTW i do have this working with osmid, but that will work only for me...

**Comment by mtehver** [comment]
I have now implemented this: for null values, empty strings a unique id is automatically generated. The auto id works much better in these cases.
