### ISSUE TITLE
[cartocss] breakline in text breaks font boldness

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#347]
For moutain peaks i use this:
```
text-face-name: @mont_md;
text-name: @name ?  ( [ele] + 'm' + '\n ' + @name): '';
```

mont_md is a medium font.
Here is the render.
As you can see the elevation is not "medium". It s actually a nice feature to be able to do this, but not wanted there :D 
![tns-NativeScriptActivity-04032020093024](https://user-images.githubusercontent.com/655344/78335627-431cfb00-758e-11ea-8327-9dee90bcd49e.png)

**Comment by mtehver** [comment]
Thanks for reporting this.  A really good find. Turns out the font shaping library treats '\n' symbol in text in a very strange way. Should be fixed now in mobile-carto-libs repo.

**Comment by farfromrefug** [comment]
@mtehver awesome! would love to test this. Did you see the issue https://github.com/CartoDB/mobile-external-libs/issues/1 ?
Can't build anymore. Not sure if i can bring back the boost submodule or if you made changes to it.

**Comment by farfromrefug** [comment]
@mtehver i can confirm it is fixed in develop!
THanks
