### ISSUE TITLE
[cartocsss] operator || not working

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#348]
It is said in the doc that the operator `||` is working
However if i try to do that
```
@maki_icon: [nuti::maki-[subclass]] || [nuti::maki-[class]] || [nuti::maki-[layer]];
```
it does not seem to work.
Would be very practical as easier to read than using `?:`

**Comment by mtehver** [comment]
The || operator is designed to return boolean, as in C/C++. I know there are languages that support something like this (Python, for example). But most C-based languages do not. A better proposal would be be to add something like ?? operator in C# in addition to ||. Currently closing this and marking 'wont fix'.

**Comment by farfromrefug** [comment]
oh ok! got it ;)
