### ISSUE TITLE
[android]broken render sometimes after sleep/awake

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#349]
Sometimes after coming back from sleep and moving a bit around the map the render gets broken
Here are 2 examples
Suspending app the resuming it fixes the issue
![Screenshot_20200403-123347_Librechair](https://user-images.githubusercontent.com/655344/78381691-04ab2e80-75d6-11ea-9357-8964f3e25396.png)
![Screenshot_20200403-161435_Librechair](https://user-images.githubusercontent.com/655344/78381693-0543c500-75d6-11ea-9ea9-d7de0e95d36c.png)

**Comment by farfromrefug** [comment]
@mtehver Got some logs. It seems to be indeed a broken GL context.
However i cant really seem to find what exactly broke it.

[logs-2020-04-06-20-40-02.zip](https://github.com/CartoDB/mobile-sdk/files/4442523/logs-2020-04-06-20-40-02.zip)

**Comment by mtehver** [comment]
Thanks, the log is helpful. I will try to reproduce this myself, there are a few hints in the log.

**Comment by mtehver** [comment]
@farfromrefug Could you test with 4.3.0RC2? This version should fix the issue. Though I did not manage to reproduce this, the log was very helpful. Thanks!

**Comment by farfromrefug** [comment]
@mtehver i have been digging into this and this might be an issue with `GLSurfaceView`
It seems that Mapbox also faced that. 
The doc about [`TextureView`](https://developer.android.com/reference/android/view/TextureView) mentions that. I think the issue comes with fragment animations.
Maybe the solution would be to do the same think as Mapbox did, allow to render either using `GLSurfaceView` or `TextureView`. See [here](https://github.com/mapbox/mapbox-gl-native-android/blob/013076339111ae36862d474895588adec3795d24/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L291)
Would you prefer that or like a new MapView class like TextureMapView ?
The second solution might be easier to develop.

**Comment by mtehver** [comment]
@farfromrefug I think you are correct, the black background is an artifact from `GLSurfaceView`. Having a another rendering surface based on `TextureView` would be nice and I think MapBox implemented it the way it should be done (configurable via options). If you think there is no other workaround, feel free to open another issue for this.

**Comment by mtehver** [comment]
I am closing this, as the original issue should be fixed in 4.3.0.
