### ISSUE TITLE
Add cartocss::MapGenerator tot the sdk

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#350]
I am thinking about adding a live theme editor un my app.
The process would be fairly simple by editing the mss files. However for better performance I would still like to save the theme in XML. To do that I would need MapGenerator to be added to the SDK. 
If you agree that mean I would need public aois to access the cartocssmaploader ( which is already include in the SDK but not public I think) and MapGenerator

I have looked at the code and it seems it would not be too big of an addition to the SDK. 

Hope you agree thanks

**Comment by mtehver** [comment]
I think this can be done, though I am not sure this is needed for 'offical SDK build'. I think a better option is to add this as a 'custom SDK profile'. I will think about this a bit more before committing.

A best fitting API would be to add `buildCompiledStyleSet` method to `MBVectorTileDecoder` class. Would this make sense?

**Comment by farfromrefug** [comment]
@mtehver a profile would be perfect.
By `buildCompiledStyleSet` you mean that it would generate an "xml" version of the underlining style(which would be made of mss files)? How would it return it?

**Comment by mtehver** [comment]
@farfromrefug SDK 4.4.0RC1 includes rewritten CartoCSS translation pipeline that is roughly 3x times faster than before (and likely much faster than using previous precompiled styles). So I think this idea should be simply dropped. Any thought?

**Comment by farfromrefug** [comment]
@mtehver i agree not needed anymore!
