### ISSUE TITLE
text-allow-overlap breaks text-placement

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#352]
i have something like this
```
::icon[class!=null] {
			text-placement: [nuti::markers3d];
			text-name: @osm_icon;
			text-size: linear([view::zoom], (18, 10), (20, 14.0)) - 0.000001 * [rank];
			text-face-name: @osm;
			// text-opacity:0.8;
			text-feature-id: @featureId;
			text-allow-overlap: true;
}
```
 As you can see the icons are not rotating correctly with the map. If i disable `text-allow-overlap: true;` then it works.
![tns-NativeScriptActivity-04072020105229](https://user-images.githubusercontent.com/655344/78649546-e38c5b80-78bd-11ea-82bd-ee6a3cb05ab7.png)

**Comment by mtehver** [comment]
Yes, this is a known artifact. This has to do with 'label' and 'simple' rendering modes. I added a comment about this to the Wiki page: https://github.com/CartoDB/mobile-sdk/wiki/CartoCSS-notes#label-rendering-mode-vs-simple-rendering-mode. If you really need this, I suggest adding `text-clip: false;` to the style.

**Comment by farfromrefug** [comment]
Your explanation is perfect. It is not necessary for me I was testing things.  Might need in a very few cases in which i will use text clip. Thanks!
