### ISSUE TITLE
RasterTileEventListener is not stable

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#354]
I have used RasterTileLayer with RasterTileEventListener but it is really unstable. Sometimes it works but is not stable as VectorTileLayer with VectorTileEventListener.
Did I miss something? Please help me,
Thanks you so much.

I test on Android 10 with SDK version 4.2.2
       `RasterTileLayer rasterTileLayer = (RasterTileLayer) tileLayer;

                rasterTileLayer.setRasterTileEventListener(new RasterTileEventListener() {
                    @Override
                    public boolean onRasterTileClicked(RasterTileClickInfo clickInfo) {
                        Log.i("ZXC", "onRasterTileClicked XXX");
                        Log.i("ZXC", clickInfo.getClickPos().toString());
                        return true;
                    }
                });`

**Comment by mtehver** [comment]
Thanks for reporting this, this is really bad regression in SDK 4.2.x versions. Will be fixed starting from SDK 4.3.0RC2 (I plan to publish it next week).

**Comment by phammanhdam** [comment]
Great, it worked stably in version 4.3.0RC2. Could you tell me when the final 4.3.0 release will be released. 

Thank you so much

**Comment by mtehver** [comment]
@phammanhdam The current plan is early May, unless something critical comes up.
