### ISSUE TITLE
Bug when remove all vector layers

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#357]
Hello, 
I am using many Vector Layers with LocalVectorDataSource. And when changing data, I need to remove all the old layers. But something went wrong, the mapview didn't remove the vector layers. This only happens on SDK version 4.3.0RC2. With version 4.2.2 and below, it works well.

This is my code, please fix it. Thanks you so much.

`LayerVector vLayers = new LayerVector();
        Layers layerManager = this.mapView.getLayers();
        for (int i = 0; i < layerManager.count(); i++) {
            Layer currentLayer = layerManager.get(i);
            if (currentLayer instanceof VectorLayer) {
                if (((VectorLayer) currentLayer).getDataSource() instanceof LocalVectorDataSource) {
                    vLayers.add(currentLayer);
                }
            }
        }
        layerManager.removeAll(vLayers);
        vLayers.clear();`

**Comment by mtehver** [comment]
Thanks a lot for reporting this! I will include the fix in 4.3.0RC3, which I plan to release during weekend.

**Comment by phammanhdam** [comment]
> Thanks a lot for reporting this! I will include the fix in 4.3.0RC3, which I plan to release during weekend.

Thanks you, 👍
