### ISSUE TITLE
[android][FR] support TextureView

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#358]
following the discussion [here](https://github.com/CartoDB/mobile-sdk/issues/349) i think it would be good for Carto to also support rendering map in TextureView.

There are some benefits to this:
* animation, opacity support
* should remove black rendering in fragments
* i think we would get better rendering in listviews. Right now i am seeing some bad render effects.
* screenshot support

Mapbox did that by implementing renderers . By default they use GLSurfaceView but you can use an option to tell it to render to a TextureView

It is not as simple as i thought to implement. For The TextureView you need to have a thread which will handle the frame drawing. This is handled for you in GLSurfaceView

**Comment by mtehver** [comment]
Marking this with 'idea-maybe-future'. Makes a lot of sense.

**Comment by mtehver** [comment]
Closing the issue, I merged the PR into 4.4 branch. First RC supporting this is now released.
