### ISSUE TITLE
Get selected element for vector tile layer

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#360]
I am not sure if there is a way to select a element with the Vector Tile Layer. I tried many ways but couldn't get the full geometry of element. 
Do you have any ideas for this ?, thanks a lot.

![Screenshot_2020-05-03-21-57-43-918](https://user-images.githubusercontent.com/6292758/80917525-c007e400-8d89-11ea-89cc-82508a464570.jpg)

**Comment by mtehver** [comment]
Basically that is how vector layers work. Geometry is simplified and clipped.

For some elements there is an element id that can be used to 'stitch' the geometry together. For example, if geometry crosses tile boundary, a neighbor tile needs to be read and the geometries merged together. But this requires some assumptions (for example, does not work really with multigeometry) and that ids are present (for basemaps, they are present for some features, but not all). SDK does not provide any direct support for this, but it could be somewhat hacked if using `VectorTileSearchService` class.

**Comment by jaakla** [comment]
As Mark mentioned the vector tiles just dont have original geometry for polygons and lines. Data is modified and optimized for rendering. If you need it, you need to query from the original source: from OpenStreetMap database in case of basemaps, or if you have your own dataset, then you need to have copy of it in your server or app resources. With requesting data for complex polygons you may find that some of them area really very complex, some polygons have with millions of points, and even reading it can be too much for mobile. The most extreme sample is ocean - this is one big multi-gigabyte worldwide polygon with cannot be read unless you crop, split and simplify it for every zoom level, like vector tiles do. But if you deal only with relatively small polygons, e.g. buildings and do not care about simplification, then strategies of scanning through neighbour tiles may give good enough result.

**Comment by phammanhdam** [comment]
My current solution is to use a combination of multiple layers

Thank you so much,
