### ISSUE TITLE
how Change style or css of RasterLayer ? 

### ISSUE THREAD

**Issue by sedghian** [CartoDB/mobile-sdk#362]
hi . i use carto sdk mobile and want to change style or css of Layers by hardcode .
how do it ?
my code is :
`HTTPTileDataSource http = new HTTPTileDataSource(1,19,url);`
`RasterTileLayer wmsLayer = new RasterTileLayer(http);`
`mapView.getLayers().add(wmsLayer);`

Thank you for answer .

**Comment by sedghian** [comment]
@mtehver can you answer me ?
Thank you for help .

**Comment by mtehver** [comment]
`RasterTileLayer` styling is handled by the tile generator (thus server, if you are using `HTTPTileDataSource`). SDK simply displays the raster bitmap without applying any styling. So this is not really a SDK related question, it is about server setup. Thus closing this.
