### ISSUE TITLE
Cluster Freeze Issue

### ISSUE THREAD

**Issue by yfy238** [CartoDB/mobile-sdk#364]
Hi I am using Carto library in my Android project . I have 800 location data and if I use ClusteredVectorLayer my app freezing like hell and stop responding. I tried like 5 different phone and emulator but every device getting same result. If I dont use ClusteredVectorLayer but just VectorLayer than everything work perfectly and its not freeze  but I need to use cluster.What is this problem , can you help me ?
PS: I make bitmap and other things and I am doing same way with the docs .

**Comment by mtehver** [comment]
Which SDK version are you using? A small demo that demonstrates the freezing would be helpful, otherwise we are really in the dark.

**Comment by mtehver** [comment]
Closing the issue, it was not really SDK related. This has been solved through official CARTO support channel.
