### ISSUE TITLE
impossibility to render square/circle in line patterns

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#365]
Following the discussion from that issue https://github.com/CartoDB/mobile-sdk/issues/353 it is actually impossible right now to draw line patterns (like dash array) with non distorded squares or circles.
I am talking about rendering things like [this](https://tile.openstreetmap.org/17/67620/47048.png)

Now as it is right now in the SDK it seems impossible, however it does not seems impossible to implement as Mapbox managed to do it https://github.com/mapbox/mapbox-gl-native/issues/15930

**Comment by mtehver** [comment]
@farfromrefug From what I am seeing, MapBox SDK distorts squares/circles the same way. At least when I tested with squares in the MapBox Web client. Have you actually tested this?

**Comment by farfromrefug** [comment]
@mtehver seeing the issue i sent and the screenshots there i thought it was working.
But i have now tested on android and i confirm that you were right and there is distortion there too!
So i guess we can close this
