### ISSUE TITLE
CartoCSS Text Halo

### ISSUE THREAD

**Issue by lasyakoechlin** [CartoDB/mobile-sdk#370]
Hi there,

I am using Release 4.3.1.

I am trying to add a text halo but cannot seem to do so successfully. Below is a code snippet.

```
#text_labels {
	text-name: @name;
	text-orientation: [rotation];
	text-fill: @text_fill;
	text-face-name: @medium;
	text-size: linear([view::zoom], (17, 0), (19, 10), (21, 14));
	text_halo_fill: rgba(0,0,0,1);
	text_halo_radius: 10;
}
```

My expected text output is something like this (just in terms of having a halo around the text). But I'm not seeing one. Note that the text shows up fine, but it basically ignores the text_halo_fill and text_halo_radius.

Thanks for your help!

![image](https://user-images.githubusercontent.com/60749601/85048432-4cffd480-b161-11ea-8d66-5c0d27b6eb81.png)

**Comment by mtehver** [comment]
Hi. There are typos is the snippet above. Instead of `text_halo_fill` there should be `text-halo-fill`. The same with halo radius, it should be `text-halo-radius`. Both should work, though I am not sure about radius 10, the value should be normally between 0.5 and 2.5.

**Comment by lasyakoechlin** [comment]
Oh, that's silly! Thanks! I had set it to a larger value because I couldn't notice it, when it was smaller to try and see if it was working. Anyways, thanks!
