### ISSUE TITLE
CartoCss text-orientation

### ISSUE THREAD

**Issue by lasyakoechlin** [CartoDB/mobile-sdk#372]
Hi,

I am using Carto 4.3.1 and I have implemented CartoCss-based text rotation. Each `PointGeometry` has an associated `text-orientation`, which should "make sense" based on the polygon that it is in. You can see in the image below that the text follows a good "rotation" within the polygon but it occasionally flips 180 degrees in weird ways. Basically, it's as though there is a line which if the camera rotates beyond that, all text flips. 

Is there a way that I can get it so that the text is always human-readable, basically always facing the way the camera is regardless of the map rotation? But, I still want the text to fall alone the "line" defined by the "text-orientation".

For example in the image below,

"Seating" is on a nice line, and is facing the camera as you would expect.
"Showcase" is on a nice line, and is facing the camera as you would expect.
"Bell" is on a nice line, but is flipped away from the camera, which leads to a weird UI/UX.
...

Based on my testing in multiple buildings, the main thing that I am seeing is that how it behaves is highly dependent on the building orientation. I'm guessing the map has some reflection axis that it is using, and basically, I guess I want a way to be able to dynamically control that axis or something. Then, I can toggle the rotation axis on a per-building basis (or depending on whats on the screen) to ensure that the text is always readable.

Another thought that I had is maybe I need to  be pre-adjusting the `text-orientation` or `[rotation]` based on the buildings orientation itself. For example, if I know the building is orientated with it's axes as N-E, (e.g., North up), then maybe the calculated rotations are great. But if the building is "rotated" by say 75 degrees, maybe I need to find a formula to determine if each individual text label should be "flipped" 180 degrees. Any guidance on this would be ideal.

I am open to any suggestions. Thanks!

For reference, my CartoCss text labels are defined as follows. Note that the `[rotation]` is as described above. and the other `@field` are being supplied based on another file giving the styling/colour scheme.

```
#text_labels {
	text-name: @name;
	text-orientation: [rotation];
	text-fill: @text_fill;
	text-face-name: @medium;
	text-size: linear([view::zoom], (17, 0), (19, 10), (21, 14));
	text-halo-fill: @text_halo_fill;
	text-halo-radius: @text_halo_radius;
}
```

![image](https://user-images.githubusercontent.com/60749601/85138484-d8846e80-b210-11ea-8f24-c09d97997c87.png)

**Comment by mtehver** [comment]
Hi. Thanks for reporting this, it is a bug - the orientation is currently ignored when checking whether a text should be flipped or not. I have fixed this and the fix will be in 4.3.2. Can not give ETA for the release, likely mid to late Q3.

**Comment by mtehver** [comment]
4.3.2RC1 is now available and should fix the issue. Thanks again for reporting this.

**Comment by mtehver** [comment]
SDK 4.3.2 is now released that should fix the issue. Closing.
