### ISSUE TITLE
Building carto

### ISSUE THREAD

**Issue by AlirezaAsadi96** [CartoDB/mobile-sdk#374]
Hi
I build the carto sdk step by step and successfully done. Now what should I do?how can I use carto in android studio?

**Comment by mtehver** [comment]
Do you want to just use the SDK or actually modify it? If you just want to use it, take a look at the samples in [mobile-android-samples](https://github.com/CartoDB/mobile-android-samples) repo, there is no need to build the SDK at all. If you want to modify and debug the SDK, you should follow the instructions [here](https://github.com/CartoDB/mobile-sdk/tree/master/scripts/android-dev).

**Comment by AlirezaAsadi96** [comment]
Thanks for your answer. There is a problem when building project in android studio:
**error: no template named 'BoolArray' in namespace 'Swig'**

**Comment by mtehver** [comment]
Very difficult to suggest anything without knowing all the details. But my guess is the issue is related to wrong SWIG version. You really need to use the special modified SWIG version referred in the project README file.

**Comment by AlirezaAsadi96** [comment]
Thanks for your response. Yes It was related to SWIG version
