### ISSUE TITLE
[android] webp first load is really slow on android

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#380]
I realized recently that using webp makes the app hang for quite some time.

the [dev sample](https://github.com/CartoDB/mobile-sdk/tree/master/scripts/android-dev) actually shows the issue because it uses a mbtiles in webp format.
Switching to a png mbtiles fixes the issue.

To easily reproduce:
* set the visible range of the webp layer to something like 5/12
* initialize the map zoom to 13
* once loaded zoom out.
* the app will hang when trying to show the webp layer.

PS: i can send you the webp mbtiles.

**Comment by mtehver** [comment]
Strange, as loading the tiles should happen in background and should not hang the app in any way. The referenced sample project is not using mbtiles, so not sure how I can check this.

In general slow webp performance seems quite plausible, especially when the SDK is compiled in debug mode (from Android Studio, for example). Also, currently architecture-specific code paths (SSE/AVX/NEON) are disabled for webp, I will try to enable them.

**Comment by farfromrefug** [comment]
@mtehver sorry indeed in "your" version of the dev app i used http source for you to be able to use it.
I am using this :
```
 hillshadeSource =  new MBTilesTileDataSource("/storage/C0E5-1DEA/alpimaps_mbtiles/BDALTIV2_75M_rvb.etiles");
```
I can share that mbtiles if you want

**Comment by mtehver** [comment]
@farfromrefug Thanks, that makes sense. If you could share the mbtiles, it would be great.

**Comment by mtehver** [comment]
@farfromrefug I could not really reproduce the issue, at least in the sense that Webp based tiles cause hang/stuttering and Png based do not. Nevertheless, I found that Webp images were not using optimized code path (SIMD extensions) and I have now enabled this.

Perhaps the temporarily hanging is caused by 'on demand' shader loading and is dependent on actual device. This is something that can be improved by preloading shaders when MapView is initialized, but at the expense of startup time. So I am somewhat hesitant to implement this.

**Comment by farfromrefug** [comment]
@mtehver thanks for looking into this. The weird thing is that i can clearly see a difference when switching from png mbtiles to webp mbtiles.
right now i switched to png mbtiles (event if 30% bigger) and i dont see any hickup anymore...
I think i can say i am 99% sure it comes from webp initialisation. It even feels like a lib init. Are we using platform lib or do you include a webp implementation?

**Comment by mtehver** [comment]
@farfromrefug SDK uses its own set of image decoding libraries and does not rely on platform libraries. So lib-init causing this is possible, I have not really looked into Webp code.

Does this happen with 'release' build? By default the Android Studio dev project uses 'debug' build, which can be up to 10x slower than 'release'.

**Comment by farfromrefug** [comment]
@mtehver indeed i confirm it seems to happen only on some devices. I dont see it on the emulator. Only on my Samsung a3 2017. Must be something with the native webp lib.
And yes happens both in release and debug. 
I will try to find the time and update the lib. In fact all external libs are really old. Will try to update them all and see.

**Comment by farfromrefug** [comment]
@mtehver still facing the issue with latest SDKs and updated libs.
Not sure if it comes only from webp. Not sure if it comes only from init.
I am wondering if the issue is not with the hillshade raster layer instead.
let me explain:
* layer added but not visible => no issue very smooth
* i make the layer visible the hillshade webp mbtiles layer take some times to show up and it hangs the app a little
* when i zoom in to lower level i can also see hangs on zoom level change.
* after that no more hang, even if i zoom in and out in total different places where i did not zoom before.

I will share the mbtiles soon (2gb though)

**Comment by farfromrefug** [comment]
@mtehver here is the mbtiles with which i see the issue http://gofile.me/4pKGL/SYwYTHy5v

**Comment by mtehver** [comment]
@farfromrefug I checked the uploaded file. It seems there is no index for tiles. Thus the first call to `loadTile` takes initially 2 seconds on my phone. I suggest creating the index using this statement:

```
CREATE UNIQUE INDEX tiles_index ON tiles (zoom_level, tile_column, tile_row)
```

When decoding actual webp in the tile, there seems to be no delay.

Regarding the hanging when zooming in/out, I do not have a good explanation for this. Perhaps uploading normal maps as textures / building mipmaps causes this. After the textures have been uploaded and cached, subsequent zooming should work without hanging.

**Comment by farfromrefug** [comment]
@mtehver good catch thank you so much ! i generate my tiles with `https://github.com/mapbox/rio-rgbify` It misses that index! will change that thank you

**Comment by mtehver** [comment]
@farfromrefug Perhaps this issue can be closed now? It seems it was not about webp, instead it was related to missing index in .mbtiles file.

**Comment by farfromrefug** [comment]
@mtehver yes thanks!
