### ISSUE TITLE
Issue with displaying long labels in RTL languages

### ISSUE THREAD

**Issue by safe-bug** [CartoDB/mobile-sdk#381]
Hello
I have an issue with displaying long labels (2 lines) in RTL languages like Arabic, Persian, ... . You can find an example [in this screenshot](https://i.imgur.com/2eHN5Zb.jpg) that the order of displaying words is not correct when the label gets too long (when it should be displayed in two lines). The correct form is to put the second line words at the start of first line and then other words join it.

How can I fix it?

**Comment by mtehver** [comment]
Hi. Thanks for reporting this. If you are willing to look into this yourself, the relevant text splitting code is in libs-carto/vt/src/vt/TextFormatter.cpp. The code is not very straightforward as it depends on both bidi (Unicode bidirectional handling library) and harfbuzz (Unicode shaping library). My guess is that the word counting/splitting code is not correct for RTL languages, but I have really no idea how to fix this as I do not understand Arabic formatting rules.

**Comment by mtehver** [comment]
@safe-bug I pushed a fix for this, it seems to work for Arabic-only texts. For mixed texts, it simply ignores wrapping and displays everything as a single long line. It will be available in 4.3.2RC2.

**Comment by safe-bug** [comment]
@mtehver Thanks so much!

**Comment by mtehver** [comment]
@safe-bug 4.3.2RC2 is now released. Can you confirm that RTL texts are now displayed correctly?

**Comment by safe-bug** [comment]
@mtehver I've tested the RC2 release and yes they are displayed correctly! Thanks

**Comment by mtehver** [comment]
4.3.2 is now released, closing this.
