### ISSUE TITLE
How to set Expiration Time for PersistentCacheTileDataSource

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#384]
Hello, 
I'm using PersistentCacheTileDataSource for my project, I checked the cache database that has an **expirationTime** field, all values equal 0.
How to set Expiration Time for Cache Tile by SDK API. Thanks you so much.

![image](https://user-images.githubusercontent.com/6292758/93169343-1a10b100-f74f-11ea-8f5f-492584b5dc21.png)

![image](https://user-images.githubusercontent.com/6292758/93169661-c2bf1080-f74f-11ea-82f4-28b9724676fd.png)

**Comment by mtehver** [comment]
Hi. If you are using online tiles, then the expiration date is read from HTTP headers. There is no API in PersistentCacheTileDataSource to override this.

**Comment by phammanhdam** [comment]
many thanks @mtehver
