### ISSUE TITLE
Persistent Cache Max Capacity Size

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#385]
I am not sure about this problem. When my Persistent Cache layer data is more than 400Mb has a error **_"Failed to query tile set from the database: disk I/O error"_**. I has setCapacity = 1Gb

Could you help me with a solution, thanks you so much.

![image](https://user-images.githubusercontent.com/6292758/93567056-38c5b080-f9b8-11ea-8e83-d4ebe71b2e39.png)

**Comment by mtehver** [comment]
I did a quick test with 1GB persistent tile cache on my device and everything works as expected. Any chance the storage is simply full on your device?

**Comment by phammanhdam** [comment]
@mtehver, thank for reply.
I have checked the device's storage, no problem. You can check with my file attach and turn off the internet (Wifi, 3G) there will be an error. 
Many thank,
[Cache file demo](https://www.dropbox.com/s/j3bly4i89nxiepn/GoogleHybird.db?dl=0)

**Comment by mtehver** [comment]
@phammanhdam Thanks for the file, it really helped. Turned out that the issue was related to SQLite query cache size which SDK set to a minimal value. For small databases this worked, but caused issues for large databases. I will include the fix in SDK 4.3.2, which I plan to release this week.

**Comment by phammanhdam** [comment]
@mtehver , that's great, thank you so much. 👍👍👍

**Comment by mtehver** [comment]
4.3.2 is now released, closing this.

**Comment by phammanhdam** [comment]
@mtehver , Thanks for your support

I have tried with version 4.3.2. It worked with files larger than 400Mb,
However, when I try with file larger than 600Mb it again error occurs with access cache data with PersistentCacheTileDataSource

I tried file larger than 1Gb with MBTilesTileDataSource, it works great. 
I think, the same is to use Sqlite but maybe PersistentCacheDataSource has something different than MBTilesTileDataSource.

You can test with cache file here. Hope you can fix it soon. Many thanks.
[Download cache file 628Mb (Dropbox link)](https://www.dropbox.com/s/i9ggt24uv1dj2hx/GoogleHybird_628Mb.db?dl=0)

**Comment by mtehver** [comment]
@phammanhdam Thanks, I reproduced the issue and fixed it. It was basically the same issue that happened with previous database file, in this case it turned out to be that default sqlite cache size is not big enough for a specific query that utilizes SQL-level sorting. I will include the fix in the next release, but it is unlikely to be out anytime soon.

**Comment by mtehver** [comment]
@phammanhdam I published 4.3.3RC1 today that includes the fix.

**Comment by phammanhdam** [comment]
@mtehver , I tested it, it worked, great.  thank you very much 👍
