### ISSUE TITLE
[FR] encode/decode methods for MapPosVector

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#392]
I am in the need of encoding/decoding `MapPosVector` to store them in a DB.

The code is already there in the sdk. Would be nice to have it as "part of the core" so that it could get accessible to iOS/Android
https://github.com/CartoDB/mobile-sdk/blob/master/all/native/routing/ValhallaRoutingProxy.cpp#L130

**Comment by mtehver** [comment]
The referred code makes lots of assumptions and can not be used for generic serialization: it assumes WGS84 coordinates and clamps precision quite heavily. I suggest doing it at application level, as when done at SDK, we would need at least 8 bytes per coordinate, not 3.

**Comment by farfromrefug** [comment]
@mtehver i see that implementation is not good.
I made one here for carto https://github.com/nativescript-community/ui-carto/blob/master/plugin/platforms/android/java/com/akylas/carto/additions/Utils.java#L11
I think it would be good to have it in the core for everyone to be able to use it.
It gets useful to store long routes in DBs.

I also implemented there [distanceToEnd](https://github.com/nativescript-community/ui-carto/blob/master/plugin/platforms/android/java/com/akylas/carto/additions/Utils.java#L182) and [isLocationOnPath](https://github.com/nativescript-community/ui-carto/blob/master/plugin/platforms/android/java/com/akylas/carto/additions/Utils.java#L240)
Those are very useful for navigation. I think everyone would benefit from such functions in the core

**Comment by mtehver** [comment]
SDK already contains WKT, WKB, GeoJSON serializers for geometry classes. It is easy to convert `MapPosVector` to `LineGeometry` and use the existing serializers. I do not see any need to add a non-standard serialization.

**Comment by farfromrefug** [comment]
@mtehver do you have an example somewhere of that? very interested

**Comment by mtehver** [comment]
These Java snippets should do it:

```
        String serialized = new GeoJSONGeometryWriter().writeGeometry(new LineGeometry(mapPoses));
```

```
        MapPosVector mapPoses = ((LineGeometry) (new GeoJSONGeometryReader().readGeometry(serialized))).getPoses(); 
```

Note that you could also use `WKTGeometryWriter`/`WKTGeometryReader` instead.

**Comment by farfromrefug** [comment]
@mtehver thanks. should we close this issue? what do you think about the path methods to get distance and "on path"?

**Comment by mtehver** [comment]
Let's close this issue. Regarding the other methods - 'on path' seems too specific. 'get distance' is already implemented in 'GeomUtils' class (but only as a planar approximation, not geodesic approximation), but not currently exposed as part of the API. I will think about it a bit, it could be a good idea to expose this with bunch of other 'distance' methods (and generalize the methods to support geodesic approximation in addition to planar approximation).

**Comment by farfromrefug** [comment]
@mtehver actually yes i think GeomUtils shoudl be exposed. 
Why on path is too specific? If the framework gives routing instructions at one point you will need that method. A navigation app cant work without such a method

**Comment by mtehver** [comment]
If I am not mistaken, then 'isOnPath' can be implemented simply as 'getDistance(...) < tolerance'? In fact, I think it would be more useful to implement 'findClosestLinePoint' method, as distance can be calculated between the original and the closest point.

**Comment by farfromrefug** [comment]
@mtehver actually is `isOnPath` return the closest index in the path. So it is more `findClosestLinePoint` with a torelance to return nothing if not on path. So you do both in the same method => faster.
