### ISSUE TITLE
onVectorElementClicked is fired on iPhone simulator but doesn't work on real device

### ISSUE THREAD

**Issue by andretmn** [CartoDB/mobile-sdk#393]
Hi there! I have a listener which is assigned to a clustered layer. But the onVectorElementClicked event is fired on iPhone simulator but doesn't work on real device. 

Here is the listener.

class MarkersListener : NTVectorElementEventListener {
    private var view: VehiclesMapController!
    
    override init!(cptr: UnsafeMutableRawPointer!, swigOwnCObject ownCObject: Bool) {
        super.init(cptr: cptr, swigOwnCObject: ownCObject)
    }
    
    init(_ view: VehiclesMapController) {
        super.init()
        self.view = view
    }
    
    public override func onVectorElementClicked(_ clickInfo: NTVectorElementClickInfo?) -> Bool {
        print("--MarkersListener::onVectorElementClicked")
        if let element = clickInfo?.getVectorElement() {
            if element.containsMetaDataKey(MapEvents.CLICK_VEHICLE) {
                if let string = element.getMetaDataElement(MapEvents.CLICK_VEHICLE).getString() {
                    DispatchQueue.main.async {
                        self.view.setVehicle(VehicleModel(json: JSON(parseJSON: string)), true)
                    }
                }
            } else if let position = clickInfo?.getClickPos() {
                view.vehiclesMap.focusOn(position, 2.0)
            }
        }
        
        return false
    }
}

How can be solved? Thanks

**Comment by mtehver** [comment]
Could you share a small test demonstrating the issue? Our own AdvancedMap project includes a similar listener in a sample and it seems to work fine.

**Comment by andretmn** [comment]
Hi. I have uploaded a demonstration on youtube. here is the link: https://youtu.be/rjwJTTIu9DQ

**Comment by mtehver** [comment]
Thanks for the video. I got the sample code from our customer support, though I could not reproduce the issue on actual iPad. One thing I noticed: the sample uses `NTEditableVectorLayer` class, though this is intended only for use cases where user can move actual geometry or markers around. As a first idea, I would suggest trying replacing it with `NTVectorLayer`, if interaction is not needed.

**Comment by mtehver** [comment]
4.3.3RC2 is now published and should fix this. This should have been discovered a while ago, but as you described, simulators behave differently vs devices in this case and we did not have any 'plus' devices among our test devices. Thanks for reporting this.

**Comment by andretmn** [comment]
The issue seems to be solved. Thank you very much.
