### ISSUE TITLE
Wrong long press events are fired

### ISSUE THREAD

**Issue by safe-bug** [CartoDB/mobile-sdk#394]
Hello
We have an issue with using the Map SDK, sometimes when we want to move on map, a long press event is fired and it keeps on long pressing when moving. The only way out is to completely close the app and reopen it.

I couldn't find any pattern for creating the issue, it happens randomly on random devices, do you have any idea how can I find the actual cause of the issue and how to fix it?

Thanks

**Comment by mtehver** [comment]
Hi. SDK will fire a click event when you touch the screen for a second without moving the finger. The event should be fired exactly once. If I understand correctly, in some cases you will receive additional events even when you are moving the finger, correct? I will try to investigate this.

**Comment by safe-bug** [comment]
@mtehver yes, exactly

**Comment by farfromrefug** [comment]
@mtehver i am seeing something similar. For me it usually starts after i see a hickup in the map. I mean it happens after i see the map doing a lot of work (like loading my hillshading rgb tiles).

**Comment by safe-bug** [comment]
@mtehver I've added some markers with quite large icons to one of my layers, and the rate of wrong long presses has increased a lot! Maybe this helps for debugging.

**Comment by mtehver** [comment]
@safe-bug Thanks for the info. Any other tips? You are using latest Android build, correct? I have tried to reproduce this, but with no success so far.

**Comment by safe-bug** [comment]
@mtehver I found one case that reproduces this bug on Carto Advanced Map Sample App all the time. When I want to capture a screenshot with android 3 finger gesture this issue shows up and when I single touch on the map it recognize it as long press events. [This is the link](https://imgur.com/a/UspEn1p) to a screen capture I've taken from Carto sample app.

**Comment by mtehver** [comment]
@safe-bug Thanks. Unfortunately three finger gestures are not available on my test phones, nor on emulator. Which phone/Android version are you using?

**Comment by safe-bug** [comment]
@mtehver I'm using OnePlus 5T with android 10

**Comment by mtehver** [comment]
@safe-bug Thanks, that was really helpful! Got myself another OnePlus phone that supported the same 3-finger screenshot gesture. Tracked it down, the fix is now pushed and I plan to release 4.3.5RC1 late this week or early next week.

**Comment by safe-bug** [comment]
@mtehver That's great! Thank you very much.

**Comment by mtehver** [comment]
Closing the issue, it was fixed in 4.3.5 release.
