### ISSUE TITLE
[ios]Options.setWatermarkScale not working

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#395]
`setWatermarkScale` does not seem to have any effect on iOS. However it works fine on Android.
BTW just to make sure, some clients are asking us to remove the carto logo. That s ok if we dont use any license? 
I prefer to keep it, but this time the clients asks for it, want to make sure it is ok with you.

**Comment by mtehver** [comment]
I did a quick test with SDK 4.3.3: `[[mapView getOptions] setWatermarkScale:0]` works as expected.

We do not have a strict rule about displaying/removing CARTO watermark. In general we expect clients to show them when they use CARTO online services. If you connect SDK to you own server, we have no problem if you want to remove it.

**Comment by mtehver** [comment]
Closing the issue, it was fixed in 4.3.4 release.
