### ISSUE TITLE
Support line offset

### ISSUE THREAD

**Issue by mnameghi** [CartoDB/mobile-sdk#396]
Hello

I need to add offset to some lines with style and this could be achieved with Mapnik line-offset but it's not supported in Carto sdk. Is it possible to add this feature?

Thanks

**Comment by mtehver** [comment]
Marking this with 'idea-maybe-future'. Unlikely to be implement in near future, though.

**Comment by mtehver** [comment]
Implemented in SDK 4.4.1.
