### ISSUE TITLE
[iOS] Hiding the map while it's still rendering or loading tiles makes the app crash

### ISSUE THREAD

**Issue by MatteoColombo** [CartoDB/mobile-sdk#398]
Hi,
I'm using the library in an iOS application with Xamarin Forms and a custom renderer to display the map.
I noticed that if I hide the map when it's still doing some background work (I presume tile loading from an HTTP source), the application crashes with the following error:

`System.ObjectDisposedException: 'Cannot access a disposed object.`

After some investigations I found out that if I override the Dispose method of the renderer or if I delay its execution to when the map is already in a "stable" condition and all the tiles are loaded it doesn't crash.

I tried to unsubscribe from all the events, to remove all the layers from the map and to cancel the tasks, but the app still crashes. 
I there any way in which I can stop the rendering phase or cancel the ongoing tasks?

I attached the console output 
[out.txt](https://github.com/CartoDB/mobile-sdk/files/5635521/out.txt)

**Comment by mtehver** [comment]
Hi.  Based on the description it is hard to understand how hiding a map is related to disposing anything, so I am a bit stuck here. Could you make a small example of this behavior so we could test it ourselves? I have very little experience with Xamarin Forms, so having a sample could help a lot.

**Comment by MatteoColombo** [comment]
Hi,
I attached an example with both Android and iOS.
On Android everything is fine, while on iOS it crashes. 

I created a MapControl class in the shared project and a MapControlRenderer class in both the Android and iOS projects.
The custom renderers instantiate a new MapView and add 10 raster layers as a sample (so that the loading time is longer).
As soon as the MainPage.xaml is appearing I remove the MapControl from the UI so that the view is destroyed and the Dispose method in the renderer is called. On Android this works fine, while on iOS the app crashes.


[Example.zip](https://github.com/CartoDB/mobile-sdk/files/5654364/Example.zip)

**Comment by mtehver** [comment]
Thanks! The example was very helpful and I have now fixed the issue. The fix will be in the next release, but I can not give ETA for it. 

A temporary hack that can be used to suppress the crash is to create a subclass of `MapView` and override its `Dispose` method so that the method is simply empty (and does not call baseclass `Dispose`).

**Comment by mtehver** [comment]
A small update - I have uploaded a hot fix version of 4.3.3 release here: https://drive.google.com/file/d/1e-6la89KIz6wempFMOKw5GqgoX-EcvU-/view?usp=sharing

So you can download it and use it as a local package, instead of the official nuget.org package.

**Comment by mtehver** [comment]
Closing, this was fixed a while ago (4.3.4 release).
