### ISSUE TITLE
Crash iOS issue when using Carto Mobile SDK with Cloudflare Mobile SDK

### ISSUE THREAD

**Issue by rumitspkt** [CartoDB/mobile-sdk#400]
Hi Team, i got a weird crash when using Cloudflare Mobile SDK with Carto Mobile SDK

About Cloudflare Mobile SDK: This is a library help us analyst all network request from app. I known that under the hoods, our map loads tiles item (static file) from network, maybe Cloudflare can detect it.

Version Cloudflare Mobile SDK: 5.0.0.2: https://github.com/CocoaPods/Specs/tree/master/Specs/6/9/b/CloudflareMobileSDK/5.0.0.2

Reproduce crash: Open Map screen, move map (load tile) and crash.

Device: Only iOS < 14. (iOS >= 14 and Simulator work fine).

It is weird that when I check Firebase Crashlytics, crash log only appears in another library in app:
![with soha](https://user-images.githubusercontent.com/24636165/101315937-21e37b80-388e-11eb-9ad2-99203cb060f6.png)

I remove this library from log, I got another crash log from another library again:
![remove soha](https://user-images.githubusercontent.com/24636165/101315996-3aec2c80-388e-11eb-81a7-1feb1dfa0c4e.png)

After all, I remove all library that I got crash log:
![remove all](https://user-images.githubusercontent.com/24636165/101316012-42abd100-388e-11eb-800c-816d1acb66f4.png)

One more thing, I downgrade to 3.1.1.2 Cloudflare Mobile SDK. No crash occurs.
https://github.com/CocoaPods/Specs/tree/master/Specs/6/9/b/CloudflareMobileSDK/3.1.1.2

I know this problem come from Cloudflare Team, but if someone had this problem, please give me an advise. Many thanks.

**Comment by mtehver** [comment]
Looking at the log, it seems that all crashes come from Cloudflare SDK. So I suggest making a small demo app and then send the app to Cloudflare directly.

**Comment by rumitspkt** [comment]
Funny enough. Cloudflare just deprecated Mobile SDK
https://support.cloudflare.com/hc/en-us/articles/360054452251
