### ISSUE TITLE
rendering errors with layer opacity < 1

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#404]
When i play with layer opacities i see some rendering errors.
It seems like polygons bigger than the visible "zone" are getting unwanted edges creating the behavior seen in the video

https://user-images.githubusercontent.com/655344/102756408-291b8680-4370-11eb-8857-a77d83459e7c.mp4

**Comment by mtehver** [comment]
Interesting. Is this about CartoCSS layer opacity or SDK `Layer` opacity? Based on the issue title, the artifacts appear only when you set opacity to negative value, is this correct?

**Comment by farfromrefug** [comment]
@mtehver i am talking about SDK layer opacity. And sorry < 0 was meant to be < 1.

**Comment by phammanhdam** [comment]
I also had the same problem with mbtiles vector

**Comment by mtehver** [comment]
This should be now fixed, the fix is in the master branch. In certain cases the offscreen rendering buffer was created without stencil attachment, causing parts of neighboring tiles to 'leak'. Good find and thanks for reporting it.

**Comment by farfromrefug** [comment]
@mtehver i can confirm it is fixed

**Comment by mtehver** [comment]
Closing the issue, fix was included in 4.3.4 release.
