### ISSUE TITLE
[FR]: way to disable Map background for VectorTileLayer

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#408]
I want to have something like that
* VectorTileLayer A: world for zoom 0-6 (MBTiles )
* VectorTileLayer B: France for zoom 0-22 (MBTiles following the .poly of France so not "square")

I want both layers to use the same Style/ Decoder. The issue is that if i set a Map `background-color`  for the style i will have some tiles where A should be used but some "empty" tiles are found in B and thus B is drawn with a background so i dont see A data.
So i need a way to say that i only want A to draw a background. Could we get a `Layer` parameter to disable background drawing?
![Screenshot_1609509529](https://user-images.githubusercontent.com/655344/103439952-f14ef180-4c41-11eb-9f6a-4699606afa0c.png)
![Screenshot_1609509549](https://user-images.githubusercontent.com/655344/103439956-04fa5800-4c42-11eb-8080-c39becff3fe7.png)

**Comment by erdemuysal** [comment]
I'm not sure I got it right, but you can change the background bitmap of the map using the `setBackgroundBitmap` method in options. Please tell me if I got it wrong.

**Comment by farfromrefug** [comment]
It  won't override the style background color. I don't want 2 different styles. So I need a way to disable it
