### ISSUE TITLE
How can render map for client application ?

### ISSUE THREAD

**Issue by DavisMillier** [CartoDB/mobile-sdk#409]
Hello
I need to find a way to render data on postgis database (OSM data) , and use the tile in local application write by C# or Qt ?
i need to know how can i do that ? is any library exist for this ? i was read some document in mapnik , mapbox and other library but there work for web app.may some one help me whats should i do ?

**Comment by mtehver** [comment]
CARTO Mobile SDK can be used for this, but it is not 'out of the box' solution for this. Depending on your target platform, I suggest looking at the sample projects: 

* https://github.com/CartoDB/mobile-android-samples
* https://github.com/CartoDB/mobile-ios-samples

**Comment by mtehver** [comment]
Closing the issue due to inactivity.
