### ISSUE TITLE
findFeatures blocking main thread

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#411]
I am trying to use [findFeatures](http://cartodb.github.io/mobile-android-samples/reference/com/carto/search/VectorTileSearchService.html#findFeatures(com.carto.search.SearchRequest)) in a thread but it is still blocking the main thread.
Is that normal ? Maybe `loadTile` is ran on the main thread?

**Comment by mtehver** [comment]
Correct, if the search service instance uses online datasource, then `findFeature` will perform IO operation in the calling thread. In that case `findFeature` should be called from a background thread. I will add a comment about this to the API documentation.

**Comment by farfromrefug** [comment]
@mtehver ok so no way to make it run in a background thread? I am using a Mbtiles datasource.

**Comment by mtehver** [comment]
The API is synchronous, but the call may take arbitrary amount of time. So that is up to the app to create a background thread and run it in the thread.

**Comment by farfromrefug** [comment]
@mtehver that s what i did ! I created a thread in java and ran it there. Need to investigate this then

**Comment by farfromrefug** [comment]
@mtehver thanks for confirming it should be working. Found the issue on my side.
