### ISSUE TITLE
cartocss: compare string with number

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#413]
I want to do something like that in my css:
```
[osmid = 'nuti::selected_id'] {
	line-width: 4;
}
```
The issue is that `osmid` is a number from vector tiles. But as i want to pass `selected_id` from Java side it has to be a string because `setStyleParameter` only accepts strings. So when i do that comparaison in mss it cant work because i compare a string to a int.
It there a way to achieve that test within mss?
Or maybe there is a way to pass a number to a nuti parameter?

**Comment by mtehver** [comment]
Here `'nuti::selected_id'` is simply a value the `osmid` is compared to. You can not do comparison between two variables/parameters in CartoCSS filter. You can do the following, though:

```
line-width: [osmid] == [nuti::selected_id] ? 4 : 3;
```

Regarding `setStyleParameter`, you can convert your id to string and use this method. Nutiparameters are typed and after calling the method, it will be internally converted to integer, assuming you have declared it as integer in your style .json file in 'nutiparameters' section.

**Comment by farfromrefug** [comment]
@mtehver ok did not know about the auto conversion! It works with 
```
line-width: [osmid] = [nuti::selected_id] ? 4 : 3;
```
(== is a parse error)
But can i use it as a "scope" rule?
I need to do something like this but ti does not seem to work ( though this `['nuti::routes'>0]` or this `[class=biking]` works) 
```
[osmid = 'nuti::selected_id'] {
    line-width: 4;
}
```

**Comment by mtehver** [comment]
No, not possible to use as a scope rule. Scope rules in CartoCSS have form

```
[VAR OP VALUE] {
  ...
}
```

so `[class=biking]` and `[biking=class]` are two different things and not interchangable.

**Comment by farfromrefug** [comment]
@mtehver i understand good to know and good that it is written here so that anyone can "find" it

**Comment by farfromrefug** [comment]
@mtehver sorry to bump this. But i iam in a situation where i would like to do:
```
[zoom>='nuti::motorway_casing_start_zoom'] {}
```

any chance we could have this working?

**Comment by mtehver** [comment]
@farfromrefug The syntax for `[]` filter can not be extended without breaking backward compatibility. But you can use `when` clause instead, though be careful as it disables rule optimizations. The following should work:

```
when ([zoom] >= [nuti::motorway_casing_start_zoom]) {}
```

**Comment by farfromrefug** [comment]
@mtehver you are right when! Would it make the style much slower? The idea beind this is for different style to define at which level casing appears. The reason for the test is that casing can be really slow at low zoom level (lots of motorway/trunk roads) so letting the style define this would be awesome.
It is also a global way to customize everything in styles (like differences between streets, dark, outdoor,... while having the same shared files)

**Comment by mtehver** [comment]
@farfromrefug Regarding performance, it really depends on the style. I suggest doing some tests by compiling the styles to XML and checking the resulting sizes/contents. It should give an idea.

Regarding backward compatibility. It is briefly described above, but as an example all the following declarations are equivalent:

```
[class='street'] { }
[class=street] { }
['class'='street'] { }
['class'=street] { }
```

This is due to the syntax of `=` operator in `[]` filter always referring to the first argument as a variable (field) and the second argument as a constant. It was specced this way before SDK started to support CartoCSS and we need to support this.

**Comment by farfromrefug** [comment]
@mtehver ok i see. Maybe a dumb idea but what about add support for this `[[zoom]>= [nuti::motorway_casing_start_zoom]] { }`
Using the `[]` could help differentiate things?

**Comment by farfromrefug** [comment]
@mtehver and `when` vs what i proposed induce the same perfs? If so you are 100% right and i am ok with this

**Comment by farfromrefug** [comment]
@mtehver sorry about keeping on on this. Found another issue with the use of `when` in this case.
my style is like this:
```
[class=motorway][zoom>=11]::casing,
[class=motorway][zoom>=5][zoom<11]::casingLowZoom2, 
[class=motorway][brunnel=bridge][zoom>=15]::bridge{
    line-width: @motorway-width + @motorway-casing-width;
    [ramp=1] {
	    line-width: @motorway-link-width + @motorway-casing-width;
    }
    line-color: @motorway-casing;
    line-join: round;
    line-cap: round;
...
```
And i want the second line to change to this `[class=motorway][zoom>=[nuti::motorway_casing_start_zoom]][zoom<11]::casingLowZoom2, ` 
using when makes it impossible to have that factored code. I would need to duplicate the thing for the when case.
Not the worse but another case where being able to compare would be great

**Comment by mtehver** [comment]
@farfromrefug Can you be more specific? Any issues with the following declaration?

```
[class=motorway] [zoom<11] when([zoom] >= [nuti::motorway_casing_start_zoom])::casingLowZoom2
```
