### ISSUE TITLE
MoveToFitBounds doesn't work when map is initializing on iOS

### ISSUE THREAD

**Issue by MatteoColombo** [CartoDB/mobile-sdk#416]
Hello, I need to use the MoveToFitBounds function, but I noticed that the first time I use it, when the Map View is still initializing, it doesn't work and it logs that Screen Size is unknown. I tried to call the LayoutSubviews method as suggested in another issue but without success.
Is there any workaround for this?  Is there any way to check if Screen Size is set or to set it manually? Is there any way to subscribe to Screen Size with a callback?
Also I noticed that if I set the animation time to a "big" value (like 2-3 seconds) it usually works, but I'd rather set it to 0 and have no animation.

**Comment by MatteoColombo** [comment]
Nevermind, I found a solution. I was calling LayoutSubviews too early.
This solved the issue:
`                       Control.Frame = new CGRect(0, 0, Element.Width, Element.Height);
                        Control.LayoutSubviews();`

I'm using Xamarin Forms with a custom renderer, the Control is the MapView object and Element is the Xamarin component. I just have to make sure that Element.Width and Element.Height are set before calling setting the frame and calling LayoutSubviews.

**Comment by mtehver** [comment]
Correct, this is a known issue. `MoveToFitBound` (and `ScreenToMap`, `MapToScreen`) generally require view size to be known. Depending how initialization is done, this may not be the case. 

There is currently no SDK API to check that, nor callback that can be used for this. But this seems like a good idea, so I think we can add a callback to `MapEventListener` for this.

**Comment by mtehver** [comment]
Closing the issue, `onSurfaceChanged` method was added to `MapRenderListener` in SDK 4.3.4. The event is fired immediately after surface size is determined.
