### ISSUE TITLE
Callback when user interacts with the map

### ISSUE THREAD

**Issue by MatteoColombo** [CartoDB/mobile-sdk#417]
Hi, is there any way to know when the user interacts with the map and to understand which type of interactions he performs?
I know that there is the MapEventListener, but its OnMapMoved callback is called whenever the map focus changes, while I'm only interested in catching user interactions like panning, rotations and pinch to zoom.

**Comment by mtehver** [comment]
SDK 4.4.0RC1 now has `onMapInteraction` method in `MapEventListener`, that can be used to detect interaction types.

**Comment by mtehver** [comment]
Closing, as 4.4.0 is released now.
