### ISSUE TITLE
Callback event for mapView functions

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#418]
I don't find the API that allows to use event callback for functions like

`mapView.setFocusPos(mapPos, 1.0f);
mapView.setZoom(zoom, 1.0f);
mapView.moveToFitBounds(...)`

Can you add an API for this? That is really necessary for my application.
Thank you so much

**Comment by mtehver** [comment]
Sorry, the question is not very clear. Is this a duplicate of https://github.com/CartoDB/mobile-sdk/issues/417 perhaps?

**Comment by phammanhdam** [comment]
> Sorry, the question is not very clear. Is this a duplicate of #417 perhaps?

Exactly I mean the same.  I will close this issue and follow up with that question.

Thanks you 👍
