### ISSUE TITLE
3D NML Model Size

### ISSUE THREAD

**Issue by mastermobin** [CartoDB/mobile-sdk#419]
I wanted to use a 3D model as a marker for my application, so I found a problem with the size of that. The problem is the ratio of 3D model size to the world is constant, but I need an option to make the ratio of 3D model size to the screen constant, just like a simple marker.

Thank you

**Comment by mtehver** [comment]
You can do that by registering a custom `MapRendererListener` and updating the scale of your model in `onBeforeDrawFrame` callback. Something like this:

```
mapView.getMapRenderer().setMapRendererListener(new MapRendererListener() {
   @Override
   void onBeforeDrawFrame() {
     float scale = math.pow(2.0f, mapView.getZoom() - MODEL_ZOOM);
     if (nmlModel.getScale() != scale) {
       nmlModel.setScale(scale);
     }
  }
});
```

**Comment by mastermobin** [comment]
I did something like this that actually, but I think it could be much more efficient if we could change MVP matrix.
Also, I am wondering if the way you commented hasn't any performance issues.

**Comment by binu8051** [comment]
@mastermobin can you post the solution?

**Comment by mtehver** [comment]
@binu8051 This will be implemented in SDK 4.4.0. First RC of 4.4.0 should be released in a week or two.

**Comment by binu8051** [comment]
Thanks

**Comment by mtehver** [comment]
This is now available in SDK 4.4.0RC1. Scaling and orientation modes can be set when setting up model style in `NMLModelStyleBuilder` instance.

**Comment by binu8051** [comment]
Hi, How to set the ratio of 3D model size to the world in the new version SDK 4.4.0RC1.

**Comment by mtehver** [comment]
@binu8051 It works the same way as with bitmap markers. Something like this in Java:

```
NMLModelStyleBuilder builder = new NMLModelStyleBuilder();
// If you want to use auto-orientation
builder.setOrientationMode(BILLBOARD_ORIENTATION_FACE_CAMERA); // or BILLBOARD_ORIENTATION_FACE_CAMERA_GROUND
// If you want to use auto-saling
builder.setScalingMode(BILLBOARD_SCALING_SCREEN_SIZE); // or BILLBOARD_SCALING_CONST_SCREEN_SIZE
```

**Comment by binu8051** [comment]
Thanks, it worked

**Comment by mtehver** [comment]
Closing, as 4.4.0 is released now.
