### ISSUE TITLE
Vector element do not render when zoom = 24

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#420]
I have tested and have problems, vector element do not render when zoom = 24

I'm not sure if this is an sdk (v4.3.3) bug or not, please check it. Thanks you

**Comment by mtehver** [comment]
This can happen if you do `layer.setVisibleZoomRange(new ZoomRange(0, 24))` in your code, for example. Note that the 'visible zoom range' is half-open range, meaning the layer will be visible when 0 <= zoom < 24. If that is the case, then this is not a bug.

**Comment by phammanhdam** [comment]
@mtehver , I solved the problem with suggestions from you.  thank you
