### ISSUE TITLE
How to render mapbox vector pbf file

### ISSUE THREAD

**Issue by ShikinChen** [CartoDB/mobile-sdk#425]
I can load mapbox vector pbf file,but Carto CSS Style can not render,map is white

**Comment by mtehver** [comment]
Hi. Most likely the contents of your vector tiles do not match your CartoCSS style. If you are trying to use tiles from MapBox server with CARTO Mobile SDK built-in styles, then this is not supposed to work, as the built-in styles assume OpenMapTiles tile structure, which is different from the MapBox tile structure. If you want to use original MapBox tiles, then you need to write your own CartoCSS, which is quite a lot of work.
