### ISSUE TITLE
Exception while decoding: unknown pbf type

### ISSUE THREAD

**Issue by phammanhdam** [CartoDB/mobile-sdk#431]
I have a problem with SDK v4.4.0-rc1 when using VectorTileLayer with GeoJSONVectorTileDataSource. This doesn't happen with older version like v4.3.5

`E/carto-mobile-sdk: MBVectorTileDecoder::decodeTile: Exception while decoding: unknown pbf type
E/carto-mobile-sdk: VectorTileLayer::FetchTask: Failed to decode tile`

<img width="1134" alt="Screen Shot 2021-06-07 at 22 23 05" src="https://user-images.githubusercontent.com/6292758/121043964-51dcee80-c7df-11eb-8b0b-dabe08d270b8.png">

**Comment by mtehver** [comment]
Thanks for reporting this, good catch. This will be fixed in 4.4.0RC2.

**Comment by mtehver** [comment]
@phammanhdam SDK 4.4.0RC2 is now released, the fix is in this release. Thanks again for reporting this.

**Comment by phammanhdam** [comment]
Thanks you, i have test, it's works
