### ISSUE TITLE
4.4.0 RC1 regressions

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#432]
I am testing 4.4.0 RC1. Globally amazing :D 
Just found a few issues

* First there is some unwanted animations while zooming out. As you can see in the video the roads is shortly showing only the outline and not the road fill are not animated the same way. I am not sure what s happing so i attach the style.
[osm.zip](https://github.com/CartoDB/mobile-sdk/files/6623956/osm.zip)

https://user-images.githubusercontent.com/655344/121360295-9037f200-c934-11eb-9eab-605137a5791c.mp4

* changing a style parameter is much much slower than before. It happens with any prop like enabling / disabling buildings. On my phone it usually takes around 3s

**Comment by mtehver** [comment]
Great feedback, thanks! I have reproduced the style parameter changing issue, will fix this in RC2.

Regarding the unwanted style animations: SDK 4.4.0 now applies transition animations for appearing/disappearing vector tile layers automatically. Perhaps this is unwanted in some cases and should be disabled. Will look into this.

**Comment by farfromrefug** [comment]
@mtehver your latest commits fixed the issue with style parameter change!! Thank you

**Comment by mtehver** [comment]
@farfromrefug I tried to reproduce the issue with unwanted animations. I noticed some strange transitions between zoom levels, but these seemed to be result of the CartoCSS rules. For example, take the  following rule for 'primary' roads:

```
::casing {
	[class=primary][zoom>=12] {
		line-color: linear([view::zoom], (12, @primary-low-zoom-casing), (13, @primary-casing));
		line-width: linear([view::zoom], (12, @primary-width-z12), (13, @primary-width-z13), (15, @primary-width-z15), (17, @primary-width-z17), (18, @primary-width-z18), (19, @primary-width-z19));
	}
}

::fill {
	[class=primary] {
		[zoom>=8][ramp!=1],
		[zoom>=10] {
			line-color: @primary-low-zoom;
			line-width: linear([view::zoom], (8, @primary-width-z8), (9, @primary-width-z9), (10, @primary-width-z10), (11, @primary-width-z11));
			[zoom>=12] {
				line-color: @primary-fill;
				line-width: linear([view::zoom], (12, @primary-width-z12 - 2 * @major-casing-width-z12), (13, @primary-width-z13 - 2 * @major-casing-width-z13), (15, @primary-width-z15 - 2 * @major-casing-width-z15), (17, @primary-width-z17 - 2 * @major-casing-width-z17), (18, @primary-width-z18 - 2 * @major-casing-width-z18), (19, @primary-width-z19 - 2 * @major-casing-width-z19));
			}
		}
	}
}
```

This rule has a sharp transition when zoom=11 tiles are replaced with zoom=12 tiles. Perhaps it would be better to replace with something like this:

```
::casing {
	[class=primary][zoom>=12] {
		line-color: @primary-low-zoom-casing;
		line-width: linear([view::zoom], (12, @primary-width-z12), (13, @primary-width-z13), (15, @primary-width-z15), (17, @primary-width-z17), (18, @primary-width-z18), (19, @primary-width-z19));
	}
}


::fill {
	[class=primary] {
		[zoom>=10] {
			line-color: linear([view::zoom], (11.5, @primary-low-zoom), (13.0, @primary-fill)); // 11.5 and 13.0 key values may need tweaking
			line-width: linear([view::zoom], (8, @primary-width-z8), (9, @primary-width-z9), (10, @primary-width-z10), (11, @primary-width-z11), (12, @primary-width-z12 - 2 * @major-casing-width-z12), (13, @primary-width-z13 - 2 * @major-casing-width-z13), (15, @primary-width-z15 - 2 * @major-casing-width-z15), (17, @primary-width-z17 - 2 * @major-casing-width-z17), (18, @primary-width-z18 - 2 * @major-casing-width-z18), (19, @primary-width-z19 - 2 * @major-casing-width-z19));
		}
	}
}
```

This is simpler and does not have the issue.

**Comment by farfromrefug** [comment]
@mtehver i tried with your change but i still see the issue. I ll dig deeper.

I found another visual "bug" with latest (i build from your latest changes).
As you can see the hillshade layer is like having a weird redraw effect. Feels like some parameters are quickly changing.
I am wondering if it comes from my build. Can you confirm you see it too?
https://user-images.githubusercontent.com/655344/124512619-1aab2e80-ddd9-11eb-9fbd-31dbff40ea7e.mov

**Comment by farfromrefug** [comment]
@mtehver thanks ! https://github.com/CartoDB/mobile-sdk/commit/ce8e0c8af79a7f7c24a1a3fa98128175c8d906ec fixed the issue with hillshade layers!

**Comment by mtehver** [comment]
@farfromrefug Thanks for reporting the hillshade issue. You are correct, the referred change was made to fix the issue.
