### ISSUE TITLE
Removing single track (line) from more than 500 tracks

### ISSUE THREAD

**Issue by binu8051** [CartoDB/mobile-sdk#433]
I am displaying tracks each track have several points.
So if i want to delete or edit a track, i need to delete all and reload the tracks again.
Any way to delete or edit a single track without reloading all tracks.

my code goes like this
`
int[] getalltracksid = locationTrackingDB.getTracksID();

int cnts = getalltracksid.length;
MapPosVector linePoses;
Line line1;
long track_id;
int pointcnt=0;
TrackData trackData;
//String tr_color;
LineStyleBuilder lineStyleBuilder = new LineStyleBuilder();
//lineStyleBuilder.setColor(new Color(android.graphics.Color.BLUE));
lineStyleBuilder.setLineJoinType(LineJoinType.LINE_JOIN_TYPE_ROUND);
lineStyleBuilder.setWidth(Const.LINE_WIDTH);
PointStyleBuilder pointStyleBuilder_line = new PointStyleBuilder();
pointStyleBuilder_line.setSize(5);
pointStyleBuilder_line.setColor(new Color(0xFF9a32cd));
PointStyleBuilder pointStyleBuilder_start = new PointStyleBuilder();
pointStyleBuilder_start.setSize(20);
pointStyleBuilder_start.setColor(new Color(0xFF008000));
PointStyleBuilder pointStyleBuilder_end = new PointStyleBuilder();
pointStyleBuilder_end.setSize(20);
pointStyleBuilder_end.setColor(new Color(0xFFdb041b));
Point point_line, point_start, point_end;
for(int l=0; l<cnts; l++){
	linePoses = new MapPosVector();
	track_id = getalltracksid[l];
	trackData = locationTrackingDB.getTrackDetails(track_id);		
	if (trackData.isOnMap) {
		pointcnt = trackData.locations.length;
		int toggle = 0;
		for(int ty=0; ty<pointcnt; ty++) {
			linePoses.add(projection.fromWgs84(new MapPos(trackData.locations[ty].x, trackData.locations[ty].y)));
			point_line = new Point(projection.fromWgs84(new MapPos(trackData.locations[ty].x, trackData.locations[ty].y)), pointStyleBuilder_line.buildStyle());
			point_line.setMetaDataElement("id", new Variant(trackData.id + ""));
			point_line.setMetaDataElement("speed", new Variant(trackData.speed[ty]));
			point_line.setMetaDataElement("title", new Variant(trackData.notes));
			point_line.setMetaDataElement("time", new Variant(trackData.ctime[ty]));
			point_line.setMetaDataElement("type", new Variant("1"));
			displayTracksVectorDataSource.add(point_line);
		}
		line1 = new Line(linePoses, lineStyleBuilder.buildStyle());
		displayTracksVectorDataSource.add(line1);
		//add Green Point on start point
		point_start = new Point(projection.fromWgs84(new MapPos(trackData.locations[0].x, trackData.locations[0].y)), pointStyleBuilder_start.buildStyle());
		addmeta_data(point_start, trackData, trackData.startTime, trackData.speed[0]);
		displayTracksVectorDataSource.add(point_start);
		//add Red Point on END point
		point_end = new Point(projection.fromWgs84(new MapPos(trackData.locations[pointcnt-1].x, trackData.locations[pointcnt-1].y)), pointStyleBuilder_end.buildStyle());
		addmeta_data(point_end, trackData, trackData.endTime, trackData.speed[pointcnt-1]);
		displayTracksVectorDataSource.add(point_end);
	}
}
`

**Comment by mtehver** [comment]
Assuming 'displayTrackVectorDataSource' is an instance of `LocalVectorDataSource`, you can simply use `remove` method. But you need to keep track of your vector elements. If you want to remove element based on its 'id', you can use `getAll` method of `LocalVectorDataSource`, iterate over all elements, check their metadata and remove corresponding element if its metadata matches.

**Comment by mtehver** [comment]
Not sure I understand the question. In summary, there are multiple ways how to approach removing the element. In case of around 500 lines/points, I would use the simplest method.

**Comment by mtehver** [comment]
Closing, as the questions have been answered.
