### ISSUE TITLE
4.4.0 RC get freezes & crash frequently

### ISSUE THREAD

**Issue by binu8051** [CartoDB/mobile-sdk#434]
Hi, i updated sdk to 4.4.0 from 4.3.5
The android app freezes often and sometime is works well
sometime it freezes within 5 mins and sometime after 30mins.
i am in android 11 and here is the logcat.

`2021-06-24 21:14:51.886 1517-2464/come.binu.app I/ut.binu.boatap: Thread[3,tid=2464,WaitingInMainSignalCatcherLoop,Thread*=0x7f11a7e800,peer=0x12d43b10,"Signal Catcher"]: reacting to signal 3
2021-06-24 21:14:52.395 1517-2472/come.binu.app W/ut.binu.boatap: Suspending all threads took: 119.877ms
2021-06-24 21:14:52.706 1517-2464/come.binu.app I/ut.binu.boatap: Wrote stack traces to tombstoned`

But the same code working without any problem on 4.3.5

**Comment by mtehver** [comment]
Thanks for the feedback, this is worrying. Can you share a test project (or your original app) with instructions how to reproduce the issue?

**Comment by mtehver** [comment]
@binu8051 4.4.0RC3 is now available. I suggest trying it and then reporting about any freezes and crashes with this version.

**Comment by binu8051** [comment]
Tried with latest RC4 still it get freeze. 
I use the Offline Maps app for Android from https://github.com/CartoDB/mobile-android-maps-app
i modified this app to my requirement with bluetooth GPS for location.

**Comment by mtehver** [comment]
@binu8051 That is not very helpful, unfortunately. The unmodified Offline Maps app seems to work fine with 4.4.0 RCs and the logcat snippet does not even refer to the SDK. So we have no way of analyzing this. We could take a closer look if you provided your modified project with detailed instructions how to trigger the issue.

**Comment by binu8051** [comment]
Hi, thanks for the reply, my app uses Bluetooth GPS.
Do you have bluetooth gps so i can create a modified project.

**Comment by mtehver** [comment]
@binu8051 Sorry, I do not have Bluetooth GPS.

**Comment by mtehver** [comment]
@binu8051 Any chance of sharing the project? 4.4.0 is now released but there were no related changes vs RCs, so the issue could still persist.

**Comment by binu8051** [comment]
Please check your mail.

**Comment by mtehver** [comment]
Can confirm the issue. It is caused by synchronization bug in `NMLModel.setRotation(axis, angle)` method. It is a regression in 4.4.0 and 4.4.1. Will be fixed 4.4.2. A workaround is to simply use two separate method calls: `NMLModel.setRotationAxis(axis)` and `NMLModel.setRotation(angle)`.

**Comment by binu8051** [comment]
Its fixed and working fine, thanks.
