### ISSUE TITLE
maxOverzoomLevel not working in some cases

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#435]
Context:
I have a vector layer using a `MergedMBVTTileDataSource`:
* map datasource defined from 0 to 14
* contours datasource which is defined from 9 to 13

until now the contours data source was defined up to 14 which was working perfectly and i was seeing contours at zoom > 14

Now my contours stops at 13. What i see is contours disappearing completely at zooms > 13.
I tried to force the contours datasource maxZoom to 14 and it started working. However i would prefer not to have to do that.
Not sure what or if it should be fixed.

**Comment by farfromrefug** [comment]
Actually i stand corrected. Forcing the maxZoom to 14 even if there only data up to 13 breaks all others data sources from MergedMBVTTileDataSource. No more data from zoom 14...

**Comment by mtehver** [comment]
@farfromrefug `MergedMBVTTileDataSource` only merges layers from tiles with matching zoom levels. If zoom ranges are not equal, then layers are simply dropped if outside the intersection of the zoom ranges of the datasources. It is technically quite hard to change this. For example, to make datasource with maxZoom=13 to work at zoom=14, the datasource needs to decode all the features, rescale the geometry coordinates and perform clipping. Basically it does not seem to be worth it.

**Comment by farfromrefug** [comment]
@mtehver thanks for looing into this. i got to the same conclusion and yes seems quite hard.
I would say it is a good to have feature because it can reduce packages (mbtiles) by 4x if we had that (for contours for example). 
But anyway there is one last thing i dont get. Past zoom 14 you do rescale and clip, right? I am not sure i understand why we could not apply the same rule in `MergedMBVTTileDataSource` as the one past zoom 14. But i might just not get it ...
