### ISSUE TITLE
[FR] make long press timeout duration customizable

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#437]
Right now the long press timeout is set to 400ms.
I always felt like something was weird about its behavior and i always was getting unwanted longpress.
Maybe one of 2 things:
* wrongly recognized long press. Does a touch move cancel a long press?
* too short timeout.

Whatever it is it would be good to be able to customize it.
On android the default is set to 500ms.

**Comment by farfromrefug** [comment]
Thinking about this and playing with the sdk there is something i dont get. Setting `setClickTypeDetection(false)` make single click type detection instant. The reason why it is not instant with `setClickTypeDetection(true)` is because of double click, right? it has nothing to do with longpress ?
I mean in my mind long press gesture should not influence single click detection as it happens on touch up. So i am starting to think, could we have a way to disable double click? should nt it be disabled by default?

**Comment by mtehver** [comment]
I think you are into something here, the click detection functionality likely needs an overhaul. I will look into this post 4.4.0 release.

**Comment by farfromrefug** [comment]
@mtehver this is fixed in latest version i can customize long click. This PR https://github.com/CartoDB/mobile-sdk/pull/445 add the final touch and allows me to customize double click

**Comment by mtehver** [comment]
Available in 4.4.1. Closing.
