### ISSUE TITLE
setClickTypeDetection and single click type detection

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#438]
I started to play with `setClickTypeDetection` to get more reactive click.
So i used `setClickTypeDetection(false)` but then i can t have single click with app gestures like move/zoom
The reason is that the click seems to be triggered on down and not up, and thus not canceled by move/zoom gestures.

What i would expect with `setClickTypeDetection(false)` is to not have long/double click types but still have single click working with gestures.
Or maybe i got it wrong and it is not what it is made for?

**Comment by mtehver** [comment]
I have reviewed the behavior of `setClickTypeDetection` and indeed, it made little sense. Click event was triggered on touch, not on click. I have updated the behavior in master and added `ClickInfo` attribute to `MapClickInfo`, `VectorTileClickInfo`, etc to get additional information about the touch (like click duration).

Thanks for bringing this into attention.

**Comment by farfromrefug** [comment]
@mtehver amazing that will be a great step forward! thanks. Are you going to look at this too https://github.com/CartoDB/mobile-sdk/issues/437 ? I would love to disable only double click to get faster click detection while keeping the ability to get long click

**Comment by mtehver** [comment]
@farfromrefug With click duration available via ClickInfo you can do short/medium/long click detection easily yourself.

**Comment by farfromrefug** [comment]
@mtehver i see ! You are right so you say `setClickTypeDetection(false)` then handle it myself?

It will work though i still something is wrong with double click handling. It should be possible to disable it and we should have very fast single click while being able to do long click

**Comment by farfromrefug** [comment]
@mtehver i tried with `setClickTypeDetection(false)` and using `duration` to handle long press but it wont work!
A long press gesture is not triggered on on touch up but on long press timeout. I dont see a way to do it with `setClickTypeDetection(false)`

**Comment by mtehver** [comment]
@farfromrefug Are you sure you have the latest version from master? There is no timeout after `setClickTypeDetection(false)`, the event is triggered only on touch up.

**Comment by farfromrefug** [comment]
@mtehver yes it is my point. No timeout so no way to hanfle longress that way

**Comment by mtehver** [comment]
@farfromrefug Ok, I think I understand your point now. So you would like to have click triggered even when finger is not lifted after 500ms? And perhaps this 500ms should be configurable via options?

**Comment by farfromrefug** [comment]
@mtehver yes you are right but let me sums up:
* `setClickTypeDetection(true)`:
     - there should be a way to disable double click 
     - when double click is disabled there should be no more delay for single click. (the delay exist to detect double click)
     - options to customize long press timeout ?
* `setClickTypeDetection(false)`:
    - no dual/double/long ... detection
    - thus not sure you want to trigger after a customisable time out ? Maybe the current (new behavior) is what you intended for that option all along.
    
To conclude the whole point of my discussion was to aim for this:
* single click on touch up with no delay (like we do with `setClickTypeDetection(false)`)
*  no double click as i dont need it
* long click feature with  optional timeout duration feature (if possible)

**Comment by mtehver** [comment]
@farfromrefug This makes sense, in some cases the current long click detection mode may be a good fit. I have updated the master branch to reflect this proposal. There are now 2 additional methods in `Options` class: `setDoubleClickDetection` (default value true) and `setLongClickDuration` (default value 0.4, that is 400ms).

**Comment by farfromrefug** [comment]
@mtehver it is perfect ! i added this https://github.com/CartoDB/mobile-sdk/pull/445 to fine tune it all

**Comment by mtehver** [comment]
Thanks! #445 is merged and will be in final 4.4.1 release.

**Comment by mtehver** [comment]
4.4.1 is released now, thus closing.
