### ISSUE TITLE
How to setFocusPos below center point.

### ISSUE THREAD

**Issue by binu8051** [CartoDB/mobile-sdk#446]
Hi, i am placing a car marker which get the map position from the gps. The mapview.setFocusPos is also the the position from gps. mapView.setFocusPos(GPSlocation, 0.5f); put the mapview in center with the marker.

Its a navigation app and so that i want the place the marker below the centerpoint of the mapview so i can get more space on top (front or the marker) of the mapview.

you would have seen on google map in which the car marker is placed below the center of the mapview.

How to setFocusPos the mapview below center point.

**Comment by mtehver** [comment]
You can use `setFocusPointOffset` method from `Options` class.

**Comment by binu8051** [comment]
Thanks it worked.
