### ISSUE TITLE
`GeoJSONVectorTileDataSource` 

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#453]
i have line features inside a `GeoJSONVectorTileDataSource`. It seems `line-cap` and `line-join` are not working. I tried `round` but it has no effect
Also there is a line simplification applied depending on zoom. Anyway to disable it?

**Comment by farfromrefug** [comment]
@mtehver while debuggiing this i found some rendering issues.The line joins are not always "drawn".
BTW if using `line-join:round` shouldn't those "angles" be rounded? (they are not right now)
here is the style:
```
@name: [nuti::lang] ? ([name:[nuti::lang]] ? [name:[nuti::lang]] : ([name:[nuti::fallback_lang]] ? [name:[nuti::fallback_lang]] : [name])) : [name];
// @markerOverlap: [nuti::selected_id] = [id] ? false : true;
@itemLineWidth: (pow(2.0, linear([view::zoom], (14, -2.8), (18, 3.2))) + 0.5) * linear([view::zoom], (14,0), (14.01, 1));
#items {

	['mapnik::geometry_type'=2]{
        back/line-color: white;
        back/line-width: @itemLineWidth + 1;
        // back/line-cap:round;
        // back/line-join:round;
        line-color: gray;
        // line-cap:round;
        // line-join:round;
        line-width: @itemLineWidth;

        ['nuti::selected_id'!=''] {
            back/line-width: @itemLineWidth + 4;
            line-color: #60A5F4;
            line-width: @itemLineWidth + 2;
            marker-placement: line;
            marker-type:arrow;
            marker-line-width:0;
            marker-opacity:0.6;
            marker-width: @itemLineWidth;
            marker-height: @itemLineWidth;
            marker-fill: #B3CEFF;

        }
    }
}
```
https://user-images.githubusercontent.com/655344/131251649-d40e782b-5379-4760-96df-0e4db1107fbf.mov

**Comment by mtehver** [comment]
@farfromrefug `line-join: round` is not supported. The artifacts are a result of sharp angles that cause 'miter' join to be turned off. Such joins should be turned to 'bevel' joins (currently the line is simply split into 2 separate segments at these points). I will look into that post 4.4.1 release and probably add support for 'bevel' joins.

**Comment by farfromrefug** [comment]
@mtehver thanks i actually did not understand `line-join: round` was not supported. My bad!

**Comment by mtehver** [comment]
@farfromrefug Lines with sharp angles like the one on the screenshot above should now look better in SDK 4.4.2 RC1.

Also, when using 4.4.2 RC1 you can now configure `GeoJSONVectorTileDataSource` simplification tolerance using `setSimplifyTolerance` method. You can disable simplification by setting the value to 0. In addition, I have changed the default tolerance value so artifacts should be much less noticeable.

**Comment by farfromrefug** [comment]
@mtehver thanks already using all of that ;)

**Comment by mtehver** [comment]
@farfromrefug Regarding round line-join mode, it is in TODO list currently.
