### ISSUE TITLE
Custom MBTilesTileDataSource by Android SQLite lib

### ISSUE THREAD

**Issue by vTechGIS** [CartoDB/mobile-sdk#455]
Hello, 
My application uses the built-in MBTilesTileDataSource class. But
currently i want to use "android.database.sqlite.SQLiteDatabase" class to override "loadTile" method, is that possible?

Could you help me with that sample code, thank you so much.

**Comment by mtehver** [comment]
Hello. Yes, you can write a custom `TileDataSource` subclass. We had a discussion about this some time ago. Please check #430.

**Comment by vTechGIS** [comment]
Thank you so much,
