### ISSUE TITLE
Use SkiaSharp to draw bitmap

### ISSUE THREAD

**Issue by MatteoColombo** [CartoDB/mobile-sdk#457]
Hello, 
I need to draw a pop up with a custom layout and was thinking of extending the method drawBitmap of the CustomPopup/BalloonPopup class to draw the bitmap with SkiaSharp.
Is there a better way to achieve this? What would be the best way to convert a SKImage/SKBitmap to a Carto Bitmap?

Thanks!

**Comment by mtehver** [comment]
Hi. Not very familiar with Skia API, but there seem to be two options:
1. Simply 'save' the created image to PNG blob and then use `Bitmap.CreateFromCompressed` method from CARTO SDK.
2. Convert your `SKBitmap` to Android Bitmap (or iOS `UIImage`) and then use `BitmapUtils.CreateBitmapFromAndroidBitmap` (or `BitmapUtils.CreateBitmapFromUIImage`) from SDK.

The first option is slower but cross platform, so it depends which one is better.
