### ISSUE TITLE
MBVectorTileDecoder from CompiledStyleSet is slow (xml / json)

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#458]
I just realized that generating a `MBVectorTileDecoder` from `CompiledStyleSet` is really slow.
I tested with that theme https://github.com/farfromrefug/new_carto_theme as a zip and it took almost 1.5s. 
Now i also transformed that json style to xml and it dropped to 500ms

TBH i think it should be faster in both cases. Seems to me that now my theme is pretty small. 
I remember you telling me that json style parsing was now really fast. It seems pretty slow right now.

Would be really good to have this really faster

**Comment by mtehver** [comment]
@farfromrefug That is really strange. How did you measure it?

I did a quick measurement with SDK 4.4.2 and the latest style snapshot from your GitHub repo:

```
                long x0 = System.nanoTime();

                BinaryData styleAsset = AssetUtils.loadAsset("new_carto_theme.zip");
                AssetPackage styleAssetPackage = new ZippedAssetPackage(styleAsset);
                CompiledStyleSet styleSet = new CompiledStyleSet(styleAssetPackage);
                MBVectorTileDecoder tileDecoder = new MBVectorTileDecoder(styleSet);
                TileDataSource dataSource = new CartoOnlineTileDataSource("carto.streets");
                VectorTileLayer currentLayer = new VectorTileLayer(dataSource, tileDecoder);
                long x1 = System.nanoTime();

                Log.debug("Layer construction time: " + (x1 - x0) / 1000000);
```

I got 320ms on my Pixel 4a, which uses midrange SoC/CPU. This is not exactly great, but usable. I also have some optimisations that should reduce loading time by additional 20-30% for complex styles.

**Comment by farfromrefug** [comment]
@mtehver I do exactly the same thing (except i use 'osm' style which has image patterns). I tried right now with `streets` (CartoCSS style) and it took  1.3s so could be the same time exactly. BTW i only count the time of the `MBVectorTileDecoder` creation from `CompiledStyleSet` which is where the parsing is done.
One thing is that i test on a Samsung a3 2017 which is for sure slower

**Comment by mtehver** [comment]
@farfromrefug Ok, I guess ARM A53 cores are really that much slower than A76 cores then. The latest develop branch snapshot should improve performance by 20-30%, but I will do additional profiling.

**Comment by farfromrefug** [comment]
@mtehver tested your latest changes and am now at 950ms! this is already a big win :D Thanks a lot

**Comment by mtehver** [comment]
I did some further profiling and added few optimizations and the latest develop snapshot should cut another 10% of the loading time. In addition I created a PR with some style changes that make parsing/compiling of the style faster (https://github.com/farfromrefug/new_carto_theme/pull/4).

With the latest SDK changes and optimized style I got the loading time down to 125ms on my Pixel 4a. That seems to be good enough.

**Comment by farfromrefug** [comment]
@mtehver awesome will test that! 
Could you explain a few of your optimisations on the style? :
* using `[zoom=15]` instead of `[zoom>=15]` when targeting `zoom >= 15 && zoom <16` is an optimisation? not sure i see why
* `#park` i see why,  it was adding rules for many cases not related to park. Duplicates but makes sense
* you moved `['mapnik::geometry_type'=3]` for `#transportation` can you explain the optimisation? (so that i dont do it again)

**Comment by mtehver** [comment]
@farfromrefug Regarding `[zoom=X]`, instead of `[zoom>=X]`. This seemed to make measurable difference, but I did not have time to investigate this further. Also, I think in case of POI layer, it makes things easier to read.

Regarding 'transportation' layer, by explicitly checking for correct `geometry_type`, I fixed a few potential cases where line symbolizers were used for polygon geometry. The implemented changes reduced the number of rules in generated XML file.

**Comment by farfromrefug** [comment]
@mtehver so i did ran some tests with your latest changes:
* loading the new theme with your PR took 505ms 
* loading the same theme compiled in xml took 313ms
* thanks to your PR on the theme xml style files dropped from 1.4Mb to 800kb ....

So clearly we can say that on the side of the SDK loading of style we are good !
Now loading cartoCSS is still quite a lot slower than loading XML (no big deal here).
I will end up saying that still improvements can be made in the XML generation which would make files smaller but also loading faster(less rules):
* i see a lot of duplicate rules which could be joined based on `MinScaleDenominator` and `MaxScaleDenominator`. Like joining rule1 and rule2 if `rule1.MaxScaleDenominator === rule2.MinScaleDenominator`.
* that simple change, looking at my xmls, could reduce the file size by 20 to 40%
