### ISSUE TITLE
Boost linking error

### ISSUE THREAD

**Issue by asdafa3** [CartoDB/mobile-sdk#462]
## Problem

I noticed the recent changes with regard to how boost is set up for the project and really appreciate that the process in clearer now. However, building the latest release version of the SDK (release/v4.4.2), I still face issues with boost during the build process using your updated build instructions.

I did setup the project and resolved dependencies like described in the latest BUILDING.md notes

```
git submodule update --init --remote --recursive

curl -o boost_1_77_0.zip -L https://sourceforge.net/projects/boost/files/boost/1.77.0/boost_1_77_0.zip/download
unzip boost_1_77_0.zip
ln -s boost_1_77_0 libs-external/boost
cd boost_1_77_0
./bootstrap.sh
./b2 headers
cd ..
```

As no issues occurred during the setup process and the symlink was verified to be correctly set, I tried to build the project as

```
python swigpp-objc.py --profile standard
python build-ios.py --profile standard --use-metalangle
```

which results in the following type of errors

```
/mobile-sdk/libs-external/sqlite3pp/sqlite3pp.h:29:10: fatal error: 
      'boost/utility.hpp' file not found
#include <boost/utility.hpp>
```

The problem occurs on Mac OS.

## Solution

As the build instructions above did not work and the issue was clearly related to the symlink not working, I tried to use a relative path like (after unpacking boost in the project root folder) as 

```
cd libs-external/
ln -s ../boost_1_77_0 boost
```

which solved the linking issue. I am not sure if the ```ln``` command does handle things differently under Linux, but for Mac OS, I would propose to at least specify this behavior in the build instructions and/or provide an example.

**Comment by mtehver** [comment]
Thanks! I have updated the instructions, as you suggested.

**Comment by mtehver** [comment]
Correct, by default Windows requires slightly different commands. Fortunately there is 'Windows Subsystem for Linux' nowadays that can be used with no changes needed.

I have clarified the instructions a bit regarding Windows.
