### ISSUE TITLE
Can't archive 4.4.2 version via Xcode 12.5.1

### ISSUE THREAD

**Issue by JustasL** [CartoDB/mobile-sdk#464]
Well, as the title says - I can not archive an app with Carto 4.4.2 version using Xcode 12.5.1 (and 12.5), because of the following error:

ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1300.0.29.3.0_0' Reader: '1205.0.22.11_0')', using libLTO version 'LLVM version 12.0.5, (clang-1205.0.22.11)' for architecture arm64

I can easily archive build with 4.4.1

Oh, and I am using Swift Package Manager

**Comment by mtehver** [comment]
Thanks for reporting this. SDK 4.4.2 is compiled with XCode 13, I guess it is not backward compatible with XCode 12.x. As 4.4.2 does not contain any critical fixes vs 4.4.1, I recommend downgrading to 4.4.1 until you decide to start using XCode 13.

In general our release policy is to use the latest stable platform for all releases. In case of iOS this means currently XCode 13 and with Android this means API 31 and NDK r23.
