### ISSUE TITLE
Small water animation over map

### ISSUE THREAD

**Issue by binu8051** [CartoDB/mobile-sdk#468]
Hi, my app is for marine users so that the sea looks plain and i cant see the boat icon moving over the sea while the user moves over the sea. how to place a small water animation if it cant be done how to draw some grid lines over the map so they can see the boat moving on the map.
Thanks
Binu

**Comment by mtehver** [comment]
Hi. I would approach it as follows: create a number of half-transparent bitmap frames that can be cycled. Then create for each bitmap a `MarkerStyle` instance with that uses `BILLBOARD_ORIENTATION_GROUND` mode. Then add a marker to the position of your icon and update the style after each 5ms or so.

But it really depends what kind of visual you are trying to achieve.
