### ISSUE TITLE
adding a layer as hidden wont refresh on shown

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#471]
Let say you add a `VectorTileLayer` but `setVisible(false)` before adding it.
Then if you show it again with  `setVisible(true)` after being added to the map the the "visible" tiles wont get loaded and thus the layer wont show. The layer will appear on any map move (thus calling loadTiles).
Let me know if you need a repro sample.

**Comment by mtehver** [comment]
Indeed, thanks for reporting this. Will look into this today.

**Comment by farfromrefug** [comment]
@mtehver thanks! question related to this. I am seeing some real lagging on vector tile click detection right now in my app. I am trying to improve it. I can clearly see that having multiple vector tile layers with click listeners makes it slower. My question is, are hidden vector tiles layers correctly ignored in click handling? (i am investigating but asking could be faster ;))

**Comment by mtehver** [comment]
@farfromrefug Regarding click detection, I am quite sure that this works properly, thus hidden layers are ignored in click handling. 

Click handling could be somewhat slow, as all layers and features of matching tiles need to be decoded and checked against the click point. So the complexity in click detection is proportional to the number of features in the tile.

**Comment by mtehver** [comment]
@farfromrefug I just pushed a fix for this to master. Let's keep it open until 4.4.3 is released.

**Comment by farfromrefug** [comment]
@mtehver about vector tile click handling, i was thinking about something. If there was a parameter to ignore or filter layers to be used for click detection, would it make it faster? For example in my case i have many heavy layers which in fact could be totally ignored in click detection (like transportation or contours).

**Comment by farfromrefug** [comment]
@mtehver i have quickly looked at the code and it seems that it would make a big difference to be able to filter layers used for click event [here](https://github.com/cartodb/mobile-carto-libs/blob/100a85c0e445a6499244ceb55979578af403ead8/vt/src/vt/GLTileRenderer.cpp#L501)
I can have a go at it? though i know you would do it better and maybe prefer to do it yourself.

**Comment by mtehver** [comment]
@farfromrefug There are a few other places where changes are needed. I think I could do it, it makes sense. From API point of view, I would add something like this to `VectorTileLayer`:

```
void setClickHandlerLayerFilter(StringVector layerNames);
```

If non-empty, then only explicitly listed layers are used for click handling. Does this sound ok?

**Comment by farfromrefug** [comment]
@mtehver that sounds perfect! Thanks for your answer

**Comment by farfromrefug** [comment]
@mtehver working now thanks!

**Comment by farfromrefug** [comment]
@mtehver about the new `rendererLayerFilter` and `clickHandlerLayerFilter` regexp strings.
There seem to be something weird that i dont understand. It does not work for all layer names.  for this`landuse|landcover|water` only water and landcover are visible. Also `mountain_peak` does not work.
Not sure why `landuse` / `mountain_peak` ... are not detected

**Comment by mtehver** [comment]
@farfromrefug Regarding the filters, there are several subtle details:

* Tile/map background is also a layer with empty name. Thus if you want to use rendererLayerFilter and enable background, you need to add `^$` to regexp.
* Layer names are 'qualified names'. For example:
```
#transportation {
  ...
  ::case {
     ...
  }
}
```
You will have two layer, one with name 'transportation' and the second with name 'transportation::case'. Thus the regexp for rendering should probably be 'transportation.\*' or 'transportation|transportation::.\*'
* renderLayerFilter also affects click handling, non visible layers are not tested for clicks

**Comment by mtehver** [comment]
@farfromrefug Also, by using rendererLayerFilter, we could close issue #408. The following regexp will render all layers but not the background: '.+'

**Comment by farfromrefug** [comment]
@mtehver i get it now thanks! perfect and amazing for https://github.com/CartoDB/mobile-sdk/issues/408!

**Comment by farfromrefug** [comment]
@mtehver using something like this `clickHandlerLayerFilter: '(place|poi|mountain_peak|landuse|housenumber|water_name|waterway::label|water::label|landcover::label|park).*'` makes a huge difference! All my maps interactions are now instant on an old device. From vector tile click to map click and long press!
This is an amazing improvement which leads me to believe that a default one should be on by default. Seeing all vector styles are different i am thinking we should allow `clickHandlerLayerFilter` to be defined through a style json configuration file (which could be overloaded through `setClickHandlerLayerFilter`. That way the style designer could create the default so that every user get the most of the style. What do you think? Is it doable?

**Comment by mtehver** [comment]
@farfromrefug I added an option to configure few VectorTileLayer initial parameters via 'nutiparameters' in style.json. You can find the list in VectorTileLayer.cpp constructor. This feature is somewhat experimental, so I will currently not mention it anywhere in documentation.

**Comment by farfromrefug** [comment]
@mtehver awesome! i confirm it works as expected. You can define it through style and override it throught `VectorTileLayer`. Great addition for optimised styles. Will update the new style consequently
Thanks
