### ISSUE TITLE
[FR] add support for building `min_height`

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#472]
As explained in OSM wiki https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings a buidling can define a `min_height` defining that this part of the building is of the ground.
OpenMapTiles already defines that property, would it be great for this to be supported by carto

**Comment by mtehver** [comment]
This is already supported, just use `building-min-height: [min_height]` in CartoCSS.
