### ISSUE TITLE
[FR] release javadoc in maven repo

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#473]
I find myself always needing to access carto sdk java doc, and often offline. 
If the doc was released on maven then we could download it for apps like `[Dash](https://kapeli.com/dash)`
Thanks

**Comment by mtehver** [comment]
Good point. I think we lost published javadocs when moving from Jcenter to Maven Central. Will look into this.

**Comment by farfromrefug** [comment]
@mtehver thanks for publishing the doc. However it seems to be missing the index. I stumble upon this error https://github.com/Kapeli/javadocset/issues/8
It seems that somehow we are using `javadoc.noindex=true`

**Comment by mtehver** [comment]
@farfromrefug Currently we use 'doclava' doclet for generating Android documentation, it supports additional tags not supported by standard doclet. I believe 'doclava' is the reason for the non-standard output format. I will check if we can drop 'doclava', it seems to be unsupported anyway.

**Comment by mtehver** [comment]
@farfromrefug 4.4.3 RC3 is now available, it uses standard doclet for javadocs. Hopefully this works with 3rd party tools.

**Comment by farfromrefug** [comment]
@mtehver it works perfectly with latest version! this is a great improvement!
Thanks
