### ISSUE TITLE
concurrent `calculateRoute`

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#474]
I am trying to compute 3 routes concurrently to get a behavior like google maps.
The issue is that because of the `ValhallaOfflineRoutingService` `_mutex` this wont be possible. It even locks my thread because i call `setProfile` from the main thread.
So my question is this:
* would it be possible to call 2 concurrents `calculateRoute` from different threads? It is not the biggest deal but it would be faster. Not sure if possible seeing it would concurrent access to the sqlite database

I will handle the `setProfile` issue myself

**Comment by mtehver** [comment]
Are you using 3 different profiles/configurations for the routes? Then it is very difficult to use the same instance of routing service and guarantee correct results. If you do the following steps in 3 concurrent threads:
```
routingService.setProfile("auto");
routingService.calculateRoute(request);
```
Then there is no guarantee that you get results with correct profiles. I recommend creating 3 instances of `ValhallaOfflineRoutingService` and running each thread on different instance.

Assuming you can share the profile and configuration between threads, then I think you could execute `calculateRoute` in parallel. I have added synchronization there 'just for case', as I was not 100% sure about threading guarantees in Valhalla. But looking at the code, I am pretty sure this is thread-safe.

**Comment by farfromrefug** [comment]
@mtehver i do 3 requests but with the same profile. The idea is to give 3 alternatives routes (shortest, hardest, average...). 
But i understand your point about multiple profile. The solution would be to add profile as a setting of `RoutingRequest` or to add `profile` as an optional parameter of `calculateRoute` . Because once we call `ValhallaRoutingProxy::CalculateRoute` we should be thread safe.
let me know what you think

**Comment by mtehver** [comment]
@farfromrefug Changing profile is fast for Valhalla, but not for other routing engines. OSRM does not support profiles at all and SGRE rebuilds routing graph when profile changes.

Regarding allowing parallel `calculateRoute` in `ValhallaOfflineRoutingService`, you are correct. I will make the relevant changes to allow it. There are other services with similar limitation as well, so I will try to fix these also.

**Comment by farfromrefug** [comment]
@mtehver i tried your last changes but now it crashes when i try to run concurrent `calculateRoute` from different threads. (each calculateRoute has its own thread).
I have strictly nothing in the logcat. I am not sure what s happening

**Comment by mtehver** [comment]
@farfromrefug Is this reproducible? Can you share you .vtiles database?

**Comment by farfromrefug** [comment]
It should be reproducable yes though right now.i do it through nativescript. Will share the vtiles tonight

**Comment by farfromrefug** [comment]
@mtehver looking here https://github.com/CartoDB/mobile-external-libs/tree/master/valhalla it seems valhalla does not point to your latest changes for 3.1.4. I i the other hand is using head. Might it be why you are not seeing the issue?

**Comment by farfromrefug** [comment]
@mtehver Here is a sample java code which should allow to reproduce the issue. (building right now to test it)
```java
public void runValhallaInThread(final ValhallaOfflineRoutingService routingService, final RoutingRequest request, String profile, final LocalVectorDataSource localSource) {
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    RoutingResult result = routingService.calculateRoute(request);
                    MapPosVector pointsWithAltitude = new MapPosVector();
                    if (result != null) {
                        MapPosVector points = result.getPoints();
                        Log.d(TAG, "showing route " + points.size());
                        LineStyleBuilder builder = new LineStyleBuilder();
                        builder.setWidth(4);
                        builder.setColor(new Color((short) 255, (short) 0, (short) 0, (short) 255));
                        Line line = new Line(points, builder.buildStyle());
                        localSource.add(line);
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        thread.start();
    }

    public void testValhalla(HillshadeRasterTileLayer layer, Options options) {
        Projection projection = options.getBaseProjection();
        ValhallaOfflineRoutingService routingService;
        try {
            routingService = new ValhallaOfflineRoutingService("/storage/10E7-1004/alpimaps_mbtiles/france.vtiles");
            LocalVectorDataSource localSource = new LocalVectorDataSource(projection);
            VectorLayer vectorLayer = new VectorLayer(localSource);
            mapView.getLayers().add(vectorLayer);
            MapPosVector vector = new MapPosVector();
            vector.add(new MapPos(5.720614, 45.174683));
            vector.add(new MapPos(5.726890, 45.201224));
            RoutingRequest request = new RoutingRequest(projection, vector);
            request.setCustomParameter("costing_options", Variant.fromString("{\"pedestrian\":{\"driveway_factor\":10,\"max_hiking_difficulty\":6,\"shortest\":false,\"step_penalty\":0,\"use_ferry\":0,\"use_hills\":1,\"use_roads\":0,\"use_tracks\":1,\"walking_speed\":4}},\"directions_options\":{\"language\":\"en\"}}"));
            runValhallaInThread(routingService, request, "pedestrian", localSource);
            request = new RoutingRequest(projection, vector);
            request.setCustomParameter("costing_options", Variant.fromString("{\"pedestrian\":{\"driveway_factor\":10,\"max_hiking_difficulty\":6,\"shortest\":false,\"step_penalty\":1,\"use_ferry\":0,\"use_hills\":0,\"use_roads\":0,\"use_tracks\":1,\"walking_speed\":4}},\"directions_options\":{\"language\":\"en\"}}"));
            runValhallaInThread(routingService, request, "pedestrian", localSource);
            request = new RoutingRequest(projection, vector);
            request.setCustomParameter("costing_options", Variant.fromString("{\"pedestrian\":{\"driveway_factor\":10,\"max_hiking_difficulty\":6,\"shortest\":true,\"step_penalty\":5,\"use_ferry\":0,\"use_hills\":1,\"use_roads\":0,\"use_tracks\":1,\"walking_speed\":4}},\"directions_options\":{\"language\":\"en\"}}"));
            runValhallaInThread(routingService, request, "pedestrian", localSource);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

**Comment by farfromrefug** [comment]
@mtehver reproduced the crash with the above sample code. The issue seems to be with sqlite and concurrent querying
<img width="1742" alt="Screenshot 2021-12-03 at 11 04 45" src="https://user-images.githubusercontent.com/655344/144584588-9448a82f-752d-4a9a-90ef-2af426cb58c7.png">

**Comment by mtehver** [comment]
Great, thanks for tracking this down. Can you make this change in packagemanager/handlers/ValhallaRoutingPackageHandler.cpp:

Replace
```
if (_packageDb->connect_v2(_fileName.c_str(), SQLITE_OPEN_READONLY) != SQLITE_OK) ...
```

with
```
if (_packageDb->connect_v2(_fileName.c_str(), SQLITE_OPEN_READONLY | SQLITE_OPEN_FULLMUTEX) != SQLITE_OK) ...
```

Does this change fixe the issue? It is possible that without explicit 'mutex flag' sqlite connections are not thread-safe.

**Comment by mtehver** [comment]
@farfromrefug Sorry, I pointed to wrong file. Basically try the same change (add `SQLITE_OPEN_FULLMUTEX`) in routing/ValhallaOfflineRoutingService.cpp file.

**Comment by farfromrefug** [comment]
@mtehver yes i saw it was somewhere else. And it works!!! :D It is so fast now :D
