### ISSUE TITLE
wont build on macos 11.6 / xcode 13.0 / NDK r21e

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#475]
Recently the android has stopped working for me. It fails at link time:
```
ld.lld: error: unknown argument: -threads=4
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
I dont know why and i dont even see that flag anywhere :s It works in github actions though. Do you have any idea?

**Comment by mtehver** [comment]
I think the linker flag that causes this is `-threads=4` in scripts/build/CMakeLists.txt (`CMAKE_SHARED_LINKER_FLAGS_RELEASE` parameter). I guess you can remove it for your local build.

I suggest upgrading to NDK 23b, which is the latest 'LTS' release.
