### ISSUE TITLE
handling cross tile polygons labels

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#476]
In my custom version of openmaptiles i have landuse polygons which can have a name.
I have an issue while rendering those labels when polygon is split on 2 tiles. The label render twice. What i "would like" is to get one label in the middle of the polygon. I can try use min text distance but it will not always work depending on the polygon size.
You can see the tiles limits in openstreetmap (thin white lines)

<img width="1284" alt="Screenshot 2021-12-08 at 11 57 36" src="https://user-images.githubusercontent.com/655344/145197377-7bd0a32c-ce2f-4194-955f-011106cbcbe9.png">

**Comment by mtehver** [comment]
This is problematic with tiles, unfortunately. That is also the main reason why there are layers like 'water_name', 'transportation_name' in vector tiles in addition to 'water' and 'transportation'.

In case the plygon feature includes id (or perhaps you can use 'name' field as id), the label should be rendered once but it may jump around when zooming or panning the map.

**Comment by farfromrefug** [comment]
@mtehver ok you confirm what i was thinking. Did not really want to add another layer just for those names as it would make the tiles bigger but i get it. 
Now about your point about id indeed landcover and landuse dont have id (for size reasons i would guess).
All you say makes sense and i understand you cant do much more. I ll stick with this for now. Thanks for the explanation
