### ISSUE TITLE
marker-transform using too much memory

### ISSUE THREAD

**Issue by MatteoColombo** [CartoDB/mobile-sdk#477]
I have tile layer of wind data (speed and direction) and I need to display icons/images for each single value.
The dataset is big and spreads worldwide, ranging from zoom level 0 to zoom level 5.
I noticed that after some time I've been panning and zooming, the application closes/freezes because of an out of memory exception.

This is my style:
```#wind{
                [WindSpeed >=0 ] [WindSpeed < 2.5] {marker-file: url('wind/0.svg');}
                [WindSpeed >=2.5 ] [WindSpeed < 7.5] {marker-file: url('wind/5.svg');}
                [WindSpeed >=7.5 ] [WindSpeed < 12.5] {marker-file: url('wind/10.svg');}
                [WindSpeed >=12.5 ] [WindSpeed < 17.5] {marker-file: url('wind/15.svg');}
                [WindSpeed >=17.5 ] [WindSpeed < 22.5] {marker-file: url('wind/20.svg');}
                [WindSpeed >=22.5 ] [WindSpeed < 27.5] {marker-file: url('wind/25.svg');}
                [WindSpeed >=27.5 ] [WindSpeed < 32.5] {marker-file: url('wind/30.svg');}
                [WindSpeed >=32.5 ] [WindSpeed < 37.5] {marker-file: url('wind/35.svg');}
                [WindSpeed >=37.5 ] [WindSpeed < 42.5] {marker-file: url('wind/40.svg');}
                [WindSpeed >=42.5 ] [WindSpeed < 47.5] {marker-file: url('wind/45.svg');}
                [WindSpeed >=47.5 ] [WindSpeed < 52.5] {marker-file: url('wind/50.svg');}
                [WindSpeed >=52.5 ] [WindSpeed < 57.5] {marker-file: url('wind/55.svg');}
                [WindSpeed >=57.5 ] [WindSpeed < 62.5] {marker-file: url('wind/60.svg');}
                [WindSpeed >=62.5 ] [WindSpeed < 67.5] {marker-file: url('wind/65.svg');}
                [WindSpeed >=67.5 ] [WindSpeed < 72.5] {marker-file: url('wind/70.svg');}
                [WindSpeed >=72.5 ] [WindSpeed < 77.5] {marker-file: url('wind/75.svg');}
                [WindSpeed >=77.5 ] [WindSpeed < 82.5] {marker-file: url('wind/80.svg');}
                [WindSpeed >=82.5 ] [WindSpeed < 87.5] {marker-file: url('wind/85.svg');}
                [WindSpeed >=87.5 ] [WindSpeed < 92.5] {marker-file: url('wind/90.svg');}
                [WindSpeed >=92.5 ] [WindSpeed < 97.5] {marker-file: url('wind/95.svg');}
                [WindSpeed >=97.5 ] [WindSpeed < 102.5] {marker-file: url('wind/100.svg');}
                [WindSpeed >=102.5 ] [WindSpeed < 107.5] {marker-file: url('wind/105.svg');}
                [WindSpeed >=107.5 ] [WindSpeed < 112.5] {marker-file: url('wind/110.svg');}
                [WindSpeed >=112.5 ] [WindSpeed < 117.5] {marker-file: url('wind/115.svg');}
                [WindSpeed >=117.5 ] [WindSpeed < 122.5] {marker-file: url('wind/120.svg');}
                [WindSpeed >=122.5 ] [WindSpeed < 127.5] {marker-file: url('wind/125.svg');}
                [WindSpeed >=127.5 ] [WindSpeed < 132.5] {marker-file: url('wind/130.svg');}
                [WindSpeed >=132.5 ] [WindSpeed < 137.5] {marker-file: url('wind/135.svg');}
                [WindSpeed >=137.5 ] [WindSpeed < 142.5] {marker-file: url('wind/140.svg');}
                [WindSpeed >=142.5 ] [WindSpeed < 147.5] {marker-file: url('wind/145.svg');}
                [WindSpeed >=147.5 ] [WindSpeed < 152.5] {marker-file: url('wind/150.svg');}
                [WindSpeed >=152.5 ] [WindSpeed < 157.5] {marker-file: url('wind/155.svg');}
                [WindSpeed >=157.5 ] [WindSpeed < 162.5] {marker-file: url('wind/160.svg');}
                [WindSpeed >=162.5 ] [WindSpeed < 167.5] {marker-file: url('wind/165.svg');}
                [WindSpeed >=167.5 ] [WindSpeed < 172.5] {marker-file: url('wind/170.svg');}
                [WindSpeed >=172.5 ] [WindSpeed < 177.5] {marker-file: url('wind/175.svg');}
                [WindSpeed >=177.5 ] [WindSpeed < 182.5] {marker-file: url('wind/180.svg');}
                [WindSpeed >=182.5 ] [WindSpeed < 187.5] {marker-file: url('wind/185.svg');}
                [WindSpeed >=187.5 ] [WindSpeed < 192.5] {marker-file: url('wind/190.svg');}
                [WindSpeed >=192.5 ] [WindSpeed < 197.5] {marker-file: url('wind/195.svg');}
                [WindSpeed >=197.5 ] [WindSpeed < 202.5] {marker-file: url('wind/200.svg');}
                [WindSpeed >=202.5 ] [WindSpeed < 207.5] {marker-file: url('wind/205.svg');}
                [WindSpeed >=207.5 ] [WindSpeed < 212.5] {marker-file: url('wind/210.svg');}
                [WindSpeed >=212.5 ] [WindSpeed < 217.5] {marker-file: url('wind/215.svg');}
                [WindSpeed >=217.5 ] [WindSpeed < 222.5] {marker-file: url('wind/220.svg');}
                [WindSpeed >=222.5 ] [WindSpeed < 227.5] {marker-file: url('wind/225.svg');}
                [WindSpeed >=227.5 ] [WindSpeed < 232.5] {marker-file: url('wind/230.svg');}
                [WindSpeed >=232.5 ] {marker-file: url('wind/EX230kt.svg');}
                [zoom >=7] { marker-width:70; marker-height:70;}
                [zoom >=6][zoom < 7]  { marker-width:50; marker-height:50;}
                [zoom >=5][zoom < 6]  { marker-width:40; marker-height:40;}
                [zoom >=4][zoom < 5] { marker-width:30; marker-height:30;}
                [zoom >=3][zoom < 4] { marker-width:25; marker-height:25;}
                [zoom < 3] { marker-width:20; marker-height:20;}
                marker-transform: rotate([WindDirection]+180);
		marker-allow-overlap: true;
		marker-opacity:0.75;
            }
```
           
I noticed that if I remove the marker-transform, the application stops crashing/freezing.
Currently using version 4.3.4 of the library with some custom changes and Xamarin.iOS.

What would be the best way to display a Tiles Layer like this and still make use of the transform to rotate the item? Is there a better and more efficient solution than markers?

**Comment by mtehver** [comment]
Good find. 'marker-transform' with different value for each feature causes rendering engine to build as many batches as there are features. Each batch has a large overhead for rendering and has large memory footprint. So the slow rendering is expected, although out-of-memory errors are somewhat unexpected.

I will look into this, I think rotation transforms can be 'baked into the' geometry and all the features could be put into a single batch.

**Comment by MatteoColombo** [comment]
We found out that the wind directions were float and not integers. By limiting the number of possible directions, the situation already improved, but it's still crashing on lower spec iPads

Would calling ClearAllCaches and ClearPreloadingCache help in this case? We could call it when we get a memory warning from the OS

Instead, is there a better way to draw these icons than using markers?

**Comment by mtehver** [comment]
@MatteoColombo I will push a fix for this next week. Assuming you are compiling SDK yourself, you can simply do a custom build with the fix included. Note that the fix will be in 'mobile-carto-libs' project and the change will be compatible with 4.4.3, not with 4.3.4. I will let you know once the fix is available.

**Comment by mtehver** [comment]
@MatteoColombo I have now pushed a fix for this. If you are willing to compile the SDK yourself, you can checkout the latest SDK version and after checking out submodules you need to do `cd libs-carto && git pull origin develop`. The fix will also be in 4.4.4 RC1, ETA is end of December.

The 'develop' version also fixes a regression in 4.4.x vs 4.3.x regarding transforms, previous 4.4.x versions required all transforms to have constant arguments. 'develop' version fixes this with a much better performance vs 4.3.x.

**Comment by MatteoColombo** [comment]
@mtehver Thanks! I built it for Xamarin iOS and so far it looks good, didn't manage to make it crash :) 
I'll build it also for UWP so that I can use the profiler to check the memory usage and compare it to the previous version.

**Comment by MatteoColombo** [comment]
@mtehver I'm struggling to build the UWP nuget package. What command should I use?

**Comment by mtehver** [comment]
@MatteoColombo Adding '--build-nuget' to the command-line arguments ('build-winphone.py') should do it. The current script uses Visual Studio 2022, though you can still use Visual Studio 2019, if you replace 'Visual Studio 17 2022' (in the 'build-winphone.py') with 'Visual Studio 16 2019'.

**Comment by mtehver** [comment]
4.4.4 with a fix is released now, closing this.
