### ISSUE TITLE
markers on VectorTileLayer being clipped at edge / bounds of tiles

### ISSUE THREAD

**Issue by dpattou** [CartoDB/mobile-sdk#478]
Hi, I'm having a small issue regarding distance markers I'm drawing on a map using a VectorTileLayer and a GeoJSONVectorTileDataSource and styling with carto CSS.

My CSS (see below) places a marker and some text on top of each other. The overlap properties seem to work and the text correctly shows on top of the 'circle' marker. However, it looks like the 'circle' marker gets clipped at the bounds of the tile it 'belongs to' and not at the bounds of the whole map view.

From what I can read at https://carto.com/developers/styling/cartocss, the markers should, by default, be clipped at the bounds of the map. Am I missing something or using this the wrong way ?

If I set the marker-clip CSS property, the 'circle' marker isn't clipped at the bounds of tiles anymore, but the text and the 'circle' marker don't overlap anymore (even with text-allow-overlap: true; and marker-allow-overlap: true;) and the text is hidden behind the 'circle marker...

Here's the CSS I'm applying to this particular feature, and a screenshot of a 'clipped' marker.

Should I be using a VectorLayer and not a VectorTileLayer ? It looks like I must use a VectorTileLayer with CartoCSS. I tried adding markers with overlapping text labels on a regular VectorLayer using code but all I got was a very blurry and unsatisfying result. 

Any help would be appreciated if I'm doing something wrong :)

Cheers,

Damien

```
#distancemarkers {
	[zoom>=8] {
		marker-width: linear([view::zoom], (10, 16),(18, 32));
		marker-height: linear([view::zoom], (10, 16),(18, 32));
		marker-line-width: linear([view::zoom], (10, 0.4),(18, 1.2));
		marker-line-color: @secondary;
		marker-placement: point;
		marker-fill: white;
		marker-allow-overlap: true;

		text-name: '[value]';
		text-face-name: @mont;
		text-placement: point;
		text-fill: @secondary;
		text-size: linear([view::zoom], (10, 10),(18, 14));
		text-allow-overlap: true;
	}
}
```

<img width="444" alt="Capture d’écran 2021-12-15 à 14 57 29" src="https://user-images.githubusercontent.com/6225820/146199622-20e2a0c3-c111-4aa9-b847-7a4352b8e295.png">

**Comment by mtehver** [comment]
@dpattou Can you try adding the following 2 lines to you CartoCSS?

```
marker-clip: false;
text-clip: false;
```

This behavior is somewhat unfortunate and it is documented here: https://github.com/CartoDB/mobile-sdk/wiki/CartoCSS-notes#label-rendering-mode-vs-simple-rendering-mode

**Comment by dpattou** [comment]
Thanks for your quick answer !

By adding these, the circle marker doesn't get clipped anymore, but somehow the text doesn't show (and is probably drawn beneath or hidden because of overlap?).

I have also tried playing with the :: notation to add another layer via CSS but to no avail.

I guess I could achieve what I need by adding the circle and text to two different layers but that wouldn't be a great solution.

**Comment by mtehver** [comment]
@dpattou You are correct, I had forgotten about label (marker/text) ordering not being respected when using this. This is a limitation of the SDK that will be fixed at some point.

If you can make your marker into a bitmap (or SVG file), then you can use 'shields'. Shields basically combine both background image and text and are used to show highway numbers, for example. The following snippet may help:

```
  shield-placement: point;
  shield-name: [value];
  shield-face-name: @mont;
  shield-fill: @secondary;
  shield-file: url('shield/circle.png');
  shield-size: 9.0;
```

The problem with shields is that you can not resize shield background image the same way as you can do with markers, you may need to create multiple images for different zoom levels.

**Comment by dpattou** [comment]
Thanks, this solution could work for me. However, the shield-fill property is applied to the whole 'circle' image i'm using and not just the text. Is there a specific image / color format I should use ?

**Comment by mtehver** [comment]
@dpattou You have found a bug :-), 'shield-fill' should not affect the color of the background image. It is a regression in 4.4.2 and 4.4.3, 4.4.1 handled it correctly.

So you can downgrade to 4.4.1 for now. The fix will be in 4.4.4 version, I plan to release first RC of 4.4.4 at the end of December.

4.4.4 will likely also have an option to manually configure vector tile 'buffer sizes' for `GeoJSONVectorTileDataSource`. By setting this to a larger value (default is 4 pixels), the original CartoCSS with separate marker/text would also work without clipping artifacts.

Thanks for reporting this.

**Comment by farfromrefug** [comment]
@mtehver can wait to see that buffer size option. could help in many use cases. 
ad we are here is there a true benefit in using shield over marker + label? let say we have 10000 of them are there some real optimisations with shield?

**Comment by dpattou** [comment]
No worries, and thank you for having a look. Great, we can wait until 4.4.4 is released.

**Comment by mtehver** [comment]
@farfromrefug This change is available in 'develop' branch. Before creating a `GeoJSONVectorTileLayer` layer, you can set its buffer size with `setDefaultLayerBuffer` method. Use 'buffer in tile pixels' as its argument, the default is 4.0. Note that it must be set before creating a layer.

**Comment by farfromrefug** [comment]
@mtehver question about tiles buffer. Is it something used too with vector tiles layers? It could help on an issue i have.
If it is used does it only influence the drawing of geometries or would it also have consequences on the geometry returned when searching vector tiles? I am trying to recreated routes geometry spanning over multiple tiles. Which is why i ask.

**Comment by mtehver** [comment]
@farfromrefug Its affecting actual vector tiles. With buffering, geometry is not clipped at exactly tile boundaries, but at a 'buffer distance' from tile boundaries. Thus if you want non-overlapping geometry in search results, you need to set buffer to 0. But that would cause artifacts when rendering the tiles, especially if you use clipped markers or wide lines. Also large buffer values make tiles larger and rendering slower, so it is a balancing act.

**Comment by farfromrefug** [comment]
@mtehver i understand. Could we get that `setDefaultLayerBuffer` for more data sources then? Maybe even all ? (my case it would be MBTiles data source).
Would it be possible to imagine a different value for rendering and for searching in vector tile layer?

**Comment by mtehver** [comment]
@farfromrefug Setting buffer size only makes sense when tiles are being built. The only datasource in the SDK that builds tiles is `GeoJSONVectorTileDataSource`. Other datasources simply fetch and forward already created tiles.

**Comment by mtehver** [comment]
@dpattou 4.4.4RC1 is now available and contains the fix. Final 4.4.4 is planned for mid-January.

**Comment by farfromrefug** [comment]
@mtehver thanks for the explanation. we ll close the issue as soon as @dpattou tested the new release

**Comment by dpattou** [comment]
Hi, just tested setting the default buffer size without touching the css and it no longer clips. I set the size to 32.0 as this is the maximum size of this marker.

Thanks, I'm closing this !
