### ISSUE TITLE
`findFeatures` does not seem to return all features

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#480]
I have a "route" layer in my mbtiles data representing osm routes.
What i am trying to achieve is create a polyline from a route.
A route is spanned across multiple tiles as shown here (red bold line):
<img width="389" alt="Screenshot 2021-12-26 at 17 29 43" src="https://user-images.githubusercontent.com/655344/147414395-b5aaae1b-5282-47d0-9883-6c449e3e4b09.png">

Now those routes have a `osmid:string` property allowing me to "match" them in the same route (used in the screenshot to highlight the route).
Also each route has an `extent` property giving the bounding box of the "whole route"
Now to create my polyline i use `findFeatures` in that way (javascript bindings)
```typescript
const mapProjection = mapContext.getProjection();
const searchService = new VectorTileSearchService({
    minZoom: 14,
    maxZoom: 14,
    layer
});
let extent: [number, number, number, number] = item.properties.extent as any;
if (typeof extent === 'string') {
    extent = JSON.parse(`[${extent}]`);
}
const boundsGeo = new PolygonGeometry<LatLonKeys>({
    poses: [
        { lat: extent[1], lon: extent[0] },
        { lat: extent[3], lon: extent[2] }
    ]
});
const featureCollection = await new Promise<VectorTileFeatureCollection>((resolve) =>
    searchService.findFeatures(
        {
            projection: mapProjection,
            filterExpression: `osmid='${properties.osmid}'`,
            geometry: boundsGeo
        },
        resolve
    )
);
```
My issue is that for some reason not all "parts" of the route are returned. We can see it in the screenshot on the blue line.
<img width="388" alt="Screenshot 2021-12-26 at 17 34 14" src="https://user-images.githubusercontent.com/655344/147414506-1a7a1598-0718-42a5-88ec-7d31707e5939.png">

I think the issue is internal.
To reproduce it your can run findFeatures with `osmid='-2535348'`
You can find a small mbtiles having the data here http://gofile.me/4pKGL/UJ1GNphg1

**Comment by mtehver** [comment]
This is really strange. Perhaps you are hitting 'max results' limitation (default value is 1000). You can try setting it to a larger value using `setMaxResults` of `VectorTileSearchService'.

If it does not help, could you create a reproducible minimal app in either Java/Kotlin/ObjC/Swift?

**Comment by farfromrefug** [comment]
@mtehver when you say max results it is max `feature` count results? Cause it returns 6 only ! The weirdest is that some are missed "in the middle" of the  geometry (seen by the long straight lines in blue in the last screenshot)

I ll try to create a reproducible example. In the meantime the issue seems a bit clear to me. Some tiles are ignore / not searched.
If you look at the screenshot below we can clearly see that missing part correspond exactly to tiles bounds.
<img width="767" alt="Screenshot 2021-12-27 at 10 30 11" src="https://user-images.githubusercontent.com/655344/147457678-4a66b48d-123b-4a3a-9006-e8345304ab78.png">
.

**Comment by farfromrefug** [comment]
@mtehver reproduced it in java.
Create the vector layer with this
```java
TileDataSource source = null;
MBVectorTileDecoder decoder = null;
try {
    source = new MBTilesTileDataSource( "/storage/10E7-1004/alpimaps_mbtiles/france/tiles.mbtiles");
    final File file = new File("/storage/10E7-1004/alpimaps_mbtiles/inner.zip");
    final FileInputStream stream = new java.io.FileInputStream(file);
    final DataInputStream dataInputStream = new java.io.DataInputStream(stream);
    final byte[] bytes = new byte[(int)file.length()];
    dataInputStream.readFully(bytes);
    decoder = new MBVectorTileDecoder(new CompiledStyleSet(new ZippedAssetPackage(new com.carto.core.BinaryData(bytes))));
} catch (IOException e) {
    e.printStackTrace();
}
VectorTileLayer backlayer  = new VectorTileLayer(source, decoder);
mapView.getLayers().add(backlayer);
```
the decoder style is this one
[Uploading inner.zip…]()
 
Now you can test the search with this:
```java
public void testVectoTileSearch(final VectorTileLayer layer, final Options options) {
    final VectorTileSearchService searchService = new VectorTileSearchService(layer.getDataSource(), layer.getTileDecoder());
    searchService.setMaxZoom(14);
    searchService.setMinZoom(14);
    MapPosVector vector = new MapPosVector();
    vector.add(new MapPos(5.853,45.096));
    vector.add(new MapPos(6.009,45.225));
    PolygonGeometry boundsGeo = new PolygonGeometry(vector);
    final SearchRequest request = new SearchRequest();
    request.setFilterExpression("layer::name='route' AND osmid=-2535348");
    request.setGeometry(boundsGeo);
    request.setProjection(options.getBaseProjection());
    new Thread() {
        public void run() {
            final VectorTileFeatureCollection result = searchService.findFeatures(request);
            new Handler(android.os.Looper.getMainLooper()).post(new Runnable() {
                @Override
                public void run() {
                    Log.d(TAG, "findFeatures done " + result.getFeatureCount());
                }

            });
        }
    }.start();
}
```
It returns only 6 features. And if you draw them (i tried to do it in java but it was too long to implement becaause i am missing methods to "flatten" a `MapPosVectorVector` to create a `Line`) you ll see there are holes. 
And i know those holes should be there because i can draw them with css.

**Comment by mtehver** [comment]
@farfromrefug You define your search area as a polygon with only 2 vertices (so basically as a straight line). Try this instead:
```
vector.add(new MapPos(5.853,45.096));
vector.add(new MapPos(6.009,45.096));
vector.add(new MapPos(6.009,45.225));
vector.add(new MapPos(5.853,45.225));
```

**Comment by farfromrefug** [comment]
@mtehver wow.dumb me! works perfectly now. sorry and thank you !
