### ISSUE TITLE
Shield Image bug after upgrading carto

### ISSUE THREAD

**Issue by safe-bug** [CartoDB/mobile-sdk#481]
Hello

We have recently upgraded our Carto version from 4.4.0 to 4.4.3 and we see some issues with Shield Image. It seems that the color that we set for the ShieldFill is also set for the ShieldImage (for example if we set the text color to black the image will get black too). It didn't happen in the previous versions, what is the problem?

Thanks

**Comment by mtehver** [comment]
@safe-bug This is a know regression in 4.4.3 and will be fixed in 4.4.4. You can also try first RC of 4.4.4, it should be stable.

**Comment by mtehver** [comment]
4.4.4 with a fix included is now available, closing this.

**Comment by safe-bug** [comment]
@mtehver Thanks
