### ISSUE TITLE
How to arrange VectorLayer on mapview

### ISSUE THREAD

**Issue by binu8051** [CartoDB/mobile-sdk#487]
Hi
How to place a VectorLayer on top of all layers?
how mapview displays VectorLayers over it?

will the mapview displays as per the add order?
mapView.getLayers().add(myVectorLayer1);

Thanks
Binu

**Comment by mtehver** [comment]
The answer is somewhat nuanced. The basic rule is that vector elements are drawn based on layer order, but this does not apply to billboards. Billboards retain their orientation when map is tilted and they are sorted based on their distance from camera. If you mix normal vector elements (points, lines, polygons) with billboards (markers, popups, texts), then normal elements are rendered first (according to layer order) and then billboards are rendered on top of them.

**Comment by binu8051** [comment]
Thanks, Need one for tip
Anyway to create Heatmap as shown in this image
![image](https://user-images.githubusercontent.com/8043738/153877125-ea2668f0-cd46-4380-8048-0d3fafc4eb62.png)

i am planning to show wind speed and direction like this. 

i can read the grib files which gives the wind speed and direction of a location (lat&lng)
from this values how we can draw the heatmap and wind direction.

Can it be done with this sdk, any tips/ideas please.

**Comment by binu8051** [comment]
Found a sample app with osmdroid, it has the following code.

`public class MapTileProviderGribFile extends MapTileProviderBase {
    public static final String LOG_TAG="MAPTILEPROVIDERGRIBFILE";
    private GribFileTileSource gribFileTileSource;
    private Context context;
    private int mode=0;
    private Worker worker;


    public MapTileProviderGribFile(Context context, GribFileTileSource gribFileTileSource) {
        super(gribFileTileSource);
        this.context=context;
        this.gribFileTileSource=gribFileTileSource;
    }


    @Override
    public Drawable getMapTile(MapTile pTile) {
        long time = System.currentTimeMillis();
        long x = System.nanoTime();
        Tile tile=new Tile(pTile);
        // this creates a MUTABLE bitmap
        Bitmap bitmap = Bitmap.createBitmap(tile.getSize(), tile.getSize(), Bitmap.Config.ARGB_8888);

        if (gribFileTileSource.getMinLon() < tile.getBoundingBox().getLonWest() &&
                gribFileTileSource.getMaxLon() > tile.getBoundingBox().getLonEast() &&
                gribFileTileSource.getMinLat() < tile.getBoundingBox().getLatNorth() &&
                gribFileTileSource.getMaxLat() > tile.getBoundingBox().getLatSouth()) {

                int size = tile.getSize();
                double minLat = tile.getBoundingBox().getLatSouth();
                double minLon = tile.getBoundingBox().getLonWest();
                double dLat = tile.getBoundingBox().getLatitudeSpan() / size;
                double dLon = tile.getBoundingBox().getLongitudeSpan() / size;

                int color;
                float u = Float.NaN;
                double lat, lon;
                try {

                    gribFileTileSource.setRecord(1);
                    for (int j = 0; j < size; j++) {
                        lat = minLat + j * dLat;
                        for (int i = 0; i < size; i++) {
                            lon = minLon + i * dLon;
                            u = gribFileTileSource.getValue(lat, lon);
                            color = gribFileTileSource.getColor(u);
                            bitmap.setPixel(i, size - j - 1, color);
                        }
                    }


                } catch (IOException e) {
                    //Log.d(LOG_TAG, e.getMessage());
                } catch (NotSupportedException e) {
                    //Log.d(LOG_TAG, e.getMessage());
                } catch (NoValidGribException e) {
                    //Log.d(LOG_TAG, e.getMessage());
                }
        } else {
            Canvas canvas = new Canvas(bitmap);
            Paint paint=new Paint();
            paint.setColor(Color.BLUE);
            canvas.drawLine(0, 0, 256, 0, paint);
            canvas.drawLine(0, 0, 0, 256, paint);

        }

        Drawable drawable= new BitmapDrawable(context.getResources(), bitmap);
        long end = System.currentTimeMillis();

        long res = end-time;
        Log.d(LOG_TAG, "time: "+res);


        return drawable;

    }
}
`
Can you help me to change it, with the loadTile()
How to convert this following lines,
```
int size = tile.getSize();
double minLat = tile.getBoundingBox().getLatSouth();
double minLon = tile.getBoundingBox().getLonWest();
double dLat = tile.getBoundingBox().getLatitudeSpan() / size;
double dLon = tile.getBoundingBox().getLongitudeSpan() / size;
```

**Comment by binu8051** [comment]
@mtehver please look this once, thanks.

**Comment by mtehver** [comment]
@binu8051 Sorry for the late response. I am not familiar with grib file, but assuming you just need to convert WGS84 coordinates to tile coordinates, I suggest taking a closer at `carto.utils.TileUtils` class.  `tile.getBoundingBox()` could be similar to `TileUtils.calculateMapTileBounds`. Not sure what `tile.getSize()` in osmdroid means, though.

**Comment by binu8051** [comment]
Thanks, one more help.
how to disable the titling of mapview with the 2 fingers touch.
i just want to do it programmatically by  mapView.setTilt()

**Comment by mtehver** [comment]
@binu8051 You can use something like this `mapView.getOptions().setTiltRange(new MapRange(45, 45))`

**Comment by binu8051** [comment]
> @binu8051 Sorry for the late response. I am not familiar with grib file, but assuming you just need to convert WGS84 coordinates to tile coordinates, I suggest taking a closer at `carto.utils.TileUtils` class. `tile.getBoundingBox()` could be similar to `TileUtils.calculateMapTileBounds`. Not sure what `tile.getSize()` in osmdroid means, though.

I tried with TileUtils.calculateMapTileBounds and some old code which i got it from the Nutiteq sample code 

**Output with TileUtils.calculateMapTileBounds**
![tilebounds](https://user-images.githubusercontent.com/8043738/157603681-91238ff3-2c11-4088-84d4-af8220bdc09c.jpg)
**Output with Sample code**
![sc1](https://user-images.githubusercontent.com/8043738/157603728-430b96fd-6487-4906-9f42-12229fa2093f.jpg)

why i am getting 2 different values seems the sample code is correct and the calculateMapTileBounds  giving me wrong values.
can you please check it.

i want the Maximum lat&lng and Minimum lat&lng for a Tile.

**Comment by binu8051** [comment]
Hi i changed the code with your correction, but i am getting the latitude value in negative. 
![sc1](https://user-images.githubusercontent.com/8043738/157802382-a8cc63a1-a55c-4628-af5e-4ff6567fc871.jpg)
**`TileUtils.calculateMapTileBounds` giving Y value in negative. so the final latitude value is also negative.**

**Comment by mtehver** [comment]
@binu8051 I guess your original tiles are vertically flipped. You should unflip them first, simply use `tile.getFlipped()` instead of `tile`.

**Comment by binu8051** [comment]
there is no function tile.getFlipped(), i am using latest SDK 4.4.5

**Comment by mtehver** [comment]
@binu8051 Sorry, you are right. `getFlipped` is not part of the public API, it is only available on C++ side. Simply do `MapTile flippedTile = new MapTile(tile.getX(), (1 << tile.getZoom()) - 1 - tile.getY(), tile.getZoom())`.

**Comment by binu8051** [comment]
Fine its worked, btw the correct code is
`MapTile flippedTile = new MapTile(tile.getX(), (1 << tile.getZoom()) - 1 - tile.getY(), tile.getZoom(), tile.getFrameNr());`
