### ISSUE TITLE
Load Maps API vector layers as one request

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#49]
Currently each layer from Maps API and viz.json is created as separate VectorTileLayer with own HttpTileDataSource. CARTO tile API supports also tile URL-s with several layers at once (layer IDs separated by comma, e.g. 1,2,3). This would give two advantages: much less HTTP traffic (faster map) and `x-allow-overlap: false;` would work across layers. Note that sometimes you map designer prefer  inside layer overlap control, like now; but cartocss has no parameter to control it.

For viz.json support need stable state of viz.json format. Can be done now for Maps API only.

**Comment by jaakla** [comment]
@mtehver this done in 4.0 for Maps API, right ?

**Comment by mtehver** [comment]
Yes, done. Closing.
