### ISSUE TITLE
Problems with Custom Raster Data

### ISSUE THREAD

**Issue by clownHHu** [CartoDB/mobile-sdk#491]
I am a graduate student who is new to the development of native mobile 3D maps. I was fortunate to have contact with this project. I compiled this project under windows and wanted to modify it, and ran the Android demo. I want to implement Custom Raster Data in the demo, but after entering the module, it prompts me to contact the DJ, what should I do? Thanks for answering!
![image](https://user-images.githubusercontent.com/49898875/156709936-4cf9d257-151a-41f7-9475-a41ba481129a.png)
![4c82735e9fea865e6f9b96ac5101134](https://user-images.githubusercontent.com/49898875/156709974-86559a27-c765-48b9-91ce-3a4bda0eb512.jpg)

**Comment by mtehver** [comment]
Hi. The online service that the sample uses no longer returns heightmap tiles, it returns bitmap tiles with the text you are seeing. Thus this is not a SDK issue.

But thanks for reporting this, I will check our samples and try to find a replacement service for heightmap tiles.

**Comment by clownHHu** [comment]
> 

Thanks for your reply. If I want to build a 3D map model using elevation data and satellite images, can I learn and implement it through our project?

**Comment by clownHHu** [comment]
> Hi. The online service that the sample uses no longer returns heightmap tiles, it returns bitmap tiles with the text you are seeing. Thus this is not a SDK issue.
> 
> But thanks for reporting this, I will check our samples and try to find a replacement service for heightmap tiles.

Thanks for your reply. If I want to build a 3D map model using elevation data and satellite images, can I learn and implement it through our project?

**Comment by mtehver** [comment]
@clownHHu CARTO Mobile SDK has limited support for elevation data. Basically you could use `HillShaderRasterTileLayer` as an overlay on top of normal layers, but there is no support for real 3D height fields.

**Comment by clownHHu** [comment]
> @clownHHu CARTO Mobile SDK has limited support for elevation data. Basically you could use `HillShaderRasterTileLayer` as an overlay on top of normal layers, but there is no support for real 3D height fields.

I understand, I will try to do some research on this, thanks for your reply.

**Comment by clownHHu** [comment]
> @clownHHu CARTO Mobile SDK has limited support for elevation data. Basically you could use `HillShaderRasterTileLayer` as an overlay on top of normal layers, but there is no support for real 3D height fields.

Excuse me , would you please tell me how to get a HillShaderRasterTileLayer on the server , It seems that the url ("http://tiles.wmflabs.org/hillshading/{zoom}/{x}/{y}.png") in the sample of AdvancemapAndroid is an error, it is not displayed .

**Comment by mtehver** [comment]
@clownHHu In order to use `HillShadeRasterTileLayer` you need heightmap tiles with special encoding. SDK supports MapBox defined encoding as described here: https://docs.mapbox.com/data/tilesets/guides/access-elevation-data/. If you register MapBox account, you could access the tiles using following url: https://api.mapbox.com/v4/mapbox.terrain-rgb/{zoom}/{x}/{y}.pngraw?access_token=YOUR_MAPBOX_ACCESS_TOKEN

The 'wmflabs' source you refer did not really encode height information and does not seem to work anymore anyway.

**Comment by farfromrefug** [comment]
@mtehver @clownHHu you can also use the free to `use https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png`.

**Comment by clownHHu** [comment]
> @clownHHu In order to use `HillShadeRasterTileLayer` you need heightmap tiles with special encoding. SDK supports MapBox defined encoding as described here: https://docs.mapbox.com/data/tilesets/guides/access-elevation-data/. If you register MapBox account, you could access the tiles using following url: [https://api.mapbox.com/v4/mapbox.terrain-rgb/{zoom}/{x}/{y}.pngraw?access_token=YOUR_MAPBOX_ACCESS_TOKEN](https://api.mapbox.com/v4/mapbox.terrain-rgb/%7Bzoom%7D/%7Bx%7D/%7By%7D.pngraw?access_token=YOUR_MAPBOX_ACCESS_TOKEN)
> 
> The 'wmflabs' source you refer did not really encode height information and does not seem to work anymore anyway.

Thank you so much.

**Comment by clownHHu** [comment]
> @mtehver @clownHHu you can also use the free to `use https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png`.

Thank you so much.
