### ISSUE TITLE
polygon-pattern alignment problem

### ISSUE THREAD

**Issue by txtdevelop** [CartoDB/mobile-sdk#497]
polygon-pattern alignment seems to be off

![polygon-pattern-artifacts](https://user-images.githubusercontent.com/21575735/168618255-a2397231-6e62-459b-8d61-e3324d410440.png)

map version: 
4.4.5

platform:
iOS

layer type: 
VectorTileLayer

style:
`
          #country-boundaries{
              line-cap: butt;
              line-color: rgba(212,212,212,0.3);
              line-width: 1.0;
              polygon-pattern-file: url('patterns/lines.png');
          }
`

pattern:
![lines](https://user-images.githubusercontent.com/21575735/168618320-b7bb9f5d-db30-4456-80ef-548dbb30b4e9.png)

I tried to add "polygon-pattern-alignment: global" to the style, but nothing changed
I also tried to use a 256x256 pattern, but the alignment problem still persist

**Comment by mtehver** [comment]
Thanks for reporting this. Indeed, any power-or-two sized pattern should work here, but currently due to internal scaling factor the alignment is off. Will try to fix this in 4.4.6 version.

**Comment by mtehver** [comment]
@txtdevelop 4.4.6-rc.1 is now released and includes a fix for this.

**Comment by mtehver** [comment]
Closing this, 4.4.6 has the fix.
