### ISSUE TITLE
Vector tile query by coordinates

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#50]
Add API to query vector data from VectorTileLayer by given point coordinates. Result - same as you get in the listener of #35

**Comment by mtehver** [comment]
Develop branch now includes Layer.simulateClick method that can be used to trigger listeners and receive results from all kinds of layers.

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1. SDK 4.1 provides two ways for this: search API and Layer.simulateClick.
