### ISSUE TITLE
AccessViolationException when having more than one MapView() in UWP Xamarin.Forms

### ISSUE THREAD

**Issue by l4nk4b3l** [CartoDB/mobile-sdk#513]
Issue:
The App will crash with the following Exception when having more than one MapView(). 

_System.AccessViolationException: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."_

I provided a [SampleApp.zip](https://github.com/CartoDB/mobile-sdk/files/9196790/SampleApp.zip) for easy reproduction of the issue. 

Steps to reproduce:
- Open SampleApp
- Click on the Button "Navigate" will cause AccessViolationException

Steps to reproduce:
- Open SampleApp
- Klick on the Button "Add second MapView" will cause AccessViolationException

Plattform: UWP
CartoMobileSDK.UWP: 4.4.6

**Comment by mtehver** [comment]
Hi. Indeed, thanks a lot for the sample app. I have reproduced the issue and it is related to interaction between Angle GLES UWP wrapper and threading. We will likely have a fix for this in 4.4.7 release.

**Comment by l4nk4b3l** [comment]
Can you tell me when release 4.4.7 is planned.

**Comment by mtehver** [comment]
@l4nk4b3l We plan to release RC next week and final 4.4.7 by the end of September.

**Comment by mtehver** [comment]
@l4nk4b3l 4.4.7RC1 is now available and should fix the issue.

**Comment by mtehver** [comment]
Closing this, 4.4.7 is now released.
