### ISSUE TITLE
Tip to load large number of points and Lines

### ISSUE THREAD

**Issue by binu8051** [CartoDB/mobile-sdk#514]
Hi
My app is for marine use and it need to load large amount of tracks, each tracks have more than 50 positions. i place 2 points at the ends and draw lines for the tracks. 
There are more than 2000 tracks and some times more than 4000 tracks.
The app can load it and at lower zoom levels the mapview seems to get Strucked sometimes freezes at lower devices with 2gb ram, but 4gb ram devices can handle it smoothly and sometimes they also get freezed at lower zoom levels.

Any tip to handle large number of tracks?

while the large number of markers are handled smoothly by using the clustering. 

Thanks

**Comment by mtehver** [comment]
I do not know how the line objects are created, but 4000 * 50 line segments should not cause performance issues. If you use `VectorLayer` for displaying your tracks, you should try to re-use styles for tracks as much as possible. If this does not help, I suggest looking into `VectorTileLayer` and `GeoJSONVectorTileDataSource`. `VectorTileLayer` should scale much better with large datasets.

**Comment by binu8051** [comment]
just found that there are 1,250,000 line segments, so around 600 segments for 2100 tracks. will this create any performance issue and yes i am using VectorLayer with LocalVectorDataSource.

i tried to display just the track with first and last point during the low zoom values (0 to 12) 
after zoom level 12 i remove the above layer and display the full layer with all segments.
This method works well.

any other way?
Thanks

**Comment by farfromrefug** [comment]
@binu8051 use GeoJSONVectorTileDataSource as @mtehver suggested

**Comment by binu8051** [comment]
@farfromrefug thanks, will try it.

**Comment by binu8051** [comment]
Hi @farfromrefug @mtehver is there any sample code which use GeoJSONVectorTileDataSource, cant find any.
Also will there be a lot of change in code for converting LocalVectorDataSource to GeoJSONVectorTileDataSource?

**Comment by mtehver** [comment]
@binu8051 Unfortunately our sample projects do not include any relevant samples. But you could follow the discussion in https://github.com/CartoDB/mobile-sdk/issues/344 to get some hints. This thread includes links to snippets that can be used.

**Comment by binu8051** [comment]
Thanks,
@farfromrefug can you share the cartocss code and program code which you have used in this video
https://github.com/CartoDB/mobile-sdk/issues/453#issuecomment-907790253
Since i want to create tracks only, 
i have the map positions on database and i am using a for loop to create line on LocalVectorDataSource.

Also weather the GeoJSONVectorTileDataSource support element click event, since i want to display the track details once it got touched.

Any help will be appreciated thanks.

**Comment by farfromrefug** [comment]
@binu8051 I dont use it in Java but within Nativescript using a JS wrapper so the code i use wouldnt help you that much. But can search in this repo https://github.com/Akylas/alpimaps. Everything is in there

**Comment by binu8051** [comment]
ok thanks, i managed to load the tracks and now need to change the track color.

**Comment by binu8051** [comment]
@mtehver Hi, your sample code at https://gist.github.com/mtehver/991e4e4e7de8a524ded62a4edc88ed62 helps me alot.
Now i can display the tracks on the map.
But all the tracks are in same color. i have total 24colors.
how to select the color of the tracks as per the value.? i am confused in this part.
i have given the code which i am using.
singletrack.color; holds a value from 0 to 23
How to set this color to the tracks, please help me.
```
private Realm realm = null;
ZippedAssetPackage assetPackage = new ZippedAssetPackage(AssetUtils.loadAsset("style.zip"));
CompiledStyleSet styleSet = new CompiledStyleSet(assetPackage);
final MBVectorTileDecoder decoder = new MBVectorTileDecoder(styleSet);
GeoJSONVectorTileDataSource dataSource = new GeoJSONVectorTileDataSource(0, 19);
FeatureVector features0 = new FeatureVector();

realm = Realm.getDefaultInstance();
realm.refresh();
RealmResults<TrackModelR> allTracks = realm.where(TrackModelR.class).sort("start_time", Sort.DESCENDING).findAll();
MapPosVector linePosess;
long track_id;
long track_color;
for(TrackModelR singletrack : allTracks) {
	MapPosVector poses = new MapPosVector();
	track_id = singletrack.id;
        track_color = singletrack.color;
	//add Green Point on start point
	poses.add(new MapPos(singletrack.start_lon, singletrack.start_lat));
	RealmResults<TrackPositionsModelR> selTracks = singletrack.locations.sort("timestamp", Sort.ASCENDING);
	for(TrackPositionsModelR selTrack : selTracks) {
		poses.add(new MapPos(selTrack.longitude, selTrack.latitude));
	}
	poses.add(new MapPos(singletrack.end_lon, singletrack.end_lat));

	LineGeometry poly = new LineGeometry(poses);
	VariantObjectBuilder builder = new VariantObjectBuilder();
	builder.setLong("id", track_id);
	features0.add(new Feature(poly, builder.buildVariant()));
}
int layerId0 = 0;
try {
	layerId0 = dataSource.createLayer("line0");
	dataSource.setLayerFeatureCollection(layerId0, new EPSG4326(), new FeatureCollection(features0));
} catch (Exception e) {
	Log.e("", e.toString());
}
realm.close();
VectorTileLayer layer = new VectorTileLayer(dataSource, decoder);
mapView.getLayers().add(layer);
```
My style.json
```
{
  "layers": ["line0", "line1", "line2", "line3", "line4", "line5", "line6", "line7", "line8", "line9", "line10", "line11", "line12", "line13", "line14", "line15", "line16", "line17", "line18", "line19", "line20", "line21", "line22", "line23"],
  "styles": ["style.css"],
  "nutiparameters": {
    "selection_id": {
      "default": 0
    }
  }
}
```
My style.css
```
@color0: #F907E5;
@color1: #02F206;
@color2: #3E3F3A;
@color3: #F6FF05; 
@color4: #D32A35;
@color5: #02F7EF;
@color6: #115CFF;
@color7: #05070C;     
@color8: #E2A414;
@color9: #5FC0D8;
@color10: #00D300;
@color11: #CEB306;
@color12: #F27210;
@color13: #EAA612;
@color14: #353535;
@color15: #EF1321;
@color16: #76BC79;
@color17: #034A44;
@color18: #414206;
@color19: #CE5D3D;
@color20: #825D0C;
@color21: #3C018D;
@color22: #C60F53;
@color23: #2979FF;
		
#line0 {
	line-color: @color0;
	line-width: 8;
}
#line1 {
	line-color: @color1;
	line-width: 8;
}
#line2 {
	line-color: @color2;
	line-width: 8;
}
#line3 {
	line-color: @color3;
	line-width: 8;
}
#line4 {
	line-color: @color4;
	line-width: 8;
}
#line5 {
	line-color: @color5;
	line-width: 8;
}
#line6 {
	line-color: @color6;
	line-width: 8;
}
#line7 {
	line-color: @color7;
	line-width: 8;
}
#line8 {
	line-color: @color8;
	line-width: 8;
}
#line9 {
	line-color: @color9;
	line-width: 8;
}
#line10 {
	line-color: @color10;
	line-width: 8;
}
#line11 {
	line-color: @color11;
	line-width: 8;
}
#line12 {
	line-color: @color12;
	line-width: 8;
}
#line13 {
	line-color: @color13;
	line-width: 8;
}
#line14 {
	line-color: @color14;
	line-width: 8;
}
#line15 {
	line-color: @color15;
	line-width: 8;
}
#line16 {
	line-color: @color16;
	line-width: 8;
}
#line17 {
	line-color: @color17;
	line-width: 8;
}
#line18 {
	line-color: @color18;
	line-width: 8;
}
#line19{
	line-color: @color19;
	line-width: 8;
}
#line20 {
	line-color: @color20;
	line-width: 8;
}
#line21 {
	line-color: @color21;
	line-width: 8;
}
#line22 {
	line-color: @color22;
	line-width: 8;
}
#line23 {
	line-color: @color23;
	line-width: 8;
}
```

**Comment by binu8051** [comment]
Also how can i add/delete a single track?
Thanks for your time.

**Comment by mtehver** [comment]
@binu8051 Regarding coloring your tracks, you can define rules based on the properties of your features. Also, it makes more sense to define 1 layer with appropriate property you can use for coloring your tracks, instead of 24 layers.

Regarding adding/updating individual features - there is no direct API support for this as changing a single feature requires rebuilding vector tiles this feature affects. So you simply need to update all the features even if only a single feature changes. Thus with vector tiles there is a tradeoff between rendering speed and data synchronization speed.

**Comment by binu8051** [comment]
Thanks, the GeoJSONVectorTileDataSource  is very smooth even with 10k tracks.
For adding i have created a new layer and display it, but for editing/deleting i have to reload all tracks and it take around 30seconds to reload all.
Is creating 24layers will create any performance issues?
if not i can reload only that layer which matches that color of edit/delete tracks so it will take less time to reload.
any other way?
Is there any plan for direct support for edit/delete a individual features?

**Comment by binu8051** [comment]
@mtehver any help.

**Comment by mtehver** [comment]
@binu8051 Regarding 24 layers, most likely this will be ok, unless you target really low-end devices. Regarding support for editing individual features for `GeoJSONVectorTileDataSource` - no, this is not planned. `VectorTileLayer` is intended for maximum performance for large static datasets and there are no plans to change that.

**Comment by binu8051** [comment]
Thanks for the Tips

**Comment by binu8051** [comment]
Hi
i used the above code and few users complaint that the tracks are blinking and i have attached the sample videos.
Can't guess the problem, can @mtehver check it please.

https://user-images.githubusercontent.com/8043738/220123791-4de6d4fa-b771-4d21-935c-957d0d435598.mp4

https://user-images.githubusercontent.com/8043738/220123806-8d10754e-92bf-4631-ac82-0da6c14b530b.mp4

**Comment by binu8051** [comment]
@mtehver please check this issue.

**Comment by baneyue** [comment]
is there a sample to use GeoJSONVectorTileDataSource in android ?
I encountered the same problem, I need to display a large number of line segments, and using localVectorDataSource will result in faults

**Comment by baneyue** [comment]
`
        Feature feature = new Feature(line.getGeometry(), new Variant(line.getMetaData()));
        featureVector = new FeatureVector();
        featureVector.add(feature);

        GeoJSONVectorTileDataSource mGeoJsonDataSource = new GeoJSONVectorTileDataSource(10, 24);
        FeatureCollection featureCollection = new FeatureCollection(featureVector);
        try {
            int index = mGeoJsonDataSource.createLayer("test");
            mGeoJsonDataSource.setLayerFeatureCollection(index, projection, featureCollection);
        } catch (Exception e) {
            LogF.e("TAG", e.getMessage() + "", e);
        }
        CartoCSSStyleSet css = new CartoCSSStyleSet(TrackCss.INSTANCE.lineStyle(10);
        MBVectorTileDecoder tileDecoder = new MBVectorTileDecoder(css);
        VectorTileLayer geoJsonPointsVectorLayer = new VectorTileLayer(mGeoJsonDataSource, tileDecoder);
        geoJsonPointsVectorLayer.setSynchronizedRefresh(true);
        MapViewTools.addLayer(geoJsonPointsVectorLayer);
`
Can the VectorTileLayer‘s  width be synchronized and scaled proportionally ?

**Comment by mtehver** [comment]
@baneyue Can you be more specific? Do you mean line widths being proportional to zoom level in some way? In that case yes, you can use expressions in your CartoCSS.  For example:
```
line-width: linear([view::zoom], (1.0, 0.0), (10, 5.0));
```
This would create a linear line widening effect starting from zoom level 1 (width 0) up to zoom level 10 (width 5).

**Comment by baneyue** [comment]
We need to do a high-precision display to show the true width of the car, such as a 3-meter wide car. We need to draw a 3-meter wide driving trajectory on the map instead of using pixels. When scaling, the trajectory can also be scaled synchronously. Do you have any good plans.

**Comment by baneyue** [comment]
> @baneyue Can you be more specific? Do you mean line widths being proportional to zoom level in some way? In that case yes, you can use expressions in your CartoCSS. For example:
> 
> ```
> line-width: linear([view::zoom], (1.0, 0.0), (10, 5.0));
> ```
> 
> This would create a linear line widening effect starting from zoom level 1 (width 0) up to zoom level 10 (width 5).

I know what you mean, but this width's unit maybe pixels，that not precision of the map, i need display on map a true width.
actually, True width in map plane coordinates.  Do you know what I mean？

**Comment by mtehver** [comment]
@baneyue You can use any expression for width. If you want your line width to be proportional to the actual scale, use something like this:

```
line-width: pow(2.0, [view::zoom] - 14.0);
```

This makes the width to be 1.0 at zoom=14, 0.5 at zoom=13 and 2.0 at zoom=15.

**Comment by farfromrefug** [comment]
@mtehver could be nice to have a utility method to convert pixel to meters in cartocss. Dont you think ?

**Comment by mtehver** [comment]
@farfromrefug Unfortunately for 'planar' maps that would be a function depending on geographic coordinates, which may differ for very large features (for example, a line from equator to near pole).

**Comment by farfromrefug** [comment]
@mtehver you are right ! Though would that method be linear depending on the zoom? I mean seeing the view size we never see a big area so that the line would have a different width at top and bottom of the screen (I think). So maybe a approximation would be enough (like using the focus lat Lon to compute)

**Comment by binu8051** [comment]
Hi, whats the use if setSimplifyTolerance.
Whats the value i can set for low ram devices.
I am using this code
```
if (Utils.getRam(MainActivity.this) >= 2)
           geotracksdataSource.setSimplifyTolerance(2.0f);
else
           geotracksdataSource.setSimplifyTolerance(5.0f);
```
will it help me with large points and lines.

**Comment by mtehver** [comment]
@binu8051 `setSimplifyTolerance` does not help much with memory usage - all the data inserted into data source is still kept at original resolution. Just for rendering purposes the geometry is dynamically simplified based on zoom level.
