### ISSUE TITLE
LineStyleBuilder with setBitmap method error render

### ISSUE THREAD

**Issue by vTechGIS** [CartoDB/mobile-sdk#515]
I am using "LineStyleBuilder" with "setBitmap()" method for Line element vector.
However I see that the SDK is giving an error when rendering the bitmap displayed for Line with multiple vertex. If there are only 2 vertex there is no error. Could you help me fix this error?

I'm using Carto Mobile SDK v4.6.6. In my screenshot Green line has no error and Purple line has rendering error

![1660727076009](https://user-images.githubusercontent.com/6292758/185081557-5cda172c-0d79-4a3f-a52e-10089d36dc28.jpg)

**Comment by mtehver** [comment]
I suggest setting style `lineJoinMode` to `LINE_JOIN_TYPE_NONE` when patterns are used. In general this is a known issue but has low priority in our TODO list.

**Comment by vTechGIS** [comment]
> I suggest setting style `lineJoinMode` to `LINE_JOIN_TYPE_NONE` when patterns are used. In general this is a known issue but has low priority in our TODO list.

I fixed it with style LINE_JOIN_TYPE_NONE., Thank you so much,
