### ISSUE TITLE
API for offest TileLayer ?

### ISSUE THREAD

**Issue by vTechGIS** [CartoDB/mobile-sdk#518]
I am looking for a way to set offset map tile X and Y with custom spacing for TileLayer display.
Is this possible? or can give me some solution suggestions.

Thank you very much

**Comment by mtehver** [comment]
There is no API support for this. If you use `VectorTileLayer`, then it is possible to offset geometry a bit, but I can not think of anything else.

**Comment by vTechGIS** [comment]
> 

Thank you sir
