### ISSUE TITLE
Map is not scaling with correctly on UWP

### ISSUE THREAD

**Issue by l4nk4b3l** [CartoDB/mobile-sdk#530]
Hi,

I found an issue. The MapView is not working properly when Windows Scaling is enabled. In my case,  scaling is set to 150%.

Steps to reproduce:
1. Download .NET (Xamarin and UWP) sample app: https://github.com/CartoDB/mobile-dotnet-samples
2. Update NuGet Package from 4.4.5 to 4.4.7 or 4.4.6
3. Start UWP 
4. Marker is not centered and map is zooming with an offset 

Plattform: UWP
CartoMobileSDK.UWP: >= 4.4.6

Actual  (Windows Scaling 150%)
<img width="768" alt="150" src="https://user-images.githubusercontent.com/10784752/212345806-4e5d6642-81ce-43a1-8977-5a14c95cdd48.png">

Expected (Windows Scaling 100%)
<img width="768" alt="100" src="https://user-images.githubusercontent.com/10784752/212345803-d2fbccb6-833c-48b6-abd7-a4435b996082.png">

**Comment by mtehver** [comment]
Thanks for reporting this. I have pushed a fix for this to the master branch.

**Comment by l4nk4b3l** [comment]
Works fine. 
Are there any plans on releasing a new version?
I am having trouble building my own release.

**Comment by mtehver** [comment]
@l4nk4b3l Yes, there is a plan for 4.4.8 release, but this UWP bug is the only important one at the moment, so I would wait a bit more before doing the release.

**Comment by ZakMcGrabben** [comment]
Any updates on this issue?

**Comment by mtehver** [comment]
Thanks for reminding this. I have pushed a new version (4.4.8-rc.1) that includes fix for the issue.
