### ISSUE TITLE
How to draw a circle with radius of 10meter

### ISSUE THREAD

**Issue by binu8051** [CartoDB/mobile-sdk#544]
Hi
Any code for drawing a circle with radius of some value.
Thanks

**Comment by binu8051** [comment]
@farfromrefug @mtehver please help

**Comment by farfromrefug** [comment]
@binu8051 https://github.com/Akylas/alpimaps/blob/e69b97821b1fc24c80c3efa074896fd8627c9c16/app/mapModules/UserLocationModule.ts#L51

**Comment by binu8051** [comment]
Thanks @farfromrefug 
so there is no straight way, 
we need to create points and connect the points using line.

**Comment by farfromrefug** [comment]
@binu8051 indeed

**Comment by binu8051** [comment]
Thanks, this is my code.
`private MapPosVector createCircle(MapPos circlePos, double radius) {
        int numPoints = (int) Math.min(radius * 8, 100);
        MapPosVector linePositions = new MapPosVector();
        for (int i = 0; i <= numPoints; i++) {
            double angle = 2.0 * Math.PI * i / numPoints;
            double dx = radius * Math.cos(angle);
            double dy = radius * Math.sin(angle);
            double y = circlePos.getY() + dy;
            double x = circlePos.getX() + dx;
            MapPos circlePoss = projection.toLatLong(x, y);
            circlePoss = projection.fromWgs84(new MapPos(circlePoss.getY(), circlePoss.getX()));
            linePositions.add(circlePoss);
        }
        return linePositions;
    }`
