### ISSUE TITLE
New offline package format

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#56]
Features / requirements:
* package map tiles, search indexes and routing graph in single package. Not all parts need to present in the package. Possibly a metadata file is needed also
* streaming - enables showing/reading map while downloading. Download load zoom levels first.
* better overall compression, smaller packages. Can be at least 1/3 smaller. Avoid duplication of data (attributes etc)
* maybe support topological data model, reduces data amount for some datasets.
* data obfuscation (for private data); as supported also now in SDK packages.

Most of it cannot be done with current gzipped mbtiles, so new container is needed.

**Comment by mtehver** [comment]
Just a comment: streaming would require a container format, mbtiles will not work. Also, current container is mbtiles of gzipped tiles.

**Comment by jaakla** [comment]
Issue moved to [CartoDB/mobile-sdk-extensions #8](https://github.com/CartoDB/mobile-sdk-extensions/issues/8) via [**ZenHub**](https://www.zenhub.com/)
