### ISSUE TITLE
Animate added points and markers

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#58]
Use "scale in" appear animation for Points and Markers added to the map. API proposal: VectorLayer property setAppearAnimation(sec).

**Comment by mtehver** [comment]
Implemented as marker styling options in features/animatedvectorelements. Currently only for billboards.

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1. Closing this as the important case (Markers/Popups) is implemented. Can generalize this geometry elements later, if really needed.
