### ISSUE TITLE
API methods to query offline package tile availability

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#60]
Add two methods for developers to help offline package management.

_a) remote availability:_
**PackageManager.SuggestPackage(MapPos)** - list of offline packages which are available for given location, sorted by relevance (smaller package first). Same done in app level: https://github.com/CartoDB/mobile-android-maps-app/blob/master/nuticomponents/src/main/java/com/nutiteq/nuticomponents/PackageSuggestion.java#L100 . 

_b) local availability:_
**PackageManager.OfflineDownloaded(MapPos, zoom)** - check if offline map is available (i.e. the tile is downloaded in any downloaded package) for given location and zoom.

Use case: periodically app checks if the offline map is downloaded in area of interest (where user is browsing, or where is loading data), using (b) local availability query; if data is not downloaded, then checks using (a) remote availability method which package to be suggested to be downloaded. 

Local availability works for both country and bbox packages. Remote availability for only country packages.

**Comment by mtehver** [comment]
Implemented proposal in feature/packagemanager branch with minor differences: added Projection argument to methods, OfflineDownloaded is implemented in more general form: isAreaDownloader(MapBounds area, int zoom, Projection proj)

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1
