### ISSUE TITLE
Shared dictionary for offline packages to improve compression

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#69]
To do:

- [x] Create script for extracting shared dictionary from tiles
- [x] Modify tile packager script and related scripts to store the dictionary in 'shared_zlib_dict'
- [x] UpdateSDK to support shared dictionaries for offline map packages

**Comment by mtehver** [comment]
SDK now includes forward-compatible support for this. The dictionary for each package must be kept in 'metadata' table under 'shared_zlib_dict' value.

**Comment by mtehver** [comment]
Closing this as the shared dict packages are ready and available from SDK snapshot.
