### ISSUE TITLE
Snap to road API 

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#7]
Useful for GPS smoothing. Use vector tiles from offline map packages or online/cached vector tiles. 

Input : x,y, tolerance (in meters); output: adjusted x,y and maybe snap distance (in meters).

**Comment by mtehver** [comment]
Comment: routing packages are a better fit for this - provide more precise snapping and probably faster (with r-tree indexes)

**Comment by mtehver** [comment]
This is available in 4.1.1 when using Valhalla routing engine ('map matching' API). Thus closing.
