### ISSUE TITLE
Display background till map loads

### ISSUE THREAD

**Issue by snijsure** [CartoDB/mobile-sdk#71]
Is there a way to display  background image on the map, till actual map gets downloaded?

Right now our app (lonely planet guides) shows empty grid till the map for specific bounding box gets downloaded. I was wondering if there is way to display background image till download finishes?

**Comment by mtehver** [comment]
You can register a listener (TileLoadListener) to TileLayer instances that receive notifications when tile loading is complete. Perhaps you can use this?

**Comment by snijsure** [comment]
@mtehver 

Actually I was looking for background that different from current "grid" background. I found a way to do this.
`        
Options options = mapView.getOptions();

        android.graphics.Bitmap bMap = BitmapFactory.decodeResource(getResources(), R.drawable.marker);
        com.carto.graphics.Bitmap cartoBitmap = BitmapUtils.createBitmapFromAndroidBitmap(bMap);
        options.setBackgroundBitmap(cartoBitmap);`
