### ISSUE TITLE
Polygon/line batching

### ISSUE THREAD

**Issue by mtehver** [CartoDB/mobile-sdk#73]
The following pattern is quite common in CartoCSS (polygon and line symbolizers within a single rule):

```
#layer {
  line-color: #ff0;
  polygon-color:#000;
}
```

Unfortunately this makes vector tile renderer to switch shaders at each element, thus causing many draw calls and slowing down rendering to unusable speed in some cases. It is possible to generalize renderer batching and use line shader for polygons. So do it.

**Comment by jaakla** [comment]
This is client-side fix for https://github.com/CartoDB/cartodb/issues/7723 ?

**Comment by mtehver** [comment]
Merged to master.
