### ISSUE TITLE
Built-in zoom gestures

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#81]
- [x] Double-tap - zoom in 1 zoom level
- [x] Two-finger (dual) tap - zoom out 1 zoom level
- [x] Double-tap+pan - single-finger zoom. Up: zoom-out, down: zoom-in.

By default activated, add Options API method to disable each of them.

**Comment by mtehver** [comment]
Implemented double-tap and dual-tap in feature/zoomgestures branch. By default, both options are DISABLED as enabling them could break existing apps as the click events are handled and hidden from the app.

Double-tap + pan requires new state and state transitions in touch handler and as such, it needs much more time and really careful implementation to avoid any regressions.

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1
