### ISSUE TITLE
Refactor & update documentation

### ISSUE THREAD

**Issue by Nikituh** [CartoDB/mobile-sdk#86]

**Comment by Nikituh** [comment]
* Initial ideas: https://docs.google.com/document/d/1PsMD5R-oxIukHqhythMLZXujAPtVpxnvcxOY_unfY18/edit

**Comment by jaakla** [comment]
Make "getting started" shorter - map works
Basic tasks - own objects on map, my location, base map change
More complex tasks - all others, separate tutorials, in future goes to "Learn" section.

**Comment by jaakla** [comment]
Reviewed the gdoc and added my comments, @Nikituh can proceed with implementation of it.

**Comment by Nikituh** [comment]
Partly initialized (separated package manager & routing sections, created geocoding section), but currently not in scope: removing from project list

**Comment by Nikituh** [comment]
Scope has somewhat changed, rendering this issue irrelevant. Closing
