### ISSUE TITLE
Implement procedural 'Null tile' bitmap and sky bitmap

### ISSUE THREAD

**Issue by mtehver** [CartoDB/mobile-sdk#88]
The default bitmaps are well suited only for nutibright style and look ugly when dark style is used.

**Comment by mtehver** [comment]
Implemented in develop branch

**Comment by kochizufan** [comment]
Hi

I want to allow transparent image to 'null tile', to show the background view at 'null tile' area.
For my use case, background view is not static image but dynamic image (like movie), so make background as transparent is necessary.
Is this possible?

**Comment by mtehver** [comment]
Hi, are you using raster tiles with transparency? There are couple of things that need to be done to make this work - first you need to call Options.setBackgroundBitmap(null) and then you need to configure MapView to support transparency, as MapView is derived from GLSurfaceView. You can find the required steps from here: http://stackoverflow.com/questions/16762633/android-glsurfaceview-transparent-background-without-setzorderontop

**Comment by kochizufan** [comment]
Hi,

Thank you for helpful answer, and apologies I might mistake the matter of this issue..I thought this issue is related with this issue but it looks different issue..
But anyway thank you to kindly answer my question.

And if allowed, one more thing, I understand how to do it in Android, but how about iOS? 
I found Options.setBackgroundBitmap(null) works same in iOS, GLSurfaceView is not same in iOS..

**Comment by mtehver** [comment]
Hi,

unfortunately my proposal did not work even on Android, as the GL viewport was always cleared with white color. I have just implemented a 'fix' for this. The following snippet shows how to do it on iOS:

```
    [[mapView getOptions] setClearColor:[[NTColor alloc] initWithR:0 g:0 b:0 a:0]];
    [[mapView getOptions] setBackgroundBitmap:nil];
    [[mapView getOptions] setSkyBitmap:nil];
    mapView.opaque = NO;
    mapView.backgroundColor = [UIColor clearColor];
```
Unfortunately 'setClearColor' is a new method implemented just now, we do not have a public build supporting this yet.

**Comment by kochizufan** [comment]
Hi,

Thank you very very much for updating, I'm looking forward to it comes to public release,
And actually I'm using Xamarin SDK, so please implement it also to Xamarin's..

**Comment by mtehver** [comment]
This is implemented for all platforms, including Xamarin. Note that the develop branch will be released as 4.1.x, so this will not be available in any 4.0.x release.

**Comment by jaakla** [comment]
SDK 4.1.0 alpha version for Xamarin can now be taken from *nuget* (for [iOS][1] or [Android][2]), just enable "Pre-release" versions in nuget package loader and pick 4.1.0-alpha-8 or newer for **CartoMobileSDK**.

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1
