### ISSUE TITLE
Proposal for CartoCSS extension

### ISSUE THREAD

**Issue by mtehver** [CartoDB/mobile-sdk#9]
**Problem**

CartoCSS defines properties only at discrete zoom levels. This poses problems several problems:
- Large number of rules are needed when road widths need to be defined, for example.
- It is not possible to define parameter values for fractional zoom levels
- Transition between zoom levels are discrete, non smooth

**Proposal**

Add support for interpolation functions that can be used for line width calculation and color calculation:

```
line-width-func: <INTERPOLATOR>
color-width-func: <INTERPOLATOR>

<INTERPOLATOR> :=  step(<KEY_VALUE_PAIRS>) | linear(<KEY_VALUE_PAIRS>) | cubic(<KEY_VALUE_PAIRS>)

<KEY_VALUE_PAIRS> := <KEY_VALUE_PAIR> | <KEY_VALUE_PAIR>, <KEY_VALUE_PAIRS>
<KEY_VALUE_PAIR> := <FLOAT_OR_INTEGER>, <CSS_VALUE>
```

for example,

```
line-width-func: linear(0, 1.0, 2, 5.0)
```

defines line-width=1.0 at zoom 0, line-width=5.0 at zoom 2 and implicitly (by linear interpolation) line-width=3.0 at zoom=1. At zoom > 2, the last value (5.0) is used.

Similarly,

```
line-color-func: linear(0, #000, 1, #888)
```

defines line-color=#444 at zoom 0.5.

The proposal defines 3 types of interpolators: step (basically this is equivalent to current CartoCSS, but provided for orthogonality), linear (piecewise linear interpolator) and cubic (cubic interpolation with tangent continuity, if at least 4 points are defined. If 3 points are defined, quadratic interpolation is used and for 2 points this is equivalent to linear interpolator).

If both line-width and line-width-func properties are defined (or line-color and line-color-func), then line-width-func takes priority and line-width is ignored. This provides better backward compatibility with authoring tools.

In addition to line-color-func, similar properties should be defined for polygons, markers, etc.

**Example**

Old style:

```
#road {
  [zoom = 0] { line-color: #fff; line-width: 0.5 }
  [zoom = 1] { line-color: #eee; line-width: 1.0 }
}
```

New style:

```
#road {
  [zoom = 0] { line-color: #fff }
  [zoom = 1] { line-color: #eee }
  line-width-func: linear(0, 0.5, 1, 1.0)
}
```

or 

```
#road {
  line-color-func: linear(0, #fff, 1.0, #eee)
  line-width-func: linear(0, 0.5, 1, 1.0)
}
```

**Comment by jaakla** [comment]
Lets re-activate this to draft a solution.
a) **Turbocarto**, server side processor properties:
* Processor knows whole dataset and all possible values, so ramp can be calculated
* Processor knows all possible zoom values, and there is limited number of them
* Based on previous two Turbocarto can be pre-processed to CartoCSS in server side

b) **Renderer** (e.g. Mobile SDK), client side reader properties:
* Do not have all possible values, knows only values within current map tile which does not help at all. So something like https://github.com/CartoDB/turbo-carto/blob/e0347dd6f2bcaa51e5f4a47b800f3da28dc8d824/examples/readme/example-4.css can not be done in client side and remains to Turbocarto.
* Zoom is continuous, no list of possible values; also know zoom only during rendering of specific frame.
* So this cannot be preprocessed in server and not even in client side.

Syntactically and even semantically _linear() / ramp() etc_ functions seem to be similar, the difference comes from specific values (zoom vs view::zoom, if category() is used with a variable or not). This can be confusing for users, and even for ourselves. Turbocarto should know the difference and preprocess (i.e. convert to cartocss) some function calls, and keep others untouched, so these can be handled in the client side. This may even depend on client - for some legacy clients (using Leaflet and raster tiles) all functions should be converted to cartocss, others like mobile SDK support already the functions in client side, and some new ones like vector web client will very probably support similar functions.

Adding @donflopez - how above would work from web vector rendering perspective?

**Comment by javisantana** [comment]
So your proposal is:

- ramp for server side (per dataset evaluation)
- linear for client side (per frame evaluation)

**Comment by jaakla** [comment]
In principle, yes.  Literally these two names mean more or less same, so maybe need to find out something to make the difference clear, eg. use turbo_ramp() / dynamic_ramp().

In parallel all need to keep working:
* builder css editor -> builder web preview (needs serverside/standard cartocss)
* builder css editor -> maps api -> raster-based web client (needs serverside/standard cartocss)
* builder css editor -> maps api -> mobile client (needs clientside/extended cartocss)

Here seems to be challenge that in the maps api cases turbocarto is involved before maps api, but the result css should be different based on final client.

Out of the box idea: instead of trying to extend cartocss in a complex way that it magically works for both rendering modes generate separate css-s already in the Builder level. "style value editing gui" would be more or less same, but instead of one "cartocss" there would be "raster cartocss" and "vector cartocss" options (or sub-selections, maybe with better names), with slightly different css based on client capabilities. So advanced user/developer can manually finetune the css for both options. This would require also web preview for both modes. In longer term the raster css could be deprecated together with raster/server-based rendering in general.

**Comment by mtehver** [comment]
A comment - linear and ramp are different, linear is denotes linear interpolation while ramp provides value-based lookup. On the SDK side, step function is similar to ramp, but without the mapping part.

I think a solution would be to extend to TurboCarto parser to accept [view::zoom], linear, step and other SDK extensions and simply 'pass them through' - TurboCarto could output the expressions to postprocessed CartoCSS as they were in preprocessed CartoCSS. In that case the SDK extensions could be used in mobile apps. The problem is that these extensions do not work when generating raster tiles as Mapnik does not support these.

**Comment by javisantana** [comment]
@mtehver that's not true, ramp could be linear interpolation.

one question, what problem you see on using the current `zoom` variable?

**Comment by mtehver** [comment]
@javisantana You mean using zoom instead of view::zoom? We need both, as they denote different things ('tile' zoom versus real 'view' zoom; the latter can be fractional and in case of tile substitution can be either less or greater than tile zoom), also view::zoom is supported only in symbolizer expressions, not in selectors.

About ramp supporting linear interpolation, can you point me to an example?

**Comment by javisantana** [comment]
got it, but in general the `tile view` is actually `render zoom` which has the same meaning. We could use fractional zoom and make zoom to be available in expressions. 

From my point of view the meaning vary depending on where you use it: if you use it in linear is evaluated per frame if you use it in ramp it's evaluated with the dataset.

Anyway, having two zooms sounds like not good so let's try to unify them somehow. What would be the problems you had if zoom could we used in expressions and it would be float instead of int?

**Comment by mtehver** [comment]
Both [zoom] and [view::zoom] are useful in different places. In our test-style that uses [view::zoom], we also used [zoom] for rule filtering and [view::zoom] to provide smooth transitions. The processing of CartoCSS selectors to Mapnik rendering rules requires them to be known at tile decoding time, so if you used [view::zoom] there things would not work as expected. I do not think that it is possible to shift all the processing to rendering domain, as regenerating rendering rules from parsed CartoCSS takes about 0.5s for basemaps, so this is pretty heavy stuff. SDK has split CartoCSS processing into 3 domains (style loading domain, tile decoding domain, rendering domain) and the last one should be as light as possible. We support evaluation of CartoCSS symbolizer expressions in the rendering domain only, and do not support rebuilding rules, etc there.

As said before, I see both [zoom] and [view::zoom] being useful even when used with linear function. For example,

line-color: linear([zoom], (0, #fff), (5, #000))

vs

line-color: linear([view::zoom], (0, #fff), (5, #000))

Both are potentially useful depending on the style design. The [zoom] version can be implemented of course with selectors, but the linear version is more concise.

Note that there are limited number of symbolizer properties where per frame evaluation is really supported. For fonts, for example, SDK currently needs font size to be known at tile decoding time. If [view::zoom] is used for text-size, then [view::zoom] is internally replaced with [zoom] + 0.5 and the expression is evaluated. This provides a path for forward compatibility when additional dynamic properties are added to the renderer in the future.

**Comment by mtehver** [comment]
Closing this, as this is implemented has been available for a while now.
