### ISSUE TITLE
Online geocoding Service

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#90]
Uses https://github.com/CartoDB/mobile-tileserver/issues/38 service API. Use Pelias API with added appToken parameter.

**Comment by jaakla** [comment]
Use Mapzen Pelias URL to get started

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1. SDK has Pelias geocoding and reverse geocoding services that require MapZen API keys
