### ISSUE TITLE
Geocoding download for bbox

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#91]
* in SDK side: packagemanager should enable to download offline geocode packages for BBOX areas (e.g. cities).
* in server side: there is special extract API script which takes copy of corresponding country file (with restriction that bbox must be in single country) and deletes all data outside defined bbox.

**Comment by jaakla** [comment]
Customer case: Lonely Planet

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1
