### ISSUE TITLE
Clustering of 100k+ points

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#92]
Server side: enable processing of data table (CARTO table) to pre-generate clusters. These are not zoom-based like CDB_overviews, but hierarchical data structure, so result table is not standard mbtiles, but own structure. Otherwise logic somewhat similar to tippecanoe. 
Client side: use this table as offline point datasource, enable **animations** during zoom in/out similar to current small point set clustering feature.

**Comment by jaakla** [comment]
Customer case: HemaMaps (https://cartodb.supportbee.com/tickets/11625325)

**Comment by mtehver** [comment]
Develop branch now has much faster clustering with much lower memory footprint. On iPad2 it performs approximately 100k points/sec.

**Comment by jaakla** [comment]
Request from customer: can we serialize and cache clusters, to make next data loading faster?

**Comment by jaakla** [comment]
Comment from HEMA https://cartodb.supportbee.com/tickets/12152326

> Just one more question – since I no longer want to re-run clustering as it is all loadable at the start, I need to hide the cluster layer sometimes  for when we show certain app states.
> 
> The method setVisible on a ClusteredVectorLayer is really really slow for me.  I think it might be modifying the visible flag for every single marker object in memory.  
> 
> Is there a way to make this just skip rendering the clusters instead of updating the data if I set this to false?  Or is there another faster method I could call to hide the layer?
>

**Comment by jaakla** [comment]
Loading geojson is 10x faster with latest dev branch, need to be tested with slow devices.

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1
