### ISSUE TITLE
Scalable texts

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk#93]
Technically distance-field based text rendering. Enables calculate text size dynamically, i.e. create texts which are larger in higher zooms, without jumps between zoom levels.

Use cases:
* Indoor maps - room names should go larger when zoomed in. Gives more "paper map" zoom UX
* High-zoom street map - street names are growing in zoom 19+ to fill street space

**Comment by mtehver** [comment]
Part of SDK 4.1.0RC1
